### ISSUE TITLE
Unable to sync multisite DB locally

### ISSUE THREAD

**Issue by mariagwyn** [acquia/blt#1190]
My system information:
* BLT version: 8.6.15
* DrupalVM - rebuilt completely based on 8.6.15 specifications.
* Multisite section added to project/box/config.yml, am able to reach all installed multsites.

I have followed the instructions here: https://github.com/acquia/blt/blob/8.x/readme/multisite.md to add multisite setup. 

1. Added site_dir to multisite settings.php file.
```
/**
 * BLT/VM multisite settings
 */

$site_dir = 'magnoliatreemidwifery.com';
```
2. Defined multisites in blt/project.yml
```
multisite:
  name:
    - default
    - magnoliatreemidwifery.com
    - deiprofundis.org
```
3. Ensured that I have a working local alias in ~/.drush/magnoliatreemidwifery.aliases.drushrc.php. I confirmed that it properly reaches my ACE multisite. I am not sure this is necessary, but I did it.
4. Copied a new section into my project/drush/site-aliases/aliases.drushrc.php:
```
$aliases['magnoliatreemidwifery.local'] = array(
  // /var/www/[vagrant_machine_name]/docroot
  'root' => '/var/www/eemmcdowell/docroot',
  // vagrant_hostname
  'uri' => 'http://magnoliatreemidwifery.com',
  // vagrant_hostname
  'remote-host' => 'local.eemmcdowell',
  'remote-user' => 'vagrant',
  'ssh-options' => '-o PasswordAuthentication=no -i ' . drush_server_home() . '/.vagrant.d/insecure_private_key'
);
```
With this, I seem to be able to get local site information via drush.

When I run this command:
```
blt local:sync -Dmultisite.name=magnoliatreemidwifery.com -verbose
```

I get the following output:
```
Executing: gzip -d /tmp/eemmcdowedb79712_20170315_001555.sql.gz
Executing: mysql --defaults-extra-file=/tmp/drush_7o5fhh --database=magnoliatreemidwifery --host=localhost --port=3306 --silent  < /tmp/eemmcdowedb79712_20170315_001555.sql
Query failed.                                                                                                                                                                                        [error]
Command dispatch complete                                                                                                                                                                               [notice]
Command dispatch complete                                                                                                                                                                               [notice]
    [drush] Changing working directory back to /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/acquia/blt/phing.

BUILD FAILEDexception 'BuildException' with message '/Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/./vendor/acquia/blt/phing/tasks/local-sync.xml:22:8: /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/./vendor/acquia/blt/phing/tasks/local-sync.xml:25:43: Drush exited with code 1' in /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/acquia/blt/phing/phingcludes/DrushTask.php:353
Stack trace:
#0 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/UnknownElement.php(100): DrushTask->main()
#1 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#2 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/tasks/system/SequentialTask.php(58): Task->perform()
#3 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/tasks/system/IfTask.php(172): SequentialTask->main()
#4 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/TaskAdapter.php(61): IfTask->main(Object(Project))
#5 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/UnknownElement.php(100): TaskAdapter->main()
#6 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#7 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#8 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#9 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#10 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/Project.php(868): Project->executeTarget('local:sync')
#11 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/Phing.php(723): Project->executeTargets(Array)
#12 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/Phing.php(200): Phing->runBuild()
#13 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/classes/phing/Phing.php(347): Phing::start(Array, NULL)
#14 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)
#15 /Users/maria.mcdowell/Sites/devdesktop/eemmcdowell-prod/vendor/phing/phing/bin/phing(14): require_once('/Users/maria.mc...')
#16 {main}; 22.5439 seconds
```

Note that if I sync the DEFAULT, there are no errors. 

I am not sure if this is a drupalvm issue, or a blt issue.

**Comment by bobbygryzynger** [comment]
@geerlingguy - I'm finding I'm running into this issue too after upgrading to DrupalVM 4.3. It seems the correct `mysql` user may not be getting created in my case.

In `box/config.yml` I have:
```yml
mysql_databases:
  - name: "{{ drupal_db_name }}_default"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    # Grant all privileges on databases with the "{{ drupal_db_name }}_" prefix.
    priv: "{{ drupal_db_name }}\_%.*:ALL"
```
However, when I run 
```sql
SELECT User FROM mysql.user;
```
`{{ drupal_db_user }}` isn't listed (which is `admin`). Instead, my user table lists:
![screen shot 2017-03-17 at 6 12 32 pm](https://cloud.githubusercontent.com/assets/6345927/24064859/6915c1de-0b3d-11e7-826c-9342c04cbc1f.png)

Further, if I try to run `blt setup:drupal:install` I get:
```sql
Failed to create database: ERROR 1045 (28000): Access denied for user 'admin'@'localhost' (using password: YES)
```

Unlike @mariagwyn, I get the `Query failed` error message even when trying to sync my `default` site. I'm thinking this issue may belong in the [geerlingguy/drupal-vm](https://github.com/geerlingguy/drupal-vm) queue.

**Comment by geerlingguy** [comment]
@bobbygryzynger - The default for `drupal_db_user` is `drupal`... so that seems correct.

If you want to use `admin` as the db username, you'd have to set `drupal_db_user: admin` to override the default.

**Comment by bobbygryzynger** [comment]
@geerlingguy - I have also have this in `box/config.yml`:
```yml
drupal_db_user: admin
drupal_db_password: admin
```

**Comment by geerlingguy** [comment]
@bobbygryzynger - Ah, I see—in that case, did you run `vagrant provision`? And if so, can you post your log, specifically the section with `geerlingguy.mysql`-related tasks?

**Comment by bobbygryzynger** [comment]
@geerlingguy I did run `vagrant provision`. Currently running a `vagrant up` after a `vagrant destroy` I'll post when it's complete.

**Comment by geerlingguy** [comment]
Thanks!

**Comment by bobbygryzynger** [comment]
This looks to be the bulk of it. Let me know if the full output would be helpful.
```
TASK [geerlingguy.mysql : Include OS-specific variables.] **********************
ok: [octagon]

TASK [geerlingguy.mysql : Include OS-specific variables (RedHat).] *************
skipping: [octagon]

TASK [geerlingguy.mysql : Define mysql_packages.] ******************************
ok: [octagon]

TASK [geerlingguy.mysql : Define mysql_daemon.] ********************************
ok: [octagon]

TASK [geerlingguy.mysql : Define mysql_slow_query_log_file.] *******************
ok: [octagon]

TASK [geerlingguy.mysql : Define mysql_log_error.] *****************************
ok: [octagon]

TASK [geerlingguy.mysql : Define mysql_syslog_tag.] ****************************
ok: [octagon]

TASK [geerlingguy.mysql : Define mysql_pid_file.] ******************************
ok: [octagon]

TASK [geerlingguy.mysql : Define mysql_config_file.] ***************************
ok: [octagon]

TASK [geerlingguy.mysql : Define mysql_config_include_dir.] ********************
ok: [octagon]

TASK [geerlingguy.mysql : Define mysql_socket.] ********************************
ok: [octagon]

TASK [geerlingguy.mysql : Define mysql_supports_innodb_large_prefix.] **********
ok: [octagon]

TASK [geerlingguy.mysql : include] *********************************************
skipping: [octagon]

TASK [geerlingguy.mysql : include] *********************************************
included: /Users/rg173/Sites/octagon/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.mysql/tasks/setup-Debian.yml for octagon

TASK [geerlingguy.mysql : Check if MySQL is already installed.] ****************
ok: [octagon]

TASK [geerlingguy.mysql : Update apt cache if MySQL is not yet installed.] *****
changed: [octagon]

TASK [geerlingguy.mysql : Ensure MySQL Python libraries are installed.] ********
changed: [octagon]

TASK [geerlingguy.mysql : Ensure MySQL packages are installed.] ****************
changed: [octagon] => (item=[u'mysql-common', u'mysql-server'])

TASK [geerlingguy.mysql : Ensure MySQL is stopped after initial install.] ******
changed: [octagon]

TASK [geerlingguy.mysql : Delete innodb log files created by apt package after initial install.] ***
changed: [octagon] => (item=ib_logfile0)
changed: [octagon] => (item=ib_logfile1)

TASK [geerlingguy.mysql : Check if MySQL packages were installed.] *************
ok: [octagon]

TASK [geerlingguy.mysql : Copy my.cnf global MySQL configuration.] *************
changed: [octagon]

TASK [geerlingguy.mysql : Verify mysql include directory exists.] **************
skipping: [octagon]

TASK [geerlingguy.mysql : Copy my.cnf override files into include directory.] **

TASK [geerlingguy.mysql : Create slow query log file (if configured).] *********
changed: [octagon]
 [WARNING]: Consider using file module with state=touch rather than running
touch

TASK [geerlingguy.mysql : Create datadir if it does not exist] *****************
changed: [octagon]

TASK [geerlingguy.mysql : Set ownership on slow query log file (if configured).] ***
changed: [octagon]

TASK [geerlingguy.mysql : Create error log file (if configured).] **************
ok: [octagon]

TASK [geerlingguy.mysql : Set ownership on error log file (if configured).] ****
changed: [octagon]

TASK [geerlingguy.mysql : Ensure MySQL is started and enabled on boot.] ********
changed: [octagon]

TASK [geerlingguy.mysql : Get MySQL version.] **********************************
ok: [octagon]

TASK [geerlingguy.mysql : Ensure default user is present.] *********************
skipping: [octagon]

TASK [geerlingguy.mysql : Copy user-my.cnf file with password credentials.] ****
skipping: [octagon]

TASK [geerlingguy.mysql : Disallow root login remotely] ************************
ok: [octagon] => (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1'))

TASK [geerlingguy.mysql : Get list of hosts for the root user.] ****************
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..

This feature will be removed in version 2.4. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [octagon]

TASK [geerlingguy.mysql : Update MySQL root password for localhost root account (5.7.x).] ***
skipping: [octagon] => (item=127.0.0.1) 
skipping: [octagon] => (item=::1) 
skipping: [octagon] => (item=localhost) 

TASK [geerlingguy.mysql : Update MySQL root password for localhost root account (< 5.7.x).] ***
changed: [octagon] => (item=127.0.0.1)
changed: [octagon] => (item=::1)
changed: [octagon] => (item=localhost)

TASK [geerlingguy.mysql : Copy .my.cnf file with root password credentials.] ***
changed: [octagon]

TASK [geerlingguy.mysql : Get list of hosts for the anonymous user.] ***********
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..

This feature will be removed in version 2.4. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [octagon]

TASK [geerlingguy.mysql : Remove anonymous MySQL users.] ***********************

TASK [geerlingguy.mysql : Remove MySQL test database.] *************************
ok: [octagon]

TASK [geerlingguy.mysql : Ensure MySQL databases are present.] *****************
changed: [octagon] => (item={u'collation': u'utf8mb4_general_ci', u'name': u'drupal_default', u'encoding': u'utf8mb4'})
changed: [octagon] => (item={u'collation': u'utf8mb4_general_ci', u'name': u'drupal_touch', u'encoding': u'utf8mb4'})
changed: [octagon] => (item={u'collation': u'utf8mb4_general_ci', u'name': u'drupal_grad', u'encoding': u'utf8mb4'})

TASK [geerlingguy.mysql : Ensure MySQL users are present.] *********************
changed: [octagon] => (item=(censored due to no_log))

TASK [geerlingguy.mysql : Ensure replication user exists on master.] ***********
skipping: [octagon]

TASK [geerlingguy.mysql : Check slave replication status.] *********************
skipping: [octagon]

TASK [geerlingguy.mysql : Check master replication status.] ********************
skipping: [octagon]

TASK [geerlingguy.mysql : Configure replication on the slave.] *****************
skipping: [octagon]

TASK [geerlingguy.mysql : Start replication.] **********************************
skipping: [octagon]

TASK [geerlingguy.php-mysql : Include OS-specific variables.] ******************
ok: [octagon]

TASK [geerlingguy.php-mysql : Define php_mysql_package.] ***********************
skipping: [octagon]

TASK [geerlingguy.php-mysql : Install PHP MySQL dependencies (RedHat).] ********
skipping: [octagon]

TASK [geerlingguy.php-mysql : Install PHP MySQL dependencies (Debian).] ********
changed: [octagon]
```

**Comment by bobbygryzynger** [comment]
@geerlingguy - just to confirm, still seeing the same behavior after `vagrant destroy` followed by a `vagrant up`.

**Comment by geerlingguy** [comment]
The two relevant tasks are:

```
TASK [geerlingguy.mysql : Ensure MySQL databases are present.] *****************
changed: [octagon] => (item={u'collation': u'utf8mb4_general_ci', u'name': u'drupal_default', u'encoding': u'utf8mb4'})
changed: [octagon] => (item={u'collation': u'utf8mb4_general_ci', u'name': u'drupal_touch', u'encoding': u'utf8mb4'})
changed: [octagon] => (item={u'collation': u'utf8mb4_general_ci', u'name': u'drupal_grad', u'encoding': u'utf8mb4'})

TASK [geerlingguy.mysql : Ensure MySQL users are present.] *********************
changed: [octagon] => (item=(censored due to no_log))
```

Unfortunately, for security reasons, the users aren't printed to the console when that task runs.

Can you maybe just set the admin username directly in the config variable? Just set this:

```yaml
mysql_users:
  - name: admin
    host: "%"
    password: "the_password_here"
    # Grant all privileges on databases with the "{{ drupal_db_name }}_" prefix.
    priv: "{{ drupal_db_name }}\_%.*:ALL"
```

It could be that the `drupal_db_user` is getting cached somewhere.

**Comment by bobbygryzynger** [comment]
@geerlingguy, actually it seems that additional values are not being correctly picked up as I have `{{ drupal_db_name }}` set to `octagon` but `drupal` is being used to create the database name prefix.

**Comment by geerlingguy** [comment]
@bobbygryzynger - Can you create an issue in the Drupal VM issue queue for this? I don't think that the issue you're seeing is related to the one @mariagwyn originally reported. Her issue seems to have to do with the drush command/setup, and yours might be related to variable inheritance. I'd like to find a way to reproduce the issue in your case, so if you can post your full config.yml (obfuscated of course if there's anything that shouldn't be public), I can run an instance of Drupal VM locally and see if it's reproducible.

**Comment by geerlingguy** [comment]
@bobbygryzynger - I created a fresh Drupal VM instance with nothing overridden except for using the following variables inside `config.yml`:

```yaml
drupal_db_user: admin
drupal_db_password: admin

mysql_databases:
  - name: "{{ drupal_db_name }}_default"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    # Grant all privileges on databases with the "{{ drupal_db_name }}_" prefix.
    priv: "{{ drupal_db_name }}\_%.*:ALL"
```

After I brought up the VM, I checked the available databases, and got:

```
vagrant@drupalvm:~$ mysql -uroot -p -e "SELECT User FROM mysql.user;"
Enter password: 
+------------------+
| User             |
+------------------+
| admin            |
| root             |
| root             |
| debian-sys-maint |
| root             |
+------------------+
```

**Comment by bobbygryzynger** [comment]
@geerlingguy - scratch this issue, I finally noticed what's going on here. After running `blt vm:nuke` and then `blt vm` I reverted some of the changes in order to keep my customizations and there ended up being two blocks defining ` {{ drupal_db_name}}`, `{{ drupal_db_user }}` and
`{{ drupal_db_password }}` - one overwriting the other, causing this behavior.

I'm not sure if something similar could be causing @mariagwyn issues, but it's certainly worth a look. I'm now able to run my syncing tasks without any problems. Thanks for your help on this, sorry it was such an obvious mistake on my part.

**Comment by geerlingguy** [comment]
Ah, that would do it, no problem!

**Comment by grasmash** [comment]
I think this issue is resolved? Looks like @mariagwyn opened it but @bobbygryzynger did subsequent debugging. Let me know if this needs to be re-opened.

**Comment by mariagwyn** [comment]
@grasmash: I don't think that @bobbygryzynger's issue is my issue. His appears to be related to DrupalVM. Mine is specific to syncing between Acquia DBs and DrupalVM using BLT. I can open a new issue if there is too much unrelated conversation on this.
