### ISSUE TITLE
Ability to Run Behat Tests on Deployment

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1588]
As a developer I want to be able to run behat tests from cloudhooks to smoke test a deployment. It will also let me test things that I can't test in a container like CDN behavior.

When I try I get an error :(.  The reason makes sense
```
mysub@staging-11111:/var/www/html/mysub.dev$ ./vendor/bin/blt tests:behat -D behat.run-server=true -D behat.launch-selenium=false -D behat.launch-phantomjs=false -D behat.tags='~experimental' --yes -v
[warning] /var/www/html/mysubdev/docroot/sites/mysite.com/settings/local.settings.php is missing.

Warning: file(/var/www/html/mysubdev/docroot/sites/mysite.com/local.drushrc.php): failed to open stream: No such file or directory in /mnt/www/html/mysubdev/vendor/acquia/blt/src/Robo/Config/BltConfig.php on line 20

Fatal error: Uncaught TypeError: Argument 1 passed to Dflydev\DotAccessData\Data::__construct() must be of the type array or null, boolean given, called in /mnt/www/html/mysubdev/vendor/grasmash/yaml-expander/src/Expander.php on line 51 and defined in /mnt/www/html/mysubdev/vendor/dflydev/dot-access-data/src/Dflydev/DotAccessData/Data.php:28
Stack trace:
#0 /mnt/www/html/mysubdev/vendor/grasmash/yaml-expander/src/Expander.php(51): Dflydev\DotAccessData\Data->__construct(false)
#1 /mnt/www/html/mysubdev/vendor/acquia/blt/src/Robo/Config/BltConfig.php(20): Grasmash\YamlExpander\Expander::expandArrayProperties(false, Array)
#2 /mnt/www/html/mysubdev/vendor/acquia/blt/src/Robo/Commands/Setup/SettingsCommand.php(68): Acquia\Blt\Robo\Config\BltConfig->expandFileProperties('/var/www/html/w...')
#3 [internal function]: Acquia\Blt\Robo\Commands\Setup\SettingsCommand->generateSiteConfigFiles(Array)
#4 /mnt/www/html/mysubdev/vendor/consolidation/annotated-command/src/CommandProcessor.php(207): call_user_func_array(Array, Array)
#5 /mnt/ww in /mnt/www/html/mysubdev/vendor/dflydev/dot-access-data/src/Dflydev/DotAccessData/Data.php on line 28
[warning] project.local.uri in project.yml does not match local.extensions.Behat\MinkExtension.base_url in local.yml.
[warning] project.local.uri = http://127.0.0.1:8888
[warning] local.extensions.Behat\MinkExtension.base_url =
[warning] Behat is not configured properly.
[warning] project.local.uri in project.yml does not match local.extensions.Behat\MinkExtension.base_url in local.yml.
[warning] project.local.uri = http://127.0.0.1:8888
[warning] local.extensions.Behat\MinkExtension.base_url =
[error]  Behat is not configured properly. Please run `blt doctor` to diagnose the issue.
mysub@staging-11111:/var/www/html/mysubdev$ ./vendor/bin/blt tests:behat -D behat.run-server=true -D behat.launch-selenium=false -D behat.launch-phantomjs=false -D behat.tags='~experimental^C--yes -v
```

**Comment by grasmash** [comment]
Seems like you could workaround this fairly easily by committing the required local.settings.file, right? I don't think BLT should do that for you.

Do you have another solution in mind?

**Comment by aweingarten** [comment]
@grasmash, I'll try it.  Committing a local file feels wrong, are you suggesting to commit on with the deployment?  Will test and report back.

**Comment by grasmash** [comment]
@aweingarten results?

**Comment by grasmash** [comment]
I am closing this issue due to inactivity. Please ping me on this issue if you feel that it needs reopened.

**Comment by saranyapurushothaman** [comment]
This issue because of shortcut in your projectfolder. Remove the shortcut file and move your test folder outside the docroot.
