### ISSUE TITLE
Failed Feature Import Does Not Fail Build

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#1971]
My system information:
* Operating system type: [replace]
* Operating system version: [replace]
* BLT version: 8.9.1

When I run this command:
```
blt setup:config-import
```

I get the following output:
```
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/<project>/vendor/bin/drush @self features-import-all --bundle=<project> --uri=default --yes in /var/www/<project>/docroot
exception 'Exception' with message 'No entity type for field title on view multi_platform_blocks' in                                                             [error]
/var/www/<project>/docroot/core/modules/views/src/Plugin/views/HandlerBase.php:697
Stack trace:
#0 /var/www/<project>/docroot/core/modules/views/src/Plugin/views/field/EntityField.php(791): Drupal\views\Plugin\views\HandlerBase->getEntityType()
#1 /var/www/<project>/docroot/core/modules/views/src/Plugin/views/field/EntityField.php(1015): Drupal\views\Plugin\views\field\EntityField->getEntityFieldRenderer()
#2 /var/www/<project>/docroot/core/lib/Drupal/Core/Cache/CacheableMetadata.php(171): Drupal\views\Plugin\views\field\EntityField->getCacheContexts()
#3 /var/www/<project>/docroot/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2277):
Drupal\Core\Cache\CacheableMetadata::createFromObject(Object(Drupal\views\Plugin\views\field\EntityField))
#4 /var/www/<project>/docroot/core/modules/views/src/Entity/View.php(326): Drupal\views\Plugin\views\display\DisplayPluginBase->calculateCacheMetadata()
#5 /var/www/<project>/docroot/core/modules/views/src/Entity/View.php(300): Drupal\views\Entity\View->addCacheMetadata()
#6 /var/www/<project>/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(434):
Drupal\views\Entity\View->preSave(Object(Drupal\Core\Config\Entity\ConfigEntityStorage))
#7 /var/www/<project>/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(389):
Drupal\Core\Entity\EntityStorageBase->doPreSave(Object(Drupal\views\Entity\View))
#8 /var/www/<project>/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(259):
Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\views\Entity\View))
#9 /var/www/<project>/docroot/core/lib/Drupal/Core/Entity/Entity.php(364): Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object(Drupal\views\Entity\View))
#10 /var/www/<project>/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php(637): Drupal\Core\Entity\Entity->save()
#11 /var/www/<project>/docroot/core/lib/Drupal/Core/Config/ConfigInstaller.php(341): Drupal\Core\Config\Entity\ConfigEntityBase->save()
#12 /var/www/<project>/docroot/modules/contrib/features/src/FeaturesConfigInstaller.php(106): Drupal\Core\Config\ConfigInstaller->createConfiguration('', Array)
#13 /var/www/<project>/docroot/modules/contrib/features/src/FeaturesManager.php(1357): Drupal\features\FeaturesConfigInstaller->createConfiguration('', Array)
#14 /var/www/<project>/docroot/modules/contrib/features/drush/features.drush.inc(659): Drupal\features\FeaturesManager->createConfiguration(Array)
#15 [internal function]: drush_features_import('<project>_base_fiel...', '<project>_images', '<project>_message', '<project>_multi_pla...', '<project>_platform', '<project>_route',
'<project>_route_gro...', '<project>_screen', '<project>_station', '<project>_user', '<project>_views')
#16 /var/www/<project>/docroot/modules/contrib/features/drush/features.drush.inc(289): call_user_func_array('drush_features_...', Array)
#17 [internal function]: drush_features_import_all()
#18 /var/www/<project>/vendor/drush/drush/includes/command.inc(422): call_user_func_array('drush_features_...', Array)
#19 /var/www/<project>/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#20 [internal function]: drush_command()
#21 /var/www/<project>/vendor/drush/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#22 /var/www/<project>/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#23 /var/www/<project>/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#24 /var/www/<project>/vendor/drush/drush/drush.php(12): drush_main()
#25 {main}
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 38.693s
Checking for features overrides...

```

And I expected this to happen:
In this case, we have bad config in a feature that we need to fix. However, we got all the way down to our behat tests in travis before we noticed it. I found the failure later on when I was debugging the problem.

i would expect that the BLT process should fail but in this case (it does), but then it continued going and didn't actually cause anything to "stop" after the exit code.

**Comment by mikemadison13** [comment]
this appears to be resolved in the 8.x-dev branch.
