### ISSUE TITLE
BLT + Probo Behat integration issues

### ISSUE THREAD

**Issue by zweishar** [acquia/blt#2004]
I've been attempting to set up the integration with `probo.ci` that blt now comes with (thanks very much for adding this btw). Unfortunately it seems like behat tests do not execute properly on probo with the current state of this integration, however they do work well on my local machine.

BLT Version: `8.9.2`

I've modified the `probo.yml` file ever so slightly, and copied the setup script from `vendor/acquia/blt/scripts/probo/setup_environment` into my project so that it can be run before `composer install`. Here are the contents of `probo.yml`:

```
---
image: proboci/ubuntu-14.04-lamp:php-5.6

# Reference the database file uploaded to probo's /assets
assets:
  - db.sql.gz

steps:
  - name: Make drush wrapper executable
    plugin: Script
    script:
      - cd $SRC_DIR
      - chmod +x drush.wrapper

  - name: 'Before install'
    plugin: Script
    script:
     - cd $SRC_DIR
     - chmod -R 777 ./
     - "PHP_VERSION='5.6' ${SRC_DIR}/scripts/probo/setup_environment"
     - composer self-update
     - composer validate --no-check-all --ansi
     - composer install
     - composer run-script blt-alias

  - name: 'Install Drupal'
    plugin: Drupal
    drupalVersion: 8
    subDirectory: docroot
    # The database listed under assets
    database: db.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    clearCaches: true

  - name: 'Setup project'
    plugin: Script
    script:
     - "$SRC_DIR/vendor/acquia/blt/scripts/probo/setup_project"

  - name: 'Run tests'
    plugin: Script
    script:
      - echo $PATH
      - "$SRC_DIR/vendor/acquia/blt/scripts/probo/run_tests"
```

When executing non-javascript tests, I get this stack trace:
```
Scenario: Load a page with Javascript # features/Examples.feature:8
53    Given I am on "/"                   # Drupal\DrupalExtension\Context\MinkContext::visit()
54    Then I should see the text "Log in" # Drupal\DrupalExtension\Context\MinkContext::assertTextVisible()
55      exception 'Behat\Mink\Exception\DriverException' with message 'There is no element matching XPath "//html"' in /src/vendor/behat/mink-browserkit-driver/src/BrowserKitDriver.php:839
56      Stack trace:
57      #0 /src/vendor/behat/mink-browserkit-driver/src/BrowserKitDriver.php(347): Behat\Mink\Driver\BrowserKitDriver->getFilteredCrawler('//html')
58      #1 /src/vendor/behat/mink/src/Element/Element.php(176): Behat\Mink\Driver\BrowserKitDriver->getText('//html')
59      #2 /src/vendor/behat/mink/src/WebAssert.php(257): Behat\Mink\Element\Element->getText()
60      #3 /src/vendor/behat/mink-extension/src/Behat/MinkExtension/Context/MinkContext.php(292): Behat\Mink\WebAssert->pageTextContains('Log in')
61      #4 /src/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/MinkContext.php(499): Behat\MinkExtension\Context\MinkContext->assertPageContainsText('Log in')
62      #5 [internal function]: Drupal\DrupalExtension\Context\MinkContext->assertTextVisible('Log in')
63      #6 /src/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(103): call_user_func_array(Array, Array)
64      #7 /src/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(59): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
65      #8 /src/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(140): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
66      #9 /src/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(96): Behat\Testwork\Call\CallCenter->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
67      #10 /src/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(125): Behat\Testwork\Call\CallCenter->makeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
68      #11 /src/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(73): Behat\Behat\Tester\Runtime\RuntimeStepTester->testDefinition(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), Object(Behat\Behat\Definition\SearchResult), false)
69      #12 /src/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableStepTester.php(74): Behat\Behat\Tester\Runtime\RuntimeStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
70      #13 /src/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/TickingStepTester.php(59): Behat\Behat\Hook\Tester\HookableStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
71      #14 /src/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingStepTester.php(73): Behat\Behat\EventDispatcher\Tester\TickingStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
72      #15 /src/vendor/behat/behat/src/Behat/Behat/Tester/StepContainerTester.php(59): Behat\Behat\EventDispatcher\Tester\EventDispatchingStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
73      #16 /src/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeScenarioTester.php(76): Behat\Behat\Tester\StepContainerTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
74      #17 /src/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(74): Behat\Behat\Tester\Runtime\RuntimeScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
75      #18 /src/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(103): Behat\Behat\Hook\Tester\HookableScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
76      #19 /src/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php(69): Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
77      #20 /src/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(84): Behat\Behat\Tester\Runtime\IsolatingScenarioTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
78      #21 /src/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
79      #22 /src/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(71): Behat\Behat\Hook\Tester\HookableFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
80      #23 /src/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
81      #24 /src/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
82      #25 /src/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(72): Behat\Testwork\Hook\Tester\HookableSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
83      #26 /src/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
84      #27 /src/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(70): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
85      #28 /src/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
86      #29 /src/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test(Array, false)
87      #30 /src/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
88      #31 /src/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
89      #32 /src/vendor/symfony/console/Command/Command.php(266): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
90      #33 /src/vendor/symfony/console/Application.php(875): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
91      #34 /src/vendor/symfony/console/Application.php(204): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
92      #35 /src/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
93      #36 /src/vendor/symfony/console/Application.php(122): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
94      #37 /src/vendor/behat/behat/bin/behat(34): Symfony\Component\Console\Application->run()
95      #38 {main}
```

When running javascript tests, I get the following stack trace:
```
@javascript
53  Scenario: Load a page with Javascript # features/Examples.feature:9
54    Given I am on "/"                   # Drupal\DrupalExtension\Context\MinkContext::visit()
55      exception 'WebDriver\Exception\UnknownError' with message 'The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html' in /src/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
56      Stack trace:
57      #0 /src/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(157): WebDriver\Exception::factory(13, 'The path to the...')
58      #1 /src/vendor/instaclick/php-webdriver/lib/WebDriver/WebDriver.php(71): WebDriver\AbstractWebDriver->curl('POST', '/session', Array, Array)
59      #2 /src/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(287): WebDriver\WebDriver->session('chrome', Array)
60      #3 /src/vendor/behat/mink/src/Session.php(70): Behat\Mink\Driver\Selenium2Driver->start()
61      #4 /src/vendor/behat/mink/src/Mink.php(117): Behat\Mink\Session->start()
62      #5 /src/vendor/behat/mink-extension/src/Behat/MinkExtension/Context/RawMinkContext.php(108): Behat\Mink\Mink->getSession(NULL)
63      #6 /src/vendor/behat/mink-extension/src/Behat/MinkExtension/Context/RawMinkContext.php(131): Behat\MinkExtension\Context\RawMinkContext->getSession(NULL)
64      #7 /src/vendor/behat/mink-extension/src/Behat/MinkExtension/Context/MinkContext.php(49): Behat\MinkExtension\Context\RawMinkContext->visitPath('/')
65      #8 [internal function]: Behat\MinkExtension\Context\MinkContext->visit('/')
66      #9 /src/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(103): call_user_func_array(Array, Array)
67      #10 /src/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(59): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
68      #11 /src/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(140): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
69      #12 /src/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(96): Behat\Testwork\Call\CallCenter->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
70      #13 /src/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(125): Behat\Testwork\Call\CallCenter->makeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
71      #14 /src/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(73): Behat\Behat\Tester\Runtime\RuntimeStepTester->testDefinition(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), Object(Behat\Behat\Definition\SearchResult), false)
72      #15 /src/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableStepTester.php(74): Behat\Behat\Tester\Runtime\RuntimeStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
73      #16 /src/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/TickingStepTester.php(59): Behat\Behat\Hook\Tester\HookableStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
74      #17 /src/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingStepTester.php(73): Behat\Behat\EventDispatcher\Tester\TickingStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
75      #18 /src/vendor/behat/behat/src/Behat/Behat/Tester/StepContainerTester.php(59): Behat\Behat\EventDispatcher\Tester\EventDispatchingStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
76      #19 /src/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeScenarioTester.php(76): Behat\Behat\Tester\StepContainerTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
77      #20 /src/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(74): Behat\Behat\Tester\Runtime\RuntimeScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
78      #21 /src/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(103): Behat\Behat\Hook\Tester\HookableScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
79      #22 /src/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php(69): Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
80      #23 /src/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(84): Behat\Behat\Tester\Runtime\IsolatingScenarioTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
81      #24 /src/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
82      #25 /src/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(71): Behat\Behat\Hook\Tester\HookableFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
83      #26 /src/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
84      #27 /src/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
85      #28 /src/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(72): Behat\Testwork\Hook\Tester\HookableSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
86      #29 /src/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
87      #30 /src/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(70): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
88      #31 /src/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
89      #32 /src/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test(Array, false)
90      #33 /src/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
91      #34 /src/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
92      #35 /src/vendor/symfony/console/Command/Command.php(266): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
93      #36 /src/vendor/symfony/console/Application.php(875): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
94      #37 /src/vendor/symfony/console/Application.php(204): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
95      #38 /src/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
96      #39 /src/vendor/symfony/console/Application.php(122): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
97      #40 /src/vendor/behat/behat/bin/behat(34): Symfony\Component\Console\Application->run()
98      #41 {main}
```

I've sunk some time into debugging this, but I'm a bit stumped. If anyone has any insight to help me get to the bottom of this I'm happy to submit a PR to fix this.

**Comment by zweishar** [comment]
I should also note that I attempted to fix the javascript test errors by installing `chromedriver` in the `setup_environment` script. That got me a little further but still ultimately does not work.

**Comment by grasmash** [comment]
I don't currently have access to a Probo environment to debug this myself, so there might be a good bit of back-and-forth here.

Do you know if Google Chrome is available inside of the Probo environment?

**Comment by grasmash** [comment]
I opened #2011  at the starting point for this issue.

I didn't actually write the Probo integration, but #2011 is a representation of how I would approach the task.  It might contain the necessary fix.

It might also break the Drupal installation process. I'm not sure if it's necessary to use the Probo specific syntax for installation, or if it is sufficient to execute the normal BLT command for doing so.
 I'm referring to this code removal: https://github.com/acquia/blt/pull/2011/files#diff-f4bb78b23d00270f4fa802ad5fb3724cL14

I suspect that the more direct cause of your issue is solved by this line: https://github.com/acquia/blt/pull/2011/files#diff-c8d29352ffcd806b5541e0ac57bee65aR9

**Comment by zweishar** [comment]
Thanks for the quick response grasmash.

Google chrome is available:
`Google Chrome 61.0.3163.100`

I'll dig into these issues and see if any of them allow my tests to run. I'll comment back here with my findings.

**Comment by thom8** [comment]
For debugging you can use the public containers @ https://hub.docker.com/r/proboci/ubuntu-16.04-lamp/

RE: #2011 -- there are some things done by the probo drupal task to make sure the site is accessible after the build.

**Comment by danepowell** [comment]
@zweishar are you able to test the changes here? https://github.com/acquia/blt/pull/2011

**Comment by typhonius** [comment]
I've been in touch with Probo about some of the issues we've had and it turns out that the containers that were used did not have an up to date version of Google Chrome in which in turn caused issues when trying to test with Behat.

Probo have rolled some new images which may remedy some of the issues seen in this thread:
```
proboci/ubuntu-14.04-lamp:php5.6-nightly
proboci/ubuntu-14.04-lamp:php7.0-nightly
proboci/ubuntu-14.04-lamp:php7.1-nightly
```

**Comment by danepowell** [comment]
Maybe we need to depend on those, and more generally test for compatible versions of Chrome before running tests.

**Comment by grasmash** [comment]
Closing due to inactivity. It's a cool idea but I don't think we can support extra CI scope.
