### ISSUE TITLE
blt setup:all error

### ISSUE THREAD

**Issue by debdattasarkar** [acquia/blt#2376]
My system information:
* Operating system type: mac OS High Sierra
* Operating system version: 10.13.1
* BLT version: 8.9.6

Output of `blt doctor`:
```
Drupal VM was detected. Running blt doctor inside of VM...
Executing command cd /var/www/dep/docroot/.. && /var/www/dep/docroot/../vendor/bin/drush cc drush && /var/www/dep/docroot/../vendor/bin/drush --include=/var/www/dep/docroot/../vendor/acquia/blt/drush blt-doctor -r /var/www/dep/docroot/../docroot inside of Drupal VM...
'drush' cache was cleared.                                                                                                                                                                       [success]
+----------------------+------------------------------------------------------------------------------+
| Property             | Value                                                                        |
+----------------------+------------------------------------------------------------------------------+
| %paths               |                                                                              |
|  - %root             | /var/www/dep/docroot                                                         |
|  - %site             | sites/default                                                                |
|  - %modules          | modules                                                                      |
|  - %themes           | themes                                                                       |
|  - %config-sync      | /var/www/dep/config/default                                                  |
| blt-version          | 8.9.6                                                                        |
| config-sync          | /var/www/dep/config/default                                                  |
| db-driver            | mysql                                                                        |
| db-hostname          | localhost                                                                    |
| db-name              | drupal                                                                       |
| db-password          | drupal                                                                       |
| db-port              | 3306                                                                         |
| db-username          | drupal                                                                       |
| dev-desktop-enabled  | false                                                                        |
| drupal-settings-file | sites/default/settings.php                                                   |
| drupal-version       | 8.3.7                                                                        |
| drupal-vm-enabled    | true                                                                         |
| drush-alias-files    | /var/www/dep/docroot/../drush/site-aliases/example.local.aliases.drushrc.php |
|                      | /var/www/dep/docroot/../drush/site-aliases/centrica-acsf.aliases.drushrc.php |
|                      | /var/www/dep/docroot/../drush/site-aliases/aliases.drushrc.php               |
|                      | /var/www/dep/docroot/../drush/site-aliases/example.acsf.aliases.drushrc.php  |
| drush-conf           | /var/www/dep/drush/drushrc.php                                               |
| drush-script         | /var/www/dep/vendor/drush/drush/drush.php                                    |
| drush-temp           | /tmp                                                                         |
| drush-version        | 8.1.14                                                                       |
| local-drushrc        | /var/www/dep/docroot/sites/default/local.drushrc.php                         |
| local-settings       | /var/www/dep/docroot/sites/default/settings/local.settings.php               |
| modules              | modules                                                                      |
| php-bin              | /usr/bin/php                                                                 |
| php-conf             | /etc/php/5.6/cli/php.ini                                                     |
| php-mysql            | /var/run/mysqld/mysqld.sock                                                  |
| php-os               | Linux                                                                        |
| root                 | /var/www/dep/docroot                                                         |
| shell                |                                                                              |
| site                 | sites/default                                                                |
| themes               | themes                                                                       |
| uri                  | http://local.dep.com                                                         |
+----------------------+------------------------------------------------------------------------------+
+--------------------------+-------------------------------------------------------------+
| Check                    | Outcome                                                     |
+--------------------------+-------------------------------------------------------------+
| checkDocrootExists       | Found docroot.                                              |
| checkCoreExists          | Drupal core exists                                          |
| checkSettingsFile        | BLT settings are included in settings file.                 |
| checkLocalSettingsFile   | Found your local settings file.                             |
| checkLocalDrushFile      | Found your local drush settings file.                       |
| checkUri                 | $options['uri'] is set.                                     |
| checkUriResponse         | Received a response from site http://local.dep.com.         |
| checkFileSystem:%files   | Public files directory is not set.                          |
| checkFileSystem:%private | Private files directory is not set.                         |
| checkFileSystem:%temp    | Temporary files directory is not set.                       |
| checkDbConnection        | Connected to database.                                      |
| checkDrupalBootstrapped  | Could not bootstrap Drupal via drush without alias.         |
| checkDrupalInstalled     | Drupal is not installed.                                    |
|                          |                                                             |
|                          | Run `blt local:setup` to install Drupal locally.            |
| checkCaching:page        | Drupal cache is disabled.                                   |
| checkCaching:css         | CSS preprocessing is disabled.                              |
| checkCaching:js          | JS preprocessing is disabled.                               |
| checkCiConfig            | Git remotes are set in project.yml.                         |
| checkComposer:require    | acquia/blt is in composer.json's require object.            |
| checkBehat:exists        | Behat local settings file exists.                           |
| checkBehat:root          | Behat drupal_root is set correctly for Drupal VM.           |
| checkProjectYml:keys     | project.yml has no deprecated keys.                         |
| checkAcsfConfig          | BLT settings are included in your pre-settings-php include. |
| checkDrupalVm:alias      | drush.aliases.local exists your drush aliases file.         |
| checkDrupalVm            | Drupal VM is configured correctly.                          |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set              |
+--------------------------+-------------------------------------------------------------+
Connection to 127.0.0.1 closed.

```

When I run this command:
```
blt setup:all
```

I get the following output:
```
blt setup:all
Setting up local environment for site 'default' using drush alias @dep.local
> setup:build
> setup:behat
Executing command blt setup:behat --define drush.alias=self inside of Drupal VM...
[warning] The xDebug extension is loaded. This will significantly decrease performance.
Connection to 127.0.0.1 closed.
> setup:composer:install
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> setup:git-hooks
Installing pre-commit git hook...
Installing commit-msg git hook...
> setup:settings
> frontend
Executing command blt frontend --define drush.alias=self inside of Drupal VM...
[warning] The xDebug extension is loaded. This will significantly decrease performance.
> frontend:setup
Executing frontend-setup target hook...
[ExecStack] echo 'No frontend-setup configured.'
[ExecStack] Running echo 'No frontend-setup configured.' in /var/www/dep/docroot
No frontend-setup configured.
[ExecStack] Done in 0.011s
> frontend:build
Executing frontend-build target hook...
[ExecStack] echo 'No frontend-build configured.'
[ExecStack] Running echo 'No frontend-build configured.' in /var/www/dep/docroot
No frontend-build configured.
[ExecStack] Done in 0.004s
Connection to 127.0.0.1 closed.
Executing post-setup-build target hook...
[ExecStack] echo 'No post-setup build configured.'
[ExecStack] Running echo 'No post-setup build configured.' in /Users/debdattasarkar/sites/dep/docroot
No post-setup build configured.
[ExecStack] Done in 0.005s
> setup:hash-salt
Hash salt already exists.
> setup:drupal:install
Executing command blt setup:drupal:install --define drush.alias=self inside of Drupal VM...
[warning] The xDebug extension is loaded. This will significantly decrease performance.
> internal:drupal:install
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/dep/vendor/bin/drush @self site-install dep_site install_configure_form.update_status_module='array(FALSE,FALSE)' install_configure_form.enable_update_status_module=NULL --site-name=Dep --site-mail=no-reply@acquia.com --account-name=AVluVgmSYn --account-mail=no-reply@acquia.com --locale=en --uri=default --yes --verbose in /var/www/dep/docroot
Executing: mysql --defaults-extra-file=/tmp/drush_5akqAg --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_ckrLFG > /dev/null
You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
Sites directory /var/www/dep/docroot/sites/default already exists - proceeding.                                                                                                                     [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_NHFMrq --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_GmX4vQ > /dev/null
Executing: mysql --defaults-extra-file=/tmp/drush_hgUBkA --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_yX9ao0
Executing: mysql --defaults-extra-file=/tmp/drush_bUxTeK --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_ccUIha
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                                                     [ok]
exception 'Drupal\Core\Config\UnmetDependenciesException' with message 'Configuration objects provided by <em class="placeholder">acquia_search</em> have unmet dependencies: <em                [error]
class="placeholder">search_api.index.acquia_search_index (field.storage.node.body, node)</em>' in /var/www/dep/docroot/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:98
Stack trace:
#0 /var/www/dep/docroot/core/lib/Drupal/Core/Config/ConfigInstaller.php(480): Drupal\Core\Config\UnmetDependenciesException::create('acquia_search', Array)
#1 /var/www/dep/docroot/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132): Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'acquia_search')
#2 /var/www/dep/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(141): Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'acquia_search')
#3 /var/www/dep/docroot/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#4 /var/www/dep/docroot/core/includes/install.core.inc(1808): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, false)
#5 [internal function]: _install_module_batch('acquia_search', 'Acquia search', Array)
#6 /var/www/dep/docroot/core/includes/batch.inc(252): call_user_func_array('_install_module...', Array)
#7 /var/www/dep/docroot/core/includes/form.inc(876): _batch_process()
#8 /var/www/dep/docroot/core/includes/install.core.inc(625): batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#9 /var/www/dep/docroot/core/includes/install.core.inc(546): install_run_task(Array, Array)
#10 /var/www/dep/docroot/core/includes/install.core.inc(117): install_run_tasks(Array)
#11 /var/www/dep/vendor/drush/drush/includes/drush.inc(726): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#12 /var/www/dep/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)
#13 /var/www/dep/vendor/drush/drush/commands/core/drupal/site_install.inc(82): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#14 /var/www/dep/vendor/drush/drush/commands/core/site_install.drush.inc(255): drush_core_site_install_version('dep_site', Array)
#15 [internal function]: drush_core_site_install('dep_site', 'install_configu...', 'install_configu...')
#16 /var/www/dep/vendor/drush/drush/includes/command.inc(422): call_user_func_array('drush_core_site...', Array)
#17 /var/www/dep/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#18 [internal function]: drush_command('dep_site', 'install_configu...', 'install_configu...')
#19 /var/www/dep/vendor/drush/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#20 /var/www/dep/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#21 /var/www/dep/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#22 /var/www/dep/vendor/drush/drush/drush.php(12): drush_main()
#23 {main}
Command dispatch complete                                                                                                                                                                           [notice]
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 8.092s
[error]   
[error]  Command `internal:drupal:install ` exited with code 1. 
Connection to 127.0.0.1 closed.
> setup:toggle-modules
Executing command blt setup:toggle-modules --define drush.alias=self inside of Drupal VM...
[warning] The xDebug extension is loaded. This will significantly decrease performance.
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/dep/vendor/bin/drush @self pm-enable dblog devel seckit views_ui kint --uri=default --yes in /var/www/dep/docroot
The following extensions will be enabled: dblog, devel, seckit, views_ui, kint
Do you really want to continue? (y/n): y
dblog was enabled successfully.                                                                                                                                                                  [ok]
devel was enabled successfully.                                                                                                                                                                  [ok]
devel defines the following permissions: access devel information, execute php code, switch users
kint was enabled successfully.                                                                                                                                                                   [ok]
kint defines the following permissions: access kint
seckit was enabled successfully.                                                                                                                                                                 [ok]
seckit defines the following permissions: administer seckit
views_ui was enabled successfully.                                                                                                                                                               [ok]
views_ui defines the following permissions: administer views
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 5.486s
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/dep/vendor/bin/drush @self pm-uninstall acsf acquia_connector shield --uri=default --yes in /var/www/dep/docroot
acsf is already uninstalled.                                                                                                                                                                     [ok]
shield is already uninstalled.                                                                                                                                                                   [ok]
The following extensions will be uninstalled: acquia_connector
Do you really want to continue? (y/n): y
acquia_connector was successfully uninstalled.                                                                                                                                                   [ok]
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 2.576s
Connection to 127.0.0.1 closed.
> install-alias
The BLT alias is already installed and up to date.

```

And I expected this to happen:

**Comment by grasmash** [comment]
This is an issue with your exported configuration. 

> exception 'Drupal\Core\Config\UnmetDependenciesException' with message 'Configuration objects provided by <em class="placeholder">acquia_search</em> have unmet dependencies: <em                [error]
class="placeholder">search_api.index.acquia_search_index (field.storage.node.body, node)</em>' in /var/www/dep/docroot/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:98
Stack trace:

acquia_search requires `search_api.index.acquia_search_index (field.storage.node.body, node)`, but it's missing.

**Comment by grasmash** [comment]
I suggest running `/var/www/dep/vendor/bin/drush @self site-install dep_site install_configure_form.update_status_module='array(FALSE,FALSE)' install_configure_form.enable_update_status_module=NULL --site-name=Dep --site-mail=no-reply@acquia.com --account-name=AVluVgmSYn --account-mail=no-reply@acquia.com --locale=en --uri=default --yes --verbose` directly to debug.

Closing as this is an application issue rather than a BLT issue.
