### ISSUE TITLE
Drupal 8.4.4 install failing due to lightning_workflow unmet dependencies

### ISSUE THREAD

**Issue by energee** [acquia/blt#2479]
My system information:
* Operating system type: Mac OS X / Travis & Docker
* Operating system version: 10.13.2
* BLT version: 8.9.12
* Drupal version: 8.4.4
* Lighting version: 2.2.7 (Same error with 3.0.1)

No issues with blt doctor

When I run this command:
```
blt setup:drupal:install  
```

I get the following output:
```
> internal:drupal:install
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/abilify/vendor/bin/drush site-install otsuka install_configure_form.update_status_module='array(FALSE,FALSE)' install_configure_form.enable_update_status_module=NULL --site-name='Abilify Mycite' --site-mail=no-reply@acquia.com --account-name='r3+Lu6f0Z5' --account-mail=no-reply@acquia.com --locale=en --config-dir=../config/default --uri=mycite.dd --yes --verbose in /var/www/abilify/docroot
Configuration import directory ../config/default does not contain any configuration; will skip import.                                                                                           [warning]
Executing: mysql --defaults-extra-file=/tmp/drush_3E5Jer --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_eKUr8M > /dev/null
You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
Sites directory /var/www/xxx/docroot/sites/default already exists - proceeding.                                                                                                                 [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_yPfHtJ --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_97qcm5 > /dev/null
Executing: mysql --defaults-extra-file=/tmp/drush_G5zBK1 --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_kxY7Bn
Executing: mysql --defaults-extra-file=/tmp/drush_o6Lv3j --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_M6i2TF
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                                                     [ok]
exception 'Drupal\Core\Config\UnmetDependenciesException' with message 'Configuration objects provided by <em class="placeholder">lightning_workflow</em> have unmet dependencies: <em           [error]
class="placeholder">views.view.moderation_history (views)</em>' in /var/www/xxx/docroot/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:98
Stack trace:
#0 /var/www/xxx/docroot/core/lib/Drupal/Core/Config/ConfigInstaller.php(480): Drupal\Core\xxx\UnmetDependenciesException::create('lightning_workf...', Array)
#1 /var/www/xxx/docroot/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132): Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'lightning_workf...')
```

And I expected this to happen:

Successful site install, i am getting the same results in our travis build and it is blocking update to Drupal 8.4.4

**Comment by grasmash** [comment]
This error indicates that your exported configuration is invalid. It is a bug in your application, and is unrelated to BLT.

The error is being raised by drush during execution of `drush si`. You need to resolve the unmet dependency in your configuration.

**Comment by energee** [comment]
This is on a fresh install

**Comment by grasmash** [comment]
So `config/default` is completely empty?

**Comment by energee** [comment]
Yes
```../config/default$ ls
README.md```

**Comment by energee** [comment]
It seems like this is an issue with the way composer is installing dependencies because when I remove lightning and blt from composer and walk through the update in a certain order (I haven't determined what that order is as of yet), I am able execute a successful install. However, that final saved version of the composer.json/lock will ultimately fail when installed on the docker environment via travis.
