### ISSUE TITLE
New project install failing due to existing config

### ISSUE THREAD

**Issue by dwhoban** [acquia/blt#2520]
My system information:
* Operating system type: MacOS
* Operating system version: 10.13.3
* BLT version: 9.0.0-beta2 

Output of `blt doctor`:
```
Drupal VM was detected. Running blt doctor inside of VM...
Executing command cd /var/www/gc2018/docroot/.. && ./vendor/bin/blt doctor inside of Drupal VM...
[error]  Could not find VM. Please ensure that the VM machine name matches project.machine_name 
+---------------------------+-------------------------------------------------------+
| Property                  | Value                                                 |
+---------------------------+-------------------------------------------------------+
| %paths.%root              | /var/www/gc2018/docroot                               |
| %paths.%site              | sites/default                                         |
| %paths.%modules           | sites/all/modules                                     |
| %paths.%themes            | sites/all/themes                                      |
| %paths.%config-sync       | /var/www/gc2018/config/default                        |
| %paths.%files             | sites/default/files                                   |
| %paths.%temp              | /tmp                                                  |
| %paths.%private           | /var/www/gc2018/files-private                         |
| admin-theme               | seven                                                 |
| alias-searchpaths.0       | /var/www/gc2018/drush/sites                           |
| blt-version               | 9.0.0-beta2                                           |
| bootstrap                 | Successful                                            |
| composer-version          | Composer version 1.6.2 2018-01-05 15:28:41            |
| config-sync               | /var/www/gc2018/config/default                        |
| db-driver                 | mysql                                                 |
| db-hostname               | localhost                                             |
| db-name                   | drupal                                                |
| db-password               | drupal                                                |
| db-port                   | 3306                                                  |
| db-status                 | Connected                                             |
| db-username               | drupal                                                |
| drupal-settings-file      | sites/default/settings.php                            |
| drupal-version            | 8.4.4                                                 |
| drush-alias-files.0       | /var/www/gc2018/drush/sites/gc2018.site.yml           |
| drush-conf.0              | /var/www/gc2018/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/gc2018/drush/drush.yml                       |
| drush-conf.2              | /var/www/gc2018/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/gc2018/vendor/bin/drush                      |
| drush-temp                | /tmp                                                  |
| drush-version             | 9.0.0                                                 |
| files                     | sites/default/files                                   |
| install-profile           | lightning                                             |
| modules                   | sites/all/modules                                     |
| php-bin                   | /usr/bin/php7.1                                       |
| php-conf.0                | /etc/php/7.1/cli/php.ini                              |
| php-os                    | Linux                                                 |
| private                   | /var/www/gc2018/files-private                         |
| root                      | /var/www/gc2018/docroot                               |
| site                      | sites/default                                         |
| stacks.drupal-vm.inited   | false                                                 |
| stacks.dev-desktop.inited | false                                                 |
| temp                      | /tmp                                                  |
| theme                     | stark                                                 |
| themes                    | sites/all/themes                                      |
| uri                       | http://local.blted8.com                               |
+---------------------------+-------------------------------------------------------+
+--------------------------------------+--------------------------------------------------------------+
| Check                                | Problem                                                      |
+--------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri          | base_url in tests/behat/local.yml does not match the site    |
|                                      | URI.                                                         |
|                                      |   Behat base_url is set to                                   |
|                                      | http://local.gc2018.com.                                     |
|                                      |   Drush site URI is set to                                   |
|                                      | http://local.blted8.com.                                     |
| ConfigCheck:checkGitConfig           | Git repositories are not defined in blt.yml.                 |
|                                      |   Add values for git.remotes to blt.yml to enabled automated |
|                                      | deployment.                                                  |
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root.    |
| WebUriCheck:checkUriResponse         | Did not get a response from http://local.blted8.com          |
|                                      | Is your *AMP stack running?                                  |
|                                      | Is your web server configured to serve this URI from         |
|                                      | /var/www/gc2018/docroot?                                     |
|                                      | Is options.uri set correctly in                              |
|                                      | /var/www/gc2018/docroot/sites/default/local.drush.yml?       |
+--------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues. 
Connection to 127.0.0.1 closed.
+---------------------------+------------------------------------+
| Property                  | Value                              |
+---------------------------+------------------------------------+
| blt-version               | 9.0.0-beta2                        |
| composer-version          | Composer version 1.6.3 2018-01-31  |
|                           | 16:28:17                           |
| root                      | /Users/dan/Projects/gc2018/docroot |
| stacks.drupal-vm.inited   | true                               |
| stacks.dev-desktop.inited | false                              |
| uri                       | default                            |
+---------------------------+------------------------------------+
+------------------------------------------+--------------------------------------------------------------+
| Check                                    | Problem                                                      |
+------------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri              | base_url in tests/behat/local.yml does not match the site    |
|                                          | URI.                                                         |
|                                          |   Behat base_url is set to                                   |
|                                          | http://local.gc2018.com.                                     |
|                                          |   Drush site URI is set to default.                          |
| ConfigCheck:checkGitConfig               | Git repositories are not defined in blt.yml.                 |
|                                          |   Add values for git.remotes to blt.yml to enabled automated |
|                                          | deployment.                                                  |
| DbCheck:checkRequiredKeys                | drush status is missing the 'db-hostname' key.               |
| DrupalCheck:checkDrupalBootstrapped      | Could not bootstrap Drupal via drush without alias.          |
| DrupalCheck:checkDrupalInstalled         | Drupal is not installed.                                     |
|                                          |                                                              |
|                                          | Run `blt drupal:install` to install Drupal locally.          |
| DrupalVmCheck:checkDrupalVm:alias        | The drush alias assigned to drush.aliases.local does not     |
|                                          | exist in your drush aliases file.                            |
|                                          |   drush.aliases.local is set to @@gc2018.local               |
| FileSystemCheck:checkFileSystem:%files   | Public files directory is not set.                           |
| FileSystemCheck:checkFileSystem:%private | Private files directory is not set.                          |
| FileSystemCheck:checkFileSystem:%temp    | Temporary files directory is not set.                        |
| NodeCheck:checkNodeVersionFileExists     | Neither .nvmrc nor .node-version file found in repo root.    |
| PhpCheck:checkPhpDateTimezone            | PHP setting for date.timezone is not set.                    |
|                                          |   Define date.timezone in                                    |
| WebUriCheck:checkUri                     | Site URI is not set                                          |
|                                          | Is options.uri set correctly in                              |
|                                          | /Users/dan/Projects/gc2018/docroot/sites/default/local.drush |
|                                          | .yml?                                                        |
+------------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues. 
```

When I run this command:
```
composer create-project acquia/blt-project:9.x-dev --no-interaction gc2018  
blt vm
blt setup
```

I get the following output:
```
$ blt setup                                                                                                                                                                                   11 changed files  master 
Setting up local environment for site default.
Using drush alias @gc2018.local
> source:build
> tests:behat:init:config
Executing command blt 'tests:behat:init:config' --define=drush.alias=self inside of Drupal VM...
Connection to 127.0.0.1 closed.
> source:build:composer
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> blt:init:git-hooks
Installing pre-commit git hook...
Installing commit-msg git hook...
> blt:init:settings
> source:build:frontend
Executing command blt 'source:build:frontend' --define=drush.alias=self inside of Drupal VM...
> source:build:frontend-reqs
> source:build:frontend-assets
Connection to 127.0.0.1 closed.
> drupal:hash-salt:init
Hash salt already exists.
> drupal:install
Executing command blt 'drupal:install' --define=drush.alias=self inside of Drupal VM...
> internal:drupal:install
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/gc2018/vendor/bin/drush @self site-install lightning install_configure_form.update_status_module='array(FALSE,FALSE)' install_configure_form.enable_update_status_module=NULL --sites-subdir=default --site-name='BLTed 8' --site-mail=no-reply@acquia.com --account-name=AvJg6rSWj9 --account-mail=no-reply@acquia.com --locale=en --verbose --ansi in /var/www/gc2018/docroot
 [info] Executing: mysql --defaults-file=/tmp/drush_muDmEL --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_FGM2hB > /dev/null

 You are about to DROP all tables in your 'drupal' database. Do you want to continue? (yes/no) [yes]:
 > yes

 [info] Sites directory sites/default already exists - proceeding.
 [info] Executing: mysql --defaults-file=/tmp/drush_KngqwE --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_ya6m5H > /dev/null
 [info] Executing: mysql --defaults-file=/tmp/drush_v2G0rx --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_PvscZA
 [notice] Starting Drupal installation. This takes a while. Consider using the --notify global option.
 [error]  Configuration objects (core.entity_form_display.media.image.default, core.entity_view_display.media.image.default, media.type.image) provided by lightning_media_image already exist in active configuration 
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 04:24
[error]  Failed to install Drupal! 
[error]  Command `internal:drupal:install ` exited with code 1. 
Connection to 127.0.0.1 closed.
[error]  Executing command inside VM failed! 
```

And I expected this to happen:
I expect Drupal to install. 

This was a clean install for a new project with no existing configuration.  Only small tweaks to match names correctly.

**Comment by dwhoban** [comment]
Also happens on BLT version: [replace]

Output of `blt doctor`:
```
Drupal VM was detected. Running blt doctor inside of VM...
Executing command cd /var/www/gc2018/docroot/.. && /var/www/gc2018/docroot/../vendor/bin/drush cc drush && /var/www/gc2018/docroot/../vendor/bin/drush --include=/var/www/gc2018/docroot/../vendor/acquia/blt/drush blt-doctor -r /var/www/gc2018/docroot/../docroot inside of Drupal VM...
'drush' cache was cleared.                                                                                                                                                                                                 [success]
+----------------------+---------------------------------------------------------------------------------+
| Property             | Value                                                                           |
+----------------------+---------------------------------------------------------------------------------+
| %paths               |                                                                                 |
|  - %root             | /var/www/gc2018/docroot                                                         |
|  - %site             | sites/default                                                                   |
|  - %modules          | modules                                                                         |
|  - %themes           | themes                                                                          |
|  - %config-sync      | /var/www/gc2018/config/default                                                  |
|  - %files            | sites/default/files                                                             |
|  - %private          | /var/www/gc2018/files-private                                                   |
|  - %temp             | /tmp                                                                            |
| admin-theme          | seven                                                                           |
| blt-version          | 8.9.12                                                                          |
| bootstrap            | Successful                                                                      |
| config-sync          | /var/www/gc2018/config/default                                                  |
| db-driver            | mysql                                                                           |
| db-hostname          | localhost                                                                       |
| db-name              | drupal                                                                          |
| db-password          | drupal                                                                          |
| db-port              | 3306                                                                            |
| db-status            | Connected                                                                       |
| db-username          | drupal                                                                          |
| dev-desktop-enabled  | false                                                                           |
| drupal-settings-file | sites/default/settings.php                                                      |
| drupal-version       | 8.4.4                                                                           |
| drupal-vm-enabled    | true                                                                            |
| drush-alias-files    | /var/www/gc2018/docroot/../drush/site-aliases/example.local.aliases.drushrc.php |
|                      | /var/www/gc2018/docroot/../drush/site-aliases/aliases.drushrc.php               |
|                      | /var/www/gc2018/docroot/../drush/site-aliases/example.acsf.aliases.drushrc.php  |
| drush-conf           | /var/www/gc2018/drush/drushrc.php                                               |
| drush-script         | /var/www/gc2018/vendor/drush/drush/drush.php                                    |
| drush-temp           | /tmp                                                                            |
| drush-version        | 8.1.15                                                                          |
| files                | sites/default/files                                                             |
| install-profile      | lightning                                                                       |
| local-drushrc        | /var/www/gc2018/docroot/sites/default/local.drushrc.php                         |
| local-settings       | /var/www/gc2018/docroot/sites/default/settings/local.settings.php               |
| modules              | modules                                                                         |
| php-bin              | /usr/bin/php                                                                    |
| php-conf             | /etc/php/7.1/cli/php.ini                                                        |
| php-mysql            | /var/run/mysqld/mysqld.sock                                                     |
| php-os               | Linux                                                                           |
| private              | /var/www/gc2018/files-private                                                   |
| root                 | /var/www/gc2018/docroot                                                         |
| shell                |                                                                                 |
| site                 | sites/default                                                                   |
| temp                 | /tmp                                                                            |
| theme                | stark                                                                           |
| themes               | themes                                                                          |
| uri                  | http://local.gc2018.com                                                         |
| user                 |                                                                                 |
+----------------------+---------------------------------------------------------------------------------+
+--------------------------+--------------------------------------------------------+
| Check                    | Outcome                                                |
+--------------------------+--------------------------------------------------------+
| checkDocrootExists       | Found docroot.                                         |
| checkCoreExists          | Drupal core exists                                     |
| checkSettingsFile        | BLT settings are included in settings file.            |
| checkLocalSettingsFile   | Found your local settings file.                        |
| checkLocalDrushFile      | Found your local drush settings file.                  |
| checkUri                 | $options['uri'] is set.                                |
| checkUriResponse         | Received a response from site http://local.gc2018.com. |
| checkFileSystem:%files   | Public files directory is writable.                    |
| checkFileSystem:%private | Private files directory is writable.                   |
| checkFileSystem:%temp    | Temporary files directory is writable.                 |
| checkDbConnection        | Connected to database.                                 |
| checkDrupalBootstrapped  | Bootstrapped Drupal via drush.                         |
| checkDrupalInstalled     | Drupal is installed.                                   |
| checkCaching:page        | Drupal cache is disabled.                              |
| checkCaching:css         | CSS preprocessing is disabled.                         |
| checkCaching:js          | JS preprocessing is disabled.                          |
| checkComposer:require    | acquia/blt is in composer.json's require object.       |
| checkBehat:exists        | Behat local settings file exists.                      |
| checkBehat:root          | Behat drupal_root is set correctly for Drupal VM.      |
| checkProjectYml:keys     | project.yml has no deprecated keys.                    |
| checkDrupalVm:alias      | drush.aliases.local exists your drush aliases file.    |
| checkDrupalVm            | Drupal VM is configured correctly.                     |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set         |
+--------------------------+--------------------------------------------------------+
Connection to 127.0.0.1 closed.
```

When I run this command:
```
composer create-project acquia/blt-project --no-interaction gc2018
blt vm
blt setup
```

I get the following output:
```
Setting up local environment for site 'default' using drush alias @gc2018.local
> setup:build
> setup:behat
Executing command blt 'setup:behat' --define=drush.alias=self inside of Drupal VM...
[warning] The xDebug extension is loaded. This will significantly decrease performance.
Generating Behat configuration files...
Connection to 127.0.0.1 closed.
> setup:composer:install
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> setup:git-hooks
Installing pre-commit git hook...
Installing commit-msg git hook...
> setup:settings
> frontend
Executing command blt frontend --define=drush.alias=self inside of Drupal VM...
[warning] The xDebug extension is loaded. This will significantly decrease performance.
> frontend:setup
> frontend:build
Connection to 127.0.0.1 closed.
> setup:hash-salt
Generating hash salt...
[File\Write] Writing to /Users/dan/Projects/gc2018/salt.txt.
> setup:drupal:install
Executing command blt 'setup:drupal:install' --define=drush.alias=self inside of Drupal VM...
[warning] The xDebug extension is loaded. This will significantly decrease performance.
> internal:drupal:install
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/gc2018/vendor/bin/drush site-install lightning install_configure_form.update_status_module='array(FALSE,FALSE)' install_configure_form.enable_update_status_module=NULL --site-name=GC2018 --site-mail=no-reply@acquia.com --account-name=7VtwTOhg5G --account-mail=no-reply@acquia.com --locale=en --config-dir=../config/default --uri=default --yes --verbose in /var/www/gc2018/docroot
Configuration import directory ../config/default does not contain any configuration; will skip import.                                                                                                                     [warning]
Executing: mysql --defaults-extra-file=/tmp/drush_EuoFz5 --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_YazjZa > /dev/null
You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
Sites directory /var/www/gc2018/docroot/sites/default already exists - proceeding.                                                                                                                                            [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_3OgqOU --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_gGLZb0 > /dev/null
Executing: mysql --defaults-extra-file=/tmp/drush_tcCJ6J --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_1wjysP
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                                                                               [ok]

Drupal\Core\Config\PreExistingConfigException: Configuration objects (core.entity_form_display.media.image.default, core.entity_view_display.media.image.default, media.type.image) provided by lightning_media_image      [error]
already exist in active configuration in /var/www/gc2018/docroot/core/lib/Drupal/Core/Config/PreExistingConfigException.php:65
Stack trace:
#0 /var/www/gc2018/docroot/core/lib/Drupal/Core/Config/ConfigInstaller.php(492): Drupal\Core\Config\PreExistingConfigException::create('lightning_media...', Array)
#1 /var/www/gc2018/docroot/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132): Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'lightning_media...')
#2 /var/www/gc2018/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(145): Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'lightning_media...')
#3 /var/www/gc2018/docroot/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#4 /var/www/gc2018/docroot/core/includes/install.core.inc(1813): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, false)
#5 /var/www/gc2018/docroot/core/includes/batch.inc(294): _install_module_batch('lightning_media...', 'Media Image', Array)
#6 /var/www/gc2018/docroot/core/includes/form.inc(875): _batch_process()
#7 /var/www/gc2018/docroot/core/includes/install.core.inc(634): batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#8 /var/www/gc2018/docroot/core/includes/install.core.inc(555): install_run_task(Array, Array)
#9 /var/www/gc2018/docroot/core/includes/install.core.inc(117): install_run_tasks(Array)
#10 /var/www/gc2018/vendor/drush/drush/includes/drush.inc(726): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#11 /var/www/gc2018/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)
#12 /var/www/gc2018/vendor/drush/drush/commands/core/drupal/site_install.inc(82): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#13 /var/www/gc2018/vendor/drush/drush/commands/core/site_install.drush.inc(255): drush_core_site_install_version('lightning', Array)
#14 /var/www/gc2018/vendor/drush/drush/includes/command.inc(422): drush_core_site_install('lightning', 'install_configu...', 'install_configu...')
#15 /var/www/gc2018/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#16 /var/www/gc2018/vendor/drush/drush/includes/command.inc(199): drush_command('lightning', 'install_configu...', 'install_configu...')
#17 /var/www/gc2018/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#18 /var/www/gc2018/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#19 /var/www/gc2018/vendor/drush/drush/drush.php(12): drush_main()
#20 {main}
Command dispatch complete                                                                                                                                                                                                     [notice]
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 01:11
[error]  Failed to install Drupal! 
[error]  Command `internal:drupal:install ` exited with code 1. 
Connection to 127.0.0.1 closed.
> setup:toggle-modules
Executing command blt 'setup:toggle-modules' --define=drush.alias=self inside of Drupal VM...
[warning] The xDebug extension is loaded. This will significantly decrease performance.
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/gc2018/vendor/bin/drush pm-enable dblog devel seckit views_ui --uri=default --yes in /var/www/gc2018/docroot
dblog is already enabled.                                                                                                                                                                                                  [ok]
views_ui is already enabled.                                                                                                                                                                                               [ok]
The following extensions will be enabled: devel, seckit
Do you really want to continue? (y/n): y
devel was enabled successfully.                                                                                                                                                                                            [ok]
devel defines the following permissions: access devel information, execute php code, switch users
seckit was enabled successfully.                                                                                                                                                                                           [ok]
seckit defines the following permissions: administer seckit
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 22.035s
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/gc2018/vendor/bin/drush pm-uninstall acsf acquia_connector shield --uri=default --yes in /var/www/gc2018/docroot
Extension acsf was not found and will not be uninstalled.                                                                                                                                                                  [warning]
acquia_connector is already uninstalled.                                                                                                                                                                                   [ok]
shield is already uninstalled.                                                                                                                                                                                             [ok]
There were no extensions that could be uninstalled.                                                                                                                                                                        [ok]
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 10.228s
Connection to 127.0.0.1 closed.
> install-alias
The BLT alias is already installed and up to date.
```

And I expected this to happen:
Complete first setup of Drupal

**Comment by grasmash** [comment]
When I run:

```
composer create-project acquia/blt-project --no-interaction gc2018
cd gc2018
```

Add to composer.json:
```
    "config": {
        "platform": {
            "php": "5.6"
        }
    },
```

Run
```
blt vm
blt setup
```

I get no failure. You can see that I did need to explicitly install PHP 5.6 compatible composer deps since my host is running PHP 7.1 but my VM was running 5.6. 

Are you sure you don't have any config files in `config/default`?|

**Comment by dwhoban** [comment]
Yeah hadn’t touched the configs.  Like I said, clean install, the error happened on first run of blt setup.

I had changed the config of the box to run 7.1 on the v8 install and used the default 7.1 for the v9 install.

**Comment by grasmash** [comment]
Even though you haven't touched the configs, can you verify that the `config/default` dir is empty?

**Comment by grasmash** [comment]
Ah, I think I know your issue: 
https://docs.acquia.com/article/fixing-failing-composer-patches-updating-gnu-patch

**Comment by theneonlobster** [comment]
Beat me to it, @grasmash. 

To fix the issue in existing projects, install gpatch and see https://github.com/acquia/blt/issues/2251#issuecomment-342922657
