### ISSUE TITLE
BLT commands not working outside VM

### ISSUE THREAD

**Issue by arunavak111** [acquia/blt#2525]
My system information:
* Operating system type: Windows
* Operating system version: 10
* BLT version: 

I'm following this doc:
https://blt.readthedocs.io/en/latest/readme/onboarding/

```
PS C:\wamp\www\myproject-dev> composer run-script blt-alias
> blt install-alias -y --ansi

Notice: Undefined index: PWD in C:\wamp\www\myproject-dev\vendor\acquia\blt\bin\blt-robo.php on line 23

Call Stack:
    0.0012     123920   1. {main}() C:\wamp\www\myproject-dev\vendor\acquia\blt\bin\blt:0
    0.0196     132832   2. require_once('C:\wamp\www\myproject-dev\vendor\acquia\blt\bin\blt-robo.php') C:\wamp\www\myproject-dev\vendor\acquia\blt\bin\blt:11
    0.0208     132856   3. find_repo_root() C:\wamp\www\myproject-dev\vendor\acquia\blt\bin\blt-robo.php:7


Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in C:\wamp\www\myproject-dev\vendor\acquia\blt\src\Robo\Inspector\Inspector.p
hp on line 19

Call Stack:
    0.0012     123920   1. {main}() C:\wamp\www\myproject-dev\vendor\acquia\blt\bin\blt:0
    0.0196     132832   2. require_once('C:\wamp\www\myproject-dev\vendor\acquia\blt\bin\blt-robo.php') C:\wamp\www\myproject-dev\vendor\acquia\blt\bin\blt:11
    0.9064    1083592   3. require_once('C:\wamp\www\myproject-dev\vendor\acquia\blt\bin\blt-robo-run.php') C:\wamp\www\myproject-dev\vendor\acquia\blt\bin\blt-robo.php:14
   20.9867    2344344   4. Acquia\Blt\Robo\Blt->__construct() C:\wamp\www\myproject-dev\vendor\acquia\blt\bin\blt-robo-run.php:41
   24.1398    4142800   5. Acquia\Blt\Robo\Blt->configureContainer() C:\wamp\www\myproject-dev\vendor\acquia\blt\src\Robo\Blt.php:78
   25.3866    4495216   6. League\Container\Container->share() C:\wamp\www\myproject-dev\vendor\acquia\blt\src\Robo\Blt.php:191
   25.3876    4495248   7. League\Container\Container->add() C:\wamp\www\myproject-dev\vendor\league\container\src\Container.php:163
   25.3889    4495248   8. League\Container\Definition\DefinitionFactory->getDefinition() C:\wamp\www\myproject-dev\vendor\league\container\src\Container.php:142
   25.3918    4495280   9. class_exists() C:\wamp\www\myproject-dev\vendor\league\container\src\Definition\DefinitionFactory.php:20
   25.3925    4495536  10. spl_autoload_call() C:\wamp\www\myproject-dev\vendor\league\container\src\Definition\DefinitionFactory.php:20
   25.3932    4495584  11. Composer\Autoload\ClassLoader->loadClass() C:\wamp\www\myproject-dev\vendor\league\container\src\Definition\DefinitionFactory.php:0
   25.4171    4495704  12. Composer\Autoload\includeFile() C:\wamp\www\myproject-dev\vendor\composer\ClassLoader.php:322

Script blt install-alias -y --ansi handling the blt-alias event returned with error code 255
```

BLT Info:

```
PS C:\wamp\www\myproject-dev> composer info acquia/blt
name     : acquia/blt
descrip. : BLT
keywords : automation, deployment, drupal, template, testing
versions : * 8.9.12
type     : composer-plugin
license  : GNU General Public License v2.0 only (GPL-2.0) (OSI approved) https://spdx.org/licenses/GPL-2.0.html#licenseText
source   : [git] https://github.com/acquia/blt.git 34ed984fdd0304e9209de0bcfc7b90bfddee6d4e
dist     : [zip] https://api.github.com/repos/acquia/blt/zipball/34ed984fdd0304e9209de0bcfc7b90bfddee6d4e 34ed984fdd0304e9209de0bcfc7b90bfddee6d4e
names    : acquia/blt

autoload
psr-4
Acquia\Blt\ => src/
Acquia\Blt\Tests\ => tests/phpunit/src/
Acquia\Blt\Tests\Robo\ => tests/phpunit/Robo/

requires
asm89/twig-lint ^1.0.2
composer-plugin-api ^1.0.0
composer/installers ^1.2.0
composer/semver ^1.4
consolidation/config ^1.0.0
consolidation/robo ^1.1.0
cweagans/composer-patches ^1.6.4
dealerdirect/phpcodesniffer-composer-installer ^0.4.0
dflydev/dot-access-data ^1.1.0
doctrine/common ^2.5
doctrine/inflector ~1.1.0
drupal/coder ^8.2.11
drush/drush ^8.1.15
grasmash/drupal-security-warning ^1.0.0
grasmash/yaml-cli ^1.0.0
grasmash/yaml-expander ^1.0.5
oomphinc/composer-installers-extender ^1.1
php >=5.6
phpunit/phpunit ^4.8
squizlabs/php_codesniffer ^2.7
symfony/console ^2.7|~3.2.8
symfony/yaml ^2.7|~3.2.8
tivie/php-os-detector ^1.0
wikimedia/composer-merge-plugin ^1.4.1

requires (dev)
guzzlehttp/guzzle ^6.2

suggests
hirak/prestissimo ^0.3
typhonius/acquia_cli ^0.0.7

conflicts
drupal/core 7.*
```

**Comment by arunavak111** [comment]
I think above error was due to older php version. I have updated php in to latest php 7. And now it throwing different error:

```
PS C:\wamp\www\myproject-dev> composer run-script blt-alias
You are running Composer with SSL/TLS protection disabled.
> blt install-alias -y --ansi

Fatal error: Uncaught Error: Call to undefined function Acquia\Blt\Robo\Inspector\posix_getpwuid() in C:\wamp\www\myproject-dev\vendor\acquia\blt\src\Robo\Inspector\Inspector.php:442
Stack trace:
#0 C:\wamp\www\myproject-dev\vendor\acquia\blt\src\Robo\Inspector\Inspector.php(423): Acquia\Blt\Robo\Inspector\Inspector->getCliConfigFile()
#1 C:\wamp\www\myproject-dev\vendor\acquia\blt\src\Robo\Commands\Blt\AliasCommand.php(20): Acquia\Blt\Robo\Inspector\Inspector->isBltAliasInstalled()
#2 [internal function]: Acquia\Blt\Robo\Commands\Blt\AliasCommand->installBltAlias(Array)
#3 C:\wamp\www\myproject-dev\vendor\consolidation\annotated-command\src\CommandProcessor.php(235): call_user_func_array(Array, Array)
#4 C:\wamp\www\myproject-dev\vendor\consolidation\annotated-command\src\CommandProcessor.php(181): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\
AnnotatedCommand\CommandData))
#5 C:\wamp\www\myproject-dev\vendor\consolidation\annotated-command\src\CommandProcessor.php(150): Consolidation\Anno in C:\wamp\www\myproject-dev\vendor\acquia\blt\src\Robo\Inspector\Inspector.php
on line 442
Script blt install-alias -y --ansi handling the blt-alias event returned with error code 255
```

**Comment by grasmash** [comment]
BLT only supports Windows when using an Ubuntu Bash prompt. Otherwise you will need to use a VM. You cannot use BLT on a normal Windows prompt.

http://blt.readthedocs.io/en/8.x/readme/windows-install/
