### ISSUE TITLE
Undefined function posix_getpwuid() in composer in Windows

### ISSUE THREAD

**Issue by arunavak111** [acquia/blt#2526]
My system information:
* Operating system type: Windows
* Operating system version: 10
* BLT version: 8.9.11

Output of `blt doctor`:
```
$ blt doctor
The system cannot find the path specified.
[warning] Drupal VM is locally initialized, but is not running.
The system cannot find the path specified.
Attempting to run doctor on host machine...
[warning] Unable to run the doctor using alias '@myproject.local'. Trying with '@self'...
[warning] Unable to run the doctor using alias '@self'. Trying without alias...
[error]  Unable to execute the `blt doctor` command.

```

When I run this command:
```
composer run-script blt-alias
```

I get the following output:
```
$ composer run-script blt-alias
> blt install-alias -y --ansi
The system cannot find the path specified.
[warning] Drupal VM is locally initialized, but is not running.

Fatal error: Uncaught Error: Call to undefined function Acquia\Blt\Robo\Inspector\posix_getpwuid() in C:\wamp\www\myproject\vendor\acquia\blt\src\Robo\Inspector\Inspector.php:442
Stack trace:
#0 C:\wamp\www\myproject\vendor\acquia\blt\src\Robo\Inspector\Inspector.php(423): Acquia\Blt\Robo\Inspector\Inspector->getCliConfigFile()
#1 C:\wamp\www\myproject\vendor\acquia\blt\src\Robo\Commands\Blt\AliasCommand.php(20): Acquia\Blt\Robo\Inspector\Inspector->isBltAliasInstalled()
#2 [internal function]: Acquia\Blt\Robo\Commands\Blt\AliasCommand->installBltAlias(Array)
#3 C:\wamp\www\myproject\vendor\consolidation\annotated-command\src\CommandProcessor.php(235): call_user_func_array(Array, Array)
#4 C:\wamp\www\myproject\vendor\consolidation\annotated-command\src\CommandProcessor.php(181): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 C:\wamp\www\myproject\vendor\consolidation\annotated-command\src\CommandProcessor.php(150): Consolidation\Anno in C:\wamp\www\myproject\vendor\acquia\blt\src\Robo\Inspector\Inspector.php on line 442
Script blt install-alias -y --ansi handling the blt-alias event returned with error code 255


```

**Comment by grasmash** [comment]
BLT only supports Windows when using an Ubuntu Bash prompt. Otherwise you will need to use a VM. You cannot use BLT on a normal Windows prompt.

http://blt.readthedocs.io/en/8.x/readme/windows-install/

**Comment by arunavak111** [comment]
I'm using PowerShell and have installed Vagrant and Virtual box in my machine and vagrant up command executed successfully and I'm able to see my websites Drupal VM dashboard.

**Comment by grasmash** [comment]
In that case, you need to run the BLT command in the VM and not on a Windows prompt.

**Comment by arunavak111** [comment]
Thanks grasmash. Its working. Perfect. Thanks. :)
