### ISSUE TITLE
Empty screenshots taken during behat testing

### ISSUE THREAD

**Issue by timwood** [acquia/blt#2648]
My system information:
* Operating system type: Mac
* Operating system version: Sierra
* BLT version: 8.9.14 and 9.0.4

Output of `blt doctor`:
```
+---------------------------+---------------------------------------------------------+
| Property                  | Value                                                   |
+---------------------------+---------------------------------------------------------+
| %paths.%root              | /var/www/mfgov-d8/docroot                               |
| %paths.%site              | sites/default                                           |
| %paths.%modules           | sites/all/modules                                       |
| %paths.%themes            | sites/all/themes                                        |
| %paths.%config-sync       | /var/www/mfgov-d8/config/default                        |
| %paths.%files             | sites/default/files                                     |
| %paths.%temp              | /tmp                                                    |
| %paths.%private           | /var/www/mfgov-d8/files-private                         |
| admin-theme               | seven                                                   |
| alias-searchpaths.0       | /var/www/mfgov-d8/drush/sites                           |
| blt-version               | 9.0.4                                                   |
| bootstrap                 | Successful                                              |
| composer-version          |                                                         |
| config-sync               | /var/www/mfgov-d8/config/default                        |
| db-driver                 | mysql                                                   |
| db-hostname               | localhost                                               |
| db-name                   | drupal                                                  |
| db-password               | drupal                                                  |
| db-port                   | 3306                                                    |
| db-status                 | Connected                                               |
| db-username               | drupal                                                  |
| drupal-settings-file      | sites/default/settings.php                              |
| drupal-version            | 8.5.0                                                   |
| drush-alias-files.0       | /var/www/mfgov-d8/drush/sites/mfgov.site.yml            |
| drush-conf.0              | /var/www/mfgov-d8/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/mfgov-d8/drush/drush.yml                       |
| drush-conf.2              | /var/www/mfgov-d8/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/mfgov-d8/vendor/bin/drush                      |
| drush-temp                | /tmp                                                    |
| drush-version             | 9.2.1                                                   |
| files                     | sites/default/files                                     |
| install-profile           | lightning                                               |
| modules                   | sites/all/modules                                       |
| php-bin                   | /usr/bin/php7.1                                         |
| php-conf.0                | /etc/php/7.1/cli/php.ini                                |
| php-os                    | Linux                                                   |
| private                   | /var/www/mfgov-d8/files-private                         |
| root                      | /var/www/mfgov-d8/docroot                               |
| site                      | sites/default                                           |
| stacks.drupal-vm.inited   | true                                                    |
| stacks.dev-desktop.inited | false                                                   |
| temp                      | /tmp                                                    |
| theme                     | uswds_mfgov                                             |
| themes                    | sites/all/themes                                        |
| uri                       | https://local.manufacturing.test                        |
+---------------------------+---------------------------------------------------------+
+--------------------------------------+-----------------------------------------------------------+
| Check                                | Problem                                                   |
+--------------------------------------+-----------------------------------------------------------+
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root. |
| WebUriCheck:checkHttps               | The SSL certificate for your local site appears to be     |
|                                      | invalid for https://local.manufacturing.test.             |
+--------------------------------------+-----------------------------------------------------------+
```

When I run this command:
```
blt tests:behat:run -vvv
```

I get the following output and empty screenshots:
```
[debug] Verifying that MySQL is available...
[Robo\Common\ProcessExecutor] Running '/var/www/mfgov-d8/vendor/bin/drush' @self sqlq "SHOW DATABASES" in /var/www/mfgov-d8/docroot
information_schema
drupal
[debug] Verifying that Drupal is installed...
[Robo\Common\ProcessExecutor] Running '/var/www/mfgov-d8/vendor/bin/drush' @self sqlq "SHOW TABLES LIKE 'config'" in /var/www/mfgov-d8/docroot
config
[debug] Verifying that Drupal is installed...
[Robo\Common\ProcessExecutor] Running '/var/www/mfgov-d8/vendor/bin/drush' @self sqlq "SHOW TABLES LIKE 'config'" in /var/www/mfgov-d8/docroot
config
Configuration for behat:
+---------------------+-------------------------------------------+
| Property            | Value                                     |
+---------------------+-------------------------------------------+
| behat.config        | /var/www/mfgov-d8/tests/behat/local.yml   |
| behat.profile       | local                                     |
| behat.selenium.port | 4444                                      |
| behat.selenium.url  | http://127.0.0.1:4444/wd/hub              |
| behat.chrome.port   | 9222                                      |
| behat.chrome.args   |                                           |
| behat.paths.0       | /var/www/mfgov-d8/tests/behat             |
| behat.tags          | ~ajax&&~experimental&&~lightningextension |
| behat.extra         |                                           |
| behat.web-driver    | chrome                                    |
+---------------------+-------------------------------------------+
+-----------------------------------------------------------------------------------------------------+--------------------------------------------------+
| Property                                                                                            | Value                                            |
+-----------------------------------------------------------------------------------------------------+--------------------------------------------------+
| imports.0                                                                                           | behat.yml                                        |
| local.suites.default.paths.features                                                                 | /var/www/mfgov-d8                                |
| local.suites.default.paths.bootstrap                                                                | /var/www/mfgov-d8/tests/behat/features/bootstrap |
| local.suites.default.contexts.0.Drupal\FeatureContext                                               |                                                  |
| local.suites.default.contexts.0.parameters.environment.screenshot_dir                               | /var/www/mfgov-d8/reports                        |
| local.suites.default.contexts.1                                                                     | Drupal\DrupalExtension\Context\DrupalContext     |
| local.suites.default.contexts.2                                                                     | Drupal\DrupalExtension\Context\MinkContext       |
| local.suites.default.contexts.3                                                                     | Drupal\DrupalExtension\Context\MessageContext    |
| local.suites.default.contexts.4                                                                     | Drupal\DrupalExtension\Context\DrushContext      |
| local.extensions.DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension                       |                                                  |
| local.extensions.Behat\MinkExtension.browser_name                                                   | chrome                                           |
| local.extensions.Behat\MinkExtension.javascript_session                                             | default                                          |
| local.extensions.Behat\MinkExtension.base_url                                                       | https://local.manufacturing.test                 |
| local.extensions.Behat\MinkExtension.show_cmd                                                       | open %s                                          |
| local.extensions.Behat\MinkExtension.selenium2.wd_host                                              | http://127.0.0.1:4444/wd/hub                     |
| local.extensions.Behat\MinkExtension.selenium2.browser                                              | chrome                                           |
| local.extensions.Behat\MinkExtension.sessions.default.chrome.api_url                                | http://localhost:9222                            |
| local.extensions.Drupal\DrupalExtension.drupal.drupal_root                                          | /var/www/mfgov-d8/docroot                        |
| local.extensions.Drupal\DrupalExtension.drush.alias                                                 | @self                                            |
| default.suites.default.paths.0                                                                      | %paths.base%/features                            |
| default.extensions.Behat\MinkExtension.default_session                                              | goutte                                           |
| default.extensions.Behat\MinkExtension.browser_name                                                 | chrome                                           |
| default.extensions.Behat\MinkExtension.javascript_session                                           | default                                          |
| default.extensions.Behat\MinkExtension.goutte.guzzle_parameters.verify                              | false                                            |
| default.extensions.Behat\MinkExtension.goutte.guzzle_parameters.redirect.disable                    | true                                             |
| default.extensions.Behat\MinkExtension.goutte.guzzle_parameters.ssl.certificate_authority           | system                                           |
| default.extensions.Behat\MinkExtension.goutte.guzzle_parameters.curl.options.CURLOPT_SSL_VERIFYPEER | false                                            |
| default.extensions.Behat\MinkExtension.goutte.guzzle_parameters.curl.options.CURLOPT_SSL_VERIFYHOST | false                                            |
| default.extensions.Behat\MinkExtension.goutte.guzzle_parameters.curl.options.CURLOPT_CERTINFO       | false                                            |
| default.extensions.Behat\MinkExtension.goutte.guzzle_parameters.curl.options.CURLOPT_TIMEOUT        | 120                                              |
| default.extensions.Behat\MinkExtension.files_path                                                   | %paths.base%/media                               |
| default.extensions.Drupal\DrupalExtension.blackbox                                                  |                                                  |
| default.extensions.Drupal\DrupalExtension.api_driver                                                | drupal                                           |
| default.extensions.jarnaiz\JUnitFormatter\JUnitFormatterExtension.filename                          | report.xml                                       |
| default.extensions.jarnaiz\JUnitFormatter\JUnitFormatterExtension.outputDir                         | %paths.base%/build/tests                         |
| default.extensions.Bex\Behat\ScreenshotExtension.screenshot_taking_mode                             | all_scenarios                                    |
| default.extensions.Bex\Behat\ScreenshotExtension.image_drivers.local.screenshot_directory           | ../screenshots                                   |
+-----------------------------------------------------------------------------------------------------+--------------------------------------------------+
[Filesystem\FilesystemStack] mkdir ["/var/www/mfgov-d8/reports"]
[info] Killing running google-chrome processes...
[info] Killing all processes on port '9222'...
[info] Launching headless chrome...
[Robo\Common\ProcessExecutor] Running 'google-chrome' --headless --disable-web-security --remote-debugging-port=9222  http://localhost in /var/www/mfgov-d8
[info] Waiting for response from http://localhost:9222...
[debug] cURL error 7: Failed to connect to localhost port 9222: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
[info] Waiting for response from http://localhost:9222...
[Testing\Behat] Running behat  --format pretty /var/www/mfgov-d8/tests/behat --colors --no-interaction --stop-on-failure --strict --config /var/www/mfgov-d8/tests/behat/local.yml --profile local --tags '~ajax&&~experimental&&~lightningextension' -v
@example
Feature: Web drivers
  In order to verify that web drivers are working
  As a user
  I should be able to load the homepage
  With and without Javascript

  @javascript
  Scenario: Load a page with Javascript # features/Examples.feature:9
    Given I am on "/"                   # Drupal\DrupalExtension\Context\MinkContext::visit()
    Then I should be on "/"             # Drupal\DrupalExtension\Context\MinkContext::assertPageAddress()

      Screenshot has been taken. Open image at ../screenshots/features_examples_feature_9.png
  Scenario: Load a page without Javascript      # features/Examples.feature:13
    Given I am on "/"                           # Drupal\DrupalExtension\Context\MinkContext::visit()
    Then the response status code should be 200 # Drupal\DrupalExtension\Context\MinkContext::assertResponseStatus()

@mfgov
Feature: Home page
  When I visit the home page
  As a user
  I should see certain page elements

  Scenario: A user should see full site title on the home page                                                                # features/Homepage.feature:7
    Given I am on "/"                                                                                                         # Drupal\DrupalExtension\Context\MinkContext::visit()
    Then I should see the text "A National Advanced Manufacturing Portal - Highlighting The NNMI Program | Manufacturing.gov" # Drupal\DrupalExtension\Context\MinkContext::assertTextVisible()

  Scenario: A user should see "News & Announcements" on the home page # features/Homepage.feature:11
    Given I am on "/"                                                 # Drupal\DrupalExtension\Context\MinkContext::visit()
    Then I should see the text "News & Announcements"                 # Drupal\DrupalExtension\Context\MinkContext::assertTextVisible()

  @javascript
  Scenario: A user should see the embedded Kaltura video player on the home page # features/Homepage.feature:16
    Given I am on "/"                                                            # Drupal\DrupalExtension\Context\MinkContext::visit()
      DMore\ChromeDriver\StreamReadException in /var/www/mfgov-d8/vendor/dmore/chrome-mink-driver/src/DevToolsConnection.php:70
      Stack trace:
      #0 /var/www/mfgov-d8/vendor/dmore/chrome-mink-driver/src/ChromePage.php(38): DMore\ChromeDriver\DevToolsConnection->waitFor(Object(Closure))
      #1 /var/www/mfgov-d8/vendor/dmore/chrome-mink-driver/src/ChromeDriver.php(172): DMore\ChromeDriver\ChromePage->visit('https://local.m...')
      #2 /var/www/mfgov-d8/vendor/behat/mink/src/Session.php(143): DMore\ChromeDriver\ChromeDriver->visit('https://local.m...')
      #3 /var/www/mfgov-d8/vendor/behat/mink-extension/src/Behat/MinkExtension/Context/RawMinkContext.php(131): Behat\Mink\Session->visit('https://local.m...')
      #4 /var/www/mfgov-d8/vendor/behat/mink-extension/src/Behat/MinkExtension/Context/MinkContext.php(49): Behat\MinkExtension\Context\RawMinkContext->visitPath('/')
      #5 [internal function]: Behat\MinkExtension\Context\MinkContext->visit('/')
      #6 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(103): call_user_func_array(Array, Array)
      #7 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(59): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #8 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(140): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #9 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(96): Behat\Testwork\Call\CallCenter->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #10 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(125): Behat\Testwork\Call\CallCenter->makeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #11 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(73): Behat\Behat\Tester\Runtime\RuntimeStepTester->testDefinition(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), Object(Behat\Behat\Definition\SearchResult), false)
      #12 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableStepTester.php(74): Behat\Behat\Tester\Runtime\RuntimeStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #13 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/TickingStepTester.php(59): Behat\Behat\Hook\Tester\HookableStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #14 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingStepTester.php(73): Behat\Behat\EventDispatcher\Tester\TickingStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #15 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/Tester/StepContainerTester.php(59): Behat\Behat\EventDispatcher\Tester\EventDispatchingStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #16 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeScenarioTester.php(76): Behat\Behat\Tester\StepContainerTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #17 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(74): Behat\Behat\Tester\Runtime\RuntimeScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #18 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(103): Behat\Behat\Hook\Tester\HookableScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #19 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php(69): Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #20 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(84): Behat\Behat\Tester\Runtime\IsolatingScenarioTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #21 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
      #22 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(71): Behat\Behat\Hook\Tester\HookableFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
      #23 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
      #24 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
      #25 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(72): Behat\Testwork\Hook\Tester\HookableSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
      #26 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
      #27 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(70): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
      #28 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
      #29 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test(Array, false)
      #30 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
      #31 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #32 /var/www/mfgov-d8/vendor/symfony/console/Command/Command.php(252): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #33 /var/www/mfgov-d8/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #34 /var/www/mfgov-d8/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #35 /var/www/mfgov-d8/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #36 /var/www/mfgov-d8/vendor/symfony/console/Application.php(148): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #37 /var/www/mfgov-d8/vendor/behat/behat/bin/behat(34): Symfony\Component\Console\Application->run()
      #38 {main}
    Then I should see the text "Kaltura Player"                                  # Drupal\DrupalExtension\Context\MinkContext::assertTextVisible()

      Screenshot has been taken. Open image at ../screenshots/features_homepage_feature_16.png
--- Failed scenarios:

    features/Homepage.feature:16

5 scenarios (4 passed, 1 failed)
10 steps (8 passed, 1 failed, 1 skipped)
0m7.16s (26.15Mb)
[Testing\Behat]  Exit code 1 
[info] Killing running google-chrome processes...
[info] Killing all processes on port '9222'...
[error]  Behat tests failed! 
10.443s total time elapsed.
```

And I expected this to happen:
Behat screenshot extension to take valid screenshots of the site.

Possibly related:
https://gitlab.com/DMore/behat-chrome-extension/issues/3

Do screenshots actually work without selenium?
https://github.com/elvetemedve/behat-screenshot/issues/38#issuecomment-315193651

CC @geerlingguy

**Comment by grasmash** [comment]
Screenshots do work without Selenium. I often find that I need to scroll very far down the image to see results.

**Comment by timwood** [comment]
Attached are the two screenshots from the tests. They are completely white and a very small file size.

![features_examples_feature_9](https://user-images.githubusercontent.com/91050/37522383-1bbbbc46-28fa-11e8-9ca7-a4ed4036fcce.png)
![features_homepage_feature_16](https://user-images.githubusercontent.com/91050/37522384-1bc81e5a-28fa-11e8-9e21-6008699b8ed6.png)

**Comment by timwood** [comment]
@grasmash Do you have screenshots working with the latest Chrome?

**Comment by mikemadison13** [comment]
I am unable to reproduce the specific errors that @timwood posted, but I can reproduce the behavior (even with the most recent release of bex/behat-screenshot). I am getting a blank screenshot.

Steps to reproduce:

# get a test that WILL fail (I intentionally broke one of my)
# tag the scenario with @javascript
# ensure that you have the correct configuration in behat.yml to enable the Sceenshot Extension
```
default:
  extensions:
    Bex\Behat\ScreenshotExtension:
      screenshot_taking_mode: failed_steps
      image_drivers:
        local:
          screenshot_directory: /tmp
```
# run the test

**Comment by timwood** [comment]
Alternatively to ensuring a failing test, you can change the `screenshot_taking_mode` setting to `all_scenarios`. You still need a test that uses @javascript.

**Comment by timwood** [comment]
I believe, in my case, the empty screenshot is due to headless chrome not allowing the connection due to SSL certificate issue. Unfortunately Chrome provides a white screen rather than a useful error message. I don't see an option for headless chrome to ignore validation of ssl certificates, other than `--allow-insecure-localhost`, which only works explicitly for https://localhost/.

For now my workaround is to set `project.local.protocol` to `http` in `blt/blt.yml`, along with tweaking my .htaccess rules to not rewrite all requests to SSL for the local hostname. In addition I had to change `base_url` in `tests/behat/local.yml` (which is untracked) to use http.

Obviously it would be ideal if we could run our tests locally (and in our CI) over SSL with a valid certificate (*where valid could be a self-signed cert properly installed into the OS cert store), in order to most closely match our production environment. 

Not sure what kind of interest there is in this feature, and maybe it's a topic more relevant to Drupal-VM or one of it's Ansible roles?

**Comment by geerlingguy** [comment]
Sadly, it's getting harder to use self-signed certs for local dev too; you have to make sure you add your root CA properly... and then if you've ever used HSTS for a domain it's hard to get the cert store to reflect a new cert if—god help you—you ever regenerated the cert/key!

I have started using .test domains now, and make sure to have HSTS disabled for local environments. Also, if possible, I either test without SSL, or get a wildcard cert for my domain and use local.domain.com so it works all the way through. Note that Let's Encrypt now supports wildcards!

**Comment by timwood** [comment]
Let's encrypt has a page about certs for localhost, with a section about making and trusting your certs https://letsencrypt.org/docs/certificates-for-localhost/. This also mentions https://github.com/jsha/minica. Is it hard to have Drupal VM consistently create and "install" a cert based on the configured hostname(s)? Could Drupal VM use minica?

Thanks for the idea on using Let's Encrypt's new wildcards via public server generation.

**Comment by mikemadison13** [comment]
@timwood i think your issue is resolved here?

**Comment by timwood** [comment]
I have a viable workaround, which I don't love, but will work for now.

**Comment by richardbporter** [comment]
Has anyone found another workaround/solution to this, besides https://github.com/acquia/blt/issues/2648#issuecomment-374713402?
