### ISSUE TITLE
Unable to provision virtual machine. This is likely due to an issue with your Drupal VM configuration and not BLT itself

### ISSUE THREAD

**Issue by krishnanmuthu** [acquia/blt#2753]
My system information:
* Operating system type: Linux(Ubuntu)
* Operating system version: 14.04
* BLT version: 8.9.14

When I run this command:

blt vm

```
I get the following output:
```
[error]  Could not find VM. Please ensure that the VM machine name matches project.machine_name 
/var/www/html/omsd8/blt/project.local.yml was modified.
BLT will now use @omsd8.local as the default drush alias for all commands on this machine.
[warning] The vagrant-hostsupdater plugin is not installed! Attempting to install it...
[Exec] Running vagrant plugin install vagrant-hostsupdater
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine_index.rb:321:in `initialize': Permission denied @ rb_sysopen - /home/muthu/.vagrant.d/data/machine-index/index.lock (Errno::EACCES)
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine_index.rb:321:in `open'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine_index.rb:321:in `with_index_lock'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine_index.rb:52:in `initialize'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:702:in `new'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:702:in `machine_index'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:186:in `block in action_runner'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:504:in `hook'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:753:in `unload'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/bin/vagrant:154:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/bin/vagrant:154:in `<main>'
[Exec]  Exit code 1  Time 0.34s
 Do you want to boot Drupal VM? (y/n) y
In future, run vagrant up to boot the VM.
[Exec] Running vagrant up in /var/www/html/omsd8
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine_index.rb:321:in `initialize': Permission denied @ rb_sysopen - /home/muthu/.vagrant.d/data/machine-index/index.lock (Errno::EACCES)
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine_index.rb:321:in `open'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine_index.rb:321:in `with_index_lock'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine_index.rb:52:in `initialize'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:702:in `new'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:702:in `machine_index'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:186:in `block in action_runner'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:504:in `hook'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:753:in `unload'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/bin/vagrant:154:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/bin/vagrant:154:in `<main>'
[Exec]  Exit code 1  Time 0.663s
[error]  Drupal VM failed to boot. Read Drupal VM's previous output for more information. 
 Do you want to try to re-provision the VM? Sometimes this works. (y/n) y
[Exec] Running vagrant provision in /var/www/html/omsd8
/opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine_index.rb:321:in `initialize': Permission denied @ rb_sysopen - /home/muthu/.vagrant.d/data/machine-index/index.lock (Errno::EACCES)
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine_index.rb:321:in `open'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine_index.rb:321:in `with_index_lock'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/machine_index.rb:52:in `initialize'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:702:in `new'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:702:in `machine_index'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:186:in `block in action_runner'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:504:in `hook'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:753:in `unload'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/bin/vagrant:154:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/bin/vagrant:154:in `<main>'
[Exec]  Exit code 1  Time 0.61s
[error]  Unable to provision virtual machine. This is likely due to an issue with your Drupal VM configuration and not BLT itself.
```

And I expected this to happen:

**Comment by geerlingguy** [comment]
99% sure this is due to an old Version of VirtualBox— @krishnanmuthu, can you list what version of VirtualBox is installed? Also what version of Vagrant (`vboxmanage --version` I think, and `vagrant --version`)?

Ubuntu 14.04 has _really_ old versions in its repo, and you really need to install from the downloads if you want a supported version.

**Comment by geerlingguy** [comment]
Could also be permissions, of course, since that's the actual error message displayed, but that would be the _second_ thing I check after versions. For permissions, you could just try deleting the entire .vagrant.d folder (assuming you don't need any info on any other VMs that might be set up on your host), with `sudo rm -rf /home/muthu/.vagrant.d`.

**Comment by grasmash** [comment]
@krishnanmuthu any update?

**Comment by grasmash** [comment]
Closing due to inactivity.
