### ISSUE TITLE
Failed Drupal Installation Doesn't Fail Build

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#2755]
My system information:
* Operating system type: Travis CI
* BLT version: 8.9.14

Output of `blt doctor`:
```
blt doctor
Attempting to run doctor on host machine...
+----------------------+----------------------------------------------------------------------------------+
| Property             | Value                                                                            |
+----------------------+----------------------------------------------------------------------------------+
| %paths               |                                                                                  |
|  - %root             | /var/www/capitalcamp/docroot                                                     |
|  - %site             | sites/default                                                                    |
|  - %modules          | modules                                                                          |
|  - %themes           | themes                                                                           |
|  - %config-sync      | /var/www/capitalcamp/config/default                                              |
|  - %files            | sites/default/files                                                              |
|  - %private          | /var/www/capitalcamp/files-private                                               |
|  - %temp             | /tmp                                                                             |
| admin-theme          | seven                                                                            |
| blt-version          | 8.9.14                                                                           |
| bootstrap            | Successful                                                                       |
| config-sync          | /var/www/capitalcamp/config/default                                              |
| db-driver            | mysql                                                                            |
| db-hostname          | localhost                                                                        |
| db-name              | drupal                                                                           |
| db-password          | drupal                                                                           |
| db-port              | 3306                                                                             |
| db-status            | Connected                                                                        |
| db-username          | drupal                                                                           |
| dev-desktop-enabled  | false                                                                            |
| drupal-settings-file | sites/default/settings.php                                                       |
| drupal-version       | 8.5.2                                                                            |
| drupal-vm-enabled    | true                                                                             |
| drush-alias-files    | /var/www/capitalcamp/docroot/../drush/site-aliases/aliases.drushrc.php           |
|                      | /var/www/capitalcamp/docroot/../drush/site-aliases/capitalcamp.aliases.drushrc.p |
|                      | hp                                                                               |
|                      | /var/www/capitalcamp/docroot/../drush/site-aliases/example.acsf.aliases.drushrc. |
|                      | php                                                                              |
|                      | /var/www/capitalcamp/docroot/../drush/site-aliases/example.local.aliases.drushrc |
|                      | .php                                                                             |
| drush-conf           | /var/www/capitalcamp/drush/drushrc.php                                           |
| drush-script         | /var/www/capitalcamp/vendor/drush/drush/drush.php                                |
| drush-temp           | /tmp                                                                             |
| drush-version        | 8.1.16                                                                           |
| files                | sites/default/files                                                              |
| install-profile      | lightning                                                                        |
| local-drushrc        | /var/www/capitalcamp/docroot/sites/default/local.drushrc.php                     |
| local-settings       | /var/www/capitalcamp/docroot/sites/default/settings/local.settings.php           |
| modules              | modules                                                                          |
| php-bin              | /usr/bin/php                                                                     |
| php-conf             | /etc/php/7.1/cli/php.ini                                                         |
| php-mysql            | /var/run/mysqld/mysqld.sock                                                      |
| php-os               | Linux                                                                            |
| private              | /var/www/capitalcamp/files-private                                               |
| root                 | /var/www/capitalcamp/docroot                                                     |
| shell                |                                                                                  |
| site                 | sites/default                                                                    |
| temp                 | /tmp                                                                             |
| theme                | twentyeighteen                                                                   |
| themes               | themes                                                                           |
| uri                  | http://local.capitalcamp.com                                                     |
| user                 |                                                                                  |
+----------------------+----------------------------------------------------------------------------------+
+--------------------------+----------------------------------------------------------------+
| Check                    | Outcome                                                        |
+--------------------------+----------------------------------------------------------------+
| checkDocrootExists       | Found docroot.                                                 |
| checkCoreExists          | Drupal core exists                                             |
| checkSettingsFile        | BLT settings are included in settings file.                    |
| checkLocalSettingsFile   | Found your local settings file.                                |
| checkLocalDrushFile      | Found your local drush settings file.                          |
| checkUri                 | $options['uri'] is set.                                        |
| checkUriResponse         | Received a response from site http://local.capitalcamp.com.    |
| checkFileSystem:%files   | Public files directory is writable.                            |
| checkFileSystem:%private | Private files directory is writable.                           |
| checkFileSystem:%temp    | Temporary files directory is writable.                         |
| checkDbConnection        | Connected to database.                                         |
| checkDrupalBootstrapped  | Bootstrapped Drupal via drush.                                 |
| checkDrupalInstalled     | Drupal is installed.                                           |
| checkCaching:page        | Drupal cache is disabled.                                      |
| checkCaching:css         | CSS preprocessing is disabled.                                 |
| checkCaching:js          | JS preprocessing is disabled.                                  |
| checkCiConfig            | Git remotes are set in project.yml.                            |
| checkComposer:require    | acquia/blt is in composer.json's require object.               |
| checkBehat:exists        | tests/behat/local.yml is missing!                              |
|                          |   Run `blt setup:behat` to generate it from example.local.yml. |
| checkProjectYml:keys     | project.yml has no deprecated keys.                            |
| checkAcsfConfig          | BLT settings are included in your pre-settings-php include.    |
| checkDrupalVm:alias      | drush.aliases.local exists your drush aliases file.            |
| checkDrupalVm            | Drupal VM is configured correctly.                             |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set                 |
+--------------------------+----------------------------------------------------------------+

```

When I run this command:
```
setup:drupal:install
```

I get the following output:
```
> setup:drupal:install
> internal:drupal:install
[Acquia\Blt\Robo\Tasks\DrushTask] Running /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/vendor/bin/drush @self site-install lightning install_configure_form.update_status_module='array(FALSE,FALSE)' install_configure_form.enable_update_status_module=NULL --site-name='Drupal GovCon' --site-mail=no-reply@acquia.com --account-name=a3aJbkeOU2 --account-mail=no-reply@acquia.com --locale=en --config-dir=../config/default --uri=default --yes --verbose in /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot
Executing: mysql --defaults-extra-file=/tmp/drush_8Ul5aA --database=drupal --host=127.0.0.1 --port=3306 --silent  < /tmp/drush_A2w4lN > /dev/null
You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y
Sites directory                                                         [notice]
/home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/sites/default
already exists - proceeding.
Executing: mysql --defaults-extra-file=/tmp/drush_S7qbR9 --database=drupal --host=127.0.0.1 --port=3306 --silent  < /tmp/drush_9nI70m > /dev/null
Executing: mysql --defaults-extra-file=/tmp/drush_ssklzJ --database=drupal --host=127.0.0.1 --port=3306 --silent  < /tmp/drush_SJJfIW
Starting Drupal installation. This takes a while. Consider using the [ok]
--notify global option.
Error: Call to undefined method Drupal\search_api\Utility\PostRequestIndexing::onKernelTerminate() in /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/modules/contrib/lightning_core/modules/lightning_search/lightning_search.module on line 138 #0 [internal function]: lightning_search_entity_insert(Object(Drupal\search_api\Entity\Index), 'search_api_inde...')
#1 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php(402): call_user_func_array('lightning_searc...', Array)
#2 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(378): Drupal\Core\Extension\ModuleHandler->invokeAll('entity_insert', Array)
#3 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/modules/contrib/search_api/src/Entity/SearchApiConfigEntityStorage.php(52): Drupal\Core\Config\Entity\ConfigEntityStorage->invokeHook('insert', Object(Drupal\search_api\Entity\Index))
#4 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(395): Drupal\search_api\Entity\SearchApiConfigEntityStorage->doPostSave(Object(Drupal\search_api\Entity\Index), false)
#5 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php(259): Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\search_api\Entity\Index))
#6 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/lib/Drupal/Core/Entity/Entity.php(387): Drupal\Core\Config\Entity\ConfigEntityStorage->save(Object(Drupal\search_api\Entity\Index))
#7 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php(637): Drupal\Core\Entity\Entity->save()
#8 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/lib/Drupal/Core/Config/ConfigInstaller.php(341): Drupal\Core\Config\Entity\ConfigEntityBase->save()
#9 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/lib/Drupal/Core/Config/ConfigInstaller.php(145): Drupal\Core\Config\ConfigInstaller->createConfiguration('', Array)
#10 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(75): Drupal\Core\Config\ConfigInstaller->installDefaultConfig('module', 'lightning_searc...')
#11 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(263): Drupal\Core\ProxyClass\Config\ConfigInstaller->installDefaultConfig('module', 'lightning_searc...')
#12 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#13 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/includes/install.core.inc(1813): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, false)
#14 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/includes/batch.inc(294): _install_module_batch('lightning_searc...', 'Lightning Searc...', Array)
#15 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/includes/form.inc(875): _batch_process()
#16 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/includes/install.core.inc(634): batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#17 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/includes/install.core.inc(555): install_run_task(Array, Array)
#18 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/core/includes/install.core.inc(117): install_run_tasks(Array)
#19 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/vendor/drush/drush/includes/drush.inc(727): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#20 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/vendor/drush/drush/includes/drush.inc(712): drush_call_user_func_array('install_drupal', Array)
#21 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/vendor/drush/drush/commands/core/drupal/site_install.inc(82): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#22 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/vendor/drush/drush/commands/core/site_install.drush.inc(255): drush_core_site_install_version('lightning', Array)
#23 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/vendor/drush/drush/includes/command.inc(422): drush_core_site_install('lightning', 'install_configu...', 'install_configu...')
#24 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#25 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/vendor/drush/drush/includes/command.inc(199): drush_command('lightning', 'install_configu...', 'install_configu...')
#26 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#27 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#28 /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/vendor/drush/drush/drush.php(12): drush_main()
#29 {main}
Error: Call to undefined method Drupal\search_api\Utility\PostRequestIndexing::onKernelTerminate() in lightning_search_entity_insert() (line 138 of /home/travis/build/Drupal4Gov/Drupal-GovCon-2017/docroot/modules/contrib/lightning_core/modules/lightning_search/lightning_search.module).
Drush command terminated abnormally due to an unrecoverable error.   [error]
A non well formed numeric value encountered drush.inc:1672              [notice]
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 35.123s
[error]  Failed to install Drupal! 
[error]  Command `internal:drupal:install ` exited with code 1. 
[error]  Command `setup:drupal:install ` exited with code 1. 
01:45 total time elapsed.
```

And I expected this to happen:
I expected the build to fail. However, it continued beyond the setup to run tests and it ended with a "pass."

**Comment by mikemadison13** [comment]
similar issue to https://github.com/acquia/blt/issues/1822

**Comment by mikemadison13** [comment]
see https://travis-ci.org/Drupal4Gov/Drupal-GovCon-2017/builds/368718622?utm_source=github_status&utm_medium=notification

**Comment by mikemadison13** [comment]
FYI @grasmash i haven't had a great deal of success chasing this one down

**Comment by mirsoftacquia** [comment]
We found that tick-tock.sh wrapper script that wraps the "blt setup" command in run_rests script is causing this. That script seems to return 0 (success) even if the command that has been run inside of this command returns 1 (error). That means, the information about error inside of the script is lost and Travis (and any other parent script) logically reports success as well.

As a workaround, removing tick-tock.sh in a custom run_tests script helped.

@mikemadison13 Did you found any other solutions / workarounds that could help to propose the permanent solution to this?

**Comment by swichers** [comment]
A quick set of Bash commands to implement the workaround:

```sh
mkdir -p blt/scripts
cp vendor/acquia/blt/scripts/travis/run_tests blt/scripts/
sed -i '' "s|\\\${BLT_DIR}/scripts/blt/ci/tick-tock.sh ||" blt/scripts/run_tests
```

**Comment by bobbygryzynger** [comment]
I can also confirm I've see this issue. Similar to @swichers I addressed it in my own codebase by removing the wrapper and I now wonder how necessary this wrapper script even is. It says it exists to prevent timeouts but on Travis that's 10 minutes with no output. I personally don't have any tasks that even come close to running that long with absolutely no output.

**Comment by mikemadison13** [comment]
closing due to inactivity
