### ISSUE TITLE
Behat/Selenium Error when running tests: Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by nortmas** [acquia/blt#2793]
My system information:
* Operating system version: ubuntu 14.04
* BLT version: 8.9.14

Output of `blt doctor`:
```
+----------------------+------------------------------------------------------------------------------+
| Property             | Value                                                                        |
+----------------------+------------------------------------------------------------------------------+
| %paths               |                                                                              |
|  - %root             | /var/www/acc/docroot                                                         |
|  - %site             | sites/default                                                                |
|  - %modules          | modules                                                                      |
|  - %themes           | themes                                                                       |
|  - %config-sync      | /var/www/acc/config/default                                                  |
|  - %files            | sites/default/files                                                          |
|  - %private          | /var/www/acc/files-private                                                   |
|  - %temp             | sites/default/files/tmp                                                      |
| admin-theme          | adminimal_theme                                                              |
| blt-version          | 8.9.14                                                                       |
| bootstrap            | Erfolgreich                                                                  |
| config-sync          | /var/www/acc/config/default                                                  |
| db-driver            | mysql                                                                        |
| db-hostname          | localhost                                                                    |
| db-name              | acc                                                                          |
| db-password          | pasd34afs                                                                     |
| db-port              | 3306                                                                         |
| db-status            | Connected                                                                    |
| db-username          | acc                                                                          |
| dev-desktop-enabled  | false                                                                        |
| drupal-settings-file | sites/default/settings.php                                                   |
| drupal-version       | 8.5.1                                                                        |
| drupal-vm-enabled    | true                                                                         |
| drush-alias-files    | /home/vagrant/.drush/aliases.drushrc.php                                     |
|                      | /var/www/acc/docroot/../drush/site-aliases/aliases.drushrc.php               |
|                      | /var/www/acc/docroot/../drush/site-aliases/example.acsf.aliases.drushrc.php  |
|                      | /var/www/acc/docroot/../drush/site-aliases/example.local.aliases.drushrc.php |
| drush-conf           | /var/www/acc/drush/drushrc.php                                               |
| drush-script         | /var/www/acc/vendor/drush/drush/drush.php                                    |
| drush-temp           | /tmp                                                                         |
| drush-version        | 8.1.16                                                                       |
| files                | sites/default/files                                                          |
| install-profile      | standard                                                                     |
| local-drushrc        | /var/www/acc/docroot/sites/default/local.drushrc.php                         |
| local-settings       | /var/www/acc/docroot/sites/default/settings/local.settings.php               |
| modules              | modules                                                                      |
| php-bin              | /usr/bin/php                                                                 |
| php-conf             | /etc/php/7.1/cli/php.ini                                                     |
| php-mysql            | /var/run/mysqld/mysqld.sock                                                  |
| php-os               | Linux                                                                        |
| private              | /var/www/acc/files-private                                                   |
| root                 | /var/www/acc/docroot                                                         |
| shell                |                                                                              |
| site                 | sites/default                                                                |
| temp                 | sites/default/files/tmp                                                      |
| theme                | acc                                                                          |
| themes               | themes                                                                       |
| uri                  | http://local.acc.com                                                         |
| user                 |                                                                              |
+----------------------+------------------------------------------------------------------------------+
+--------------------------+-----------------------------------------------------+
| Check                    | Outcome                                             |
+--------------------------+-----------------------------------------------------+
| checkDocrootExists       | Found docroot.                                      |
| checkCoreExists          | Drupal core exists                                  |
| checkSettingsFile        | BLT settings are included in settings file.         |
| checkLocalSettingsFile   | Found your local settings file.                     |
| checkLocalDrushFile      | Found your local drush settings file.               |
| checkUri                 | $options['uri'] is set.                             |
| checkUriResponse         | Received a response from site http://local.acc.com. |
| checkFileSystem:%files   | Public files directory is writable.                 |
| checkFileSystem:%private | Private files directory is writable.                |
| checkFileSystem:%temp    | Temporary files directory is writable.              |
| checkDbConnection        | Connected to database.                              |
| checkDrupalBootstrapped  | Could not bootstrap Drupal via drush without alias. |
| checkDrupalInstalled     | Drupal is installed.                                |
| checkCaching:page        | Drupal cache is disabled.                           |
| checkCaching:css         | CSS preprocessing is disabled.                      |
| checkCaching:js          | JS preprocessing is disabled.                       |
| checkComposer:require    | acquia/blt is in composer.json's require object.    |
| checkBehat:exists        | Behat local settings file exists.                   |
| checkBehat:root          | Behat drupal_root is set correctly for Drupal VM.   |
| checkProjectYml:keys     | project.yml has no deprecated keys.                 |
| checkDrupalVm:alias      | drush.aliases.local exists your drush aliases file. |
| checkDrupalVm            | Drupal VM is configured correctly.                  |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set      |
+--------------------------+-----------------------------------------------------+
```

When I run this command:
```
blt tests:behat
```

I get the following output:
```
[Robo\Common\ProcessExecutor] Running vagrant status --machine-readable in /home/nortmas/www/acc
[debug] vagrant acc.metadata = provider
[debug] vagrant acc.provider-name = virtualbox
[debug] vagrant acc.state = running
[debug] vagrant acc.state-human-short = running
[debug] vagrant acc.state-human-long = The VM is running. To stop this VM%!(VAGRANT_COMMA) you can run `vagrant halt` to\nshut it down forcefully%!(VAGRANT_COMMA) or you can run `vagrant suspend` to simply\nsuspend the virtual machine. In either case%!(VAGRANT_COMMA) to restart it again%!(VAGRANT_COMMA)\nsimply run `vagrant up`.
[debug] vagrant .ui = info
[debug] Drupal VM is initialized.
[debug] Drupal VM is booted.
[warning] The xDebug extension is loaded. This will significantly decrease performance.
Executing command blt 'tests:behat' --verbose --define=drush.alias=self inside of Drupal VM...
[ExecStack] vagrant ssh --command 'cd /var/www/acc; blt 'tests:behat' --verbose --define=drush.alias=self'
[ExecStack] Running vagrant ssh --command 'cd /var/www/acc; blt 'tests:behat' --verbose --define=drush.alias=self' in /home/nortmas/www/acc
/home/nortmas/www/acc/vendor/geerlingguy/drupal-vm/lib/drupalvm/vagrant.rb:6: warning: Insecure world writable dir /home/nortmas/.composer/vendor in PATH, mode 040777
[warning] The xDebug extension is loaded. This will significantly decrease performance.
[Filesystem\FilesystemStack] mkdir ["/var/www/acc/reports"]
[info] Killing running google-chrome processes...
[info] Killing all processes on port '9222'...
[info] Launching headless chrome...
[Robo\Common\ProcessExecutor] Running 'google-chrome' --headless --disable-gpu --remote-debugging-port=9222  https://www.chromestatus.com --disable-web-security --user-data-dir > /dev/null 2>&1 in /var/www/acc
[info] Waiting for response from localhost:9222...
[info] Waiting for response from localhost:9222...
[Testing\Behat] Running behat  --format pretty /var/www/acc/tests/behat.gitlab-ci/features --colors --no-interaction --stop-on-failure --strict --config /var/www/acc/tests/behat.gitlab-ci/behat.blt.yml --profile blt --tags '~ajax&&~experimental&&~lightningextension' -v
@accuchek
Feature: Customer Loyalty

  Background: Get rid of the cookie warning                                                                 # features/customer-loyalty.feature:4
    Given I am an anonymous user                                                                            # Drupal\DrupalExtension\Context\DrupalContext::assertAnonymousUser()
      WebDriver\Exception\UnknownError: unknown error: Chrome failed to start: exited abnormally
        (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.4.0-62-generic x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 60.01 seconds
      Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'
      System info: host: 'local', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-62-generic', java.version: '1.8.0_162'
      Driver info: driver.version: unknown in /var/www/acc/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
      Stack trace:
      #0 /var/www/acc/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(157): WebDriver\Exception::factory(13, 'unknown error: ...')
      #1 /var/www/acc/vendor/instaclick/php-webdriver/lib/WebDriver/WebDriver.php(70): WebDriver\AbstractWebDriver->curl('POST', '/session', Array, Array)
      #2 /var/www/acc/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(287): WebDriver\WebDriver->session(Array, Array)
      #3 /var/www/acc/vendor/behat/mink/src/Session.php(70): Behat\Mink\Driver\Selenium2Driver->start()
      #4 /var/www/acc/vendor/behat/mink/src/Mink.php(117): Behat\Mink\Session->start()
      #5 /var/www/acc/vendor/behat/mink-extension/src/Behat/MinkExtension/Context/RawMinkContext.php(108): Behat\Mink\Mink->getSession(NULL)
      #6 /var/www/acc/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/RawDrupalContext.php(587): Behat\MinkExtension\Context\RawMinkContext->getSession()
      #7 /var/www/acc/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/DrupalContext.php(30): Drupal\DrupalExtension\Context\RawDrupalContext->loggedIn()
      #8 [internal function]: Drupal\DrupalExtension\Context\DrupalContext->assertAnonymousUser()
      #9 /var/www/acc/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(103): call_user_func_array(Array, Array)
      #10 /var/www/acc/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(59): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))

```

behat.blt.yml:
```
blt:
  suites:
    default:
      paths:
        features: /var/www/acc
        bootstrap: /var/www/acc/tests/behat/features/bootstrap
      contexts:
        - Drupal\DrupalExtension\Context\ConfigContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\MessageContext
        - FeatureContext:
            parameters:
              screenshot_dir: /var/www/acc/tests/behat.gitlab-ci/_output/assets/screenshots
        - Devinci\DevinciExtension\Context\DebugContext:
            asset_dump_path: /var/www/acc/tests/behat.gitlab-ci/_output/assets
        - Devinci\DevinciExtension\Context\JavascriptContext:
            maximum_wait: 30
      filters:
        tags: "@accuchek&&~@wip"
  formatters:
    html:
      output_path: /var/www/acc/tests/behat.gitlab-ci/_output
  extensions:
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig,Behat2
      file_name: index
      print_args: true
      print_outp: true
      loop_break: true
    jarnaiz\JUnitFormatter\JUnitFormatterExtension:
      filename: report.xml
      outputDir: /var/www/acc/tests/behat.gitlab-ci/_output
    Behat\MinkExtension:
      browser_name: chrome
      javascript_session: selenium2
      base_url: http://local.acc.com
      show_cmd: "open %s"
      selenium2:
        wd_host: http://127.0.0.1:4444/wd/hub
        browser: chrome
      files_path: /var/www/acc/tests/behat.gitlab-ci/resources
    Drupal\DrupalExtension:
      api_driver: "drupal"
      drupal:
        drupal_root: /var/www/acc/docroot
      drush_driver: "drush"
      drush:
        alias: '@self'
      region_map:
        content: "#block-mainpagecontent"
        footer: "footer"
        navigation: ".header__people"
        header: "#main-header"
        header top: ".header__top"
        header login: ".header__login"
        header menu: "#header-menu"
        search bar: '.search-bar'
      selectors:
        message_selector: '[role="contentinfo"] > [role="alert"]'
        error_message_selector: '.form-validation-message--error'
      text:
        username_field: "E-Mail-Adresse"
        password_field: "Passwort"
        log_in: "Anmelden"
        log_out: "Logout"

```

**Comment by mikemadison13** [comment]
Digging a bit this looks like an issue that can crop up more specifically with either Selenium (https://github.com/SeleniumHQ/selenium/issues/4961) or the chrome driver (https://groups.google.com/forum/#!topic/chromedriver-users/8yZDv_h8feg). 

It does look like you've customized your behat.yml file, have you tried with the original (and simplified) one that ships with BLT? https://github.com/acquia/blt/blob/8.9.x/template/tests/behat/behat.yml

**Comment by nortmas** [comment]
I've turned back the default state and tried but unfortunately the same result.
Here is an output:
`➜  acc git:(dev) ✗ blt tests:behat -vvv
[Robo\Common\ProcessExecutor] Running vagrant status --machine-readable in /home/nortmas/www/acc
[debug] vagrant acc.metadata = provider
[debug] vagrant acc.provider-name = virtualbox
[debug] vagrant acc.state = running
[debug] vagrant acc.state-human-short = running
[debug] vagrant acc.state-human-long = The VM is running. To stop this VM%!(VAGRANT_COMMA) you can run `vagrant halt` to\nshut it down forcefully%!(VAGRANT_COMMA) or you can run `vagrant suspend` to simply\nsuspend the virtual machine. In either case%!(VAGRANT_COMMA) to restart it again%!(VAGRANT_COMMA)\nsimply run `vagrant up`.
[debug] vagrant .ui = info
[debug] Drupal VM is initialized.
[debug] Drupal VM is booted.
[warning] The xDebug extension is loaded. This will significantly decrease performance.
Executing command blt 'tests:behat' --verbose --define=drush.alias=self inside of Drupal VM...
[ExecStack] vagrant ssh --command 'cd /var/www/acc; blt 'tests:behat' --verbose --define=drush.alias=self'
[ExecStack] Running vagrant ssh --command 'cd /var/www/acc; blt 'tests:behat' --verbose --define=drush.alias=self' in /home/nortmas/www/acc
/home/nortmas/www/acc/vendor/geerlingguy/drupal-vm/lib/drupalvm/vagrant.rb:6: warning: Insecure world writable dir /home/nortmas/.composer/vendor in PATH, mode 040777
[warning] The xDebug extension is loaded. This will significantly decrease performance.
[Filesystem\FilesystemStack] mkdir ["/var/www/acc/reports"]
[info] Killing running google-chrome processes...
[info] Killing all processes on port '9222'...
[info] Launching headless chrome...
[Robo\Common\ProcessExecutor] Running 'google-chrome' --headless --disable-gpu --remote-debugging-port=9222  https://www.chromestatus.com --disable-web-security --user-data-dir > /dev/null 2>&1 in /var/www/acc
[info] Waiting for response from localhost:9222...
[info] Waiting for response from localhost:9222...
[Testing\Behat] Running behat  --format pretty /var/www/acc/tests/behat --colors --no-interaction --stop-on-failure --strict --config /var/www/acc/tests/behat/local.yml --profile local --tags '~ajax&&~experimental&&~lightningextension' -v
@example
Feature: Web drivers
  In order to verify that web drivers are working
  As a user
  I should be able to load the homepage
  With and without Javascript

  @javascript
  Scenario: Load a page with Javascript # features/Examples.feature:9
    Given I am on "/"                   # Drupal\DrupalExtension\Context\MinkContext::visit()
      WebDriver\Exception\UnknownError: unknown error: Chrome failed to start: exited abnormally
        (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.4.0-62-generic x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 60.34 seconds
      Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
      System info: host: 'local', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-62-generic', java.version: '1.8.0_162'
      Driver info: org.openqa.selenium.chrome.ChromeDriver in /var/www/acc/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
`

**Comment by mikemadison13** [comment]
closing due to inactivity
