### ISSUE TITLE
New project creation fails

### ISSUE THREAD

**Issue by greylabel** [acquia/blt#2832]
My system information:
* Operating system type: OS X
* Operating system version: 10.13.4
* BLT version: 9.0.0 (per output below)

Output of `blt doctor`:
```
09:52 $ blt doctor
PHP Notice:  Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70

Notice: Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70
PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:70
Stack trace:
#0 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(58): Acquia\Blt\Robo\Config\DefaultConfig->setSite('default')
#1 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(84): Acquia\Blt\Robo\Config\ConfigInitializer->setSite('default')
#2 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt-robo-run.php(29): Acquia\Blt\Robo\Config\ConfigInitializer->initialize()
#3 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt-robo.php(14): require_once('/Users/username/Si...')
#4 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt(11): require_once('/Users/username/Si...')
#5 {main}
  thrown in /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70

Fatal error: Uncaught Error: Call to a member function set() on null in /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:70
Stack trace:
#0 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(58): Acquia\Blt\Robo\Config\DefaultConfig->setSite('default')
#1 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(84): Acquia\Blt\Robo\Config\ConfigInitializer->setSite('default')
#2 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt-robo-run.php(29): Acquia\Blt\Robo\Config\ConfigInitializer->initialize()
#3 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt-robo.php(14): require_once('/Users/username/Si...')
#4 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt(11): require_once('/Users/username/Si...')
#5 {main}
  thrown in /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70
```

When I run this command:
```
composer create-project --no-interaction acquia/blt-project my-project
```

I get the following output:
```
09:49 $ composer create-project --no-interaction acquia/blt-project my-project
    1/8:	http://packagist.org/p/provider-latest$8554f355b1f2951e5e1f169130a2e739499379df2648372a5977b25cc817b11b.json
    2/8:	http://packagist.org/p/provider-2017-10$cb5cffe079967428b1566f42b41bdbd17f69bf17a3516425e3d72af5898289c5.json
    3/8:	http://packagist.org/p/provider-2017-07$84fd9c54fa83fa8caef0659dafec43a4b91b527f7362eafab5e9822d4a92320b.json
    4/8:	http://packagist.org/p/provider-2018-04$77b34c9fdac42a70e727581f6c8929bd7965eac0d1cb22e7f5d33b4f1de5af68.json
    5/8:	http://packagist.org/p/provider-2018-01$7200ee46a0be7fd98a331fde0ee9ac46dba7ea201ebb3f3120735fa59b89ce58.json
    6/8:	http://packagist.org/p/provider-2015$8c954c09651e5818c8cc3ca9c2a447e42387c8e97723bee82c243033f31556f3.json
    7/8:	http://packagist.org/p/provider-2017$c64727d910a9f70d1bd472c8fd101bd4b34b8ec1fcb19e30d140008a7717bf6a.json
    8/8:	http://packagist.org/p/provider-2016$9103be99fbd2847d2019dc45a7f224bfe24a7d1ef773e0a8ac4b5142a1488a5e.json
    Finished: success: 8, skipped: 0, failure: 0, total: 8
Installing acquia/blt-project (9.0.0)
  - Installing acquia/blt-project (9.0.0): Downloading (100%)
Created project in my-project
    1/1:	http://packagist.org/p/provider-latest$954a492983f5fd40754fcd1d2ac68bb77b8ee124d0796159147080d32e5f185d.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/10:	https://codeload.github.com/webflo/drupal-finder/legacy.zip/8a7886c575d6eaa67a425dceccc84e735c0b9637
    2/10:	https://codeload.github.com/consolidation/config/legacy.zip/ede41d946078e97e7a9513aadc3352f1c26817af
    3/10:	https://codeload.github.com/sarciszewski/php-future/legacy.zip/8bcc414eecfe68bb4600ab9b179ef6e8454b8ca0
    4/10:	https://codeload.github.com/acquia/http-hmac-php/legacy.zip/ee04f68a1c8e749b70bc2bb6da52da0db20d0009
    5/10:	https://codeload.github.com/typhonius/acquia-php-sdk-v2/legacy.zip/1c7887e44df0dfc75d51464196c2959ca13bddbb
    6/10:	https://codeload.github.com/symfony/twig-bridge/legacy.zip/03fd0a95d3cdcfa54863fca0baf589a5c8766508
    7/10:	https://codeload.github.com/consolidation/Robo/legacy.zip/ac563abfadf7cb7314b4e152f2b5033a6c255f6f
    8/10:	https://codeload.github.com/acquia/blt/legacy.zip/55a1b0976319fa49fff7eb3425719250ed7ea191
    9/10:	https://codeload.github.com/Chi-teck/drupal-code-generator/legacy.zip/20682ec4acc92e9671ba7b9bd0e972978c3a08f2
    10/10:	https://codeload.github.com/drush-ops/drush/legacy.zip/82e00a5437b5d2c21ee0f5b3090c3931db3cb71b
    Finished: success: 10, skipped: 0, failure: 0, total: 10
Package operations: 79 installs, 0 updates, 0 removals
  - Installing wikimedia/composer-merge-plugin (v1.4.1): Loading from cache
  - Installing composer/installers (v1.5.0): Loading from cache
  - Installing grasmash/drupal-security-warning (1.1.1): Loading from cache
  - Installing cweagans/composer-patches (1.6.4): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing sarciszewski/php-future (0.4.2): Loading from cache
  - Installing acquia/http-hmac-php (3.4.0): Loading from cache
  - Installing typhonius/acquia-php-sdk-v2 (1.0.2): Loading from cache
  - Installing tivie/php-os-detector (1.1.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.8.0): Loading from cache
  - Installing symfony/yaml (v3.4.11): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.8.0): Loading from cache
  - Installing twig/twig (v1.35.3): Loading from cache
  - Installing symfony/twig-bridge (v3.4.11): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v4.0.11): Loading from cache
  - Installing symfony/console (v3.4.11): Loading from cache
  - Installing squizlabs/php_codesniffer (2.9.1): Loading from cache
  - Installing sebastian/version (1.0.6): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (1.0.5): Loading from cache
  - Installing sebastian/exporter (1.2.2): Loading from cache
  - Installing sebastian/environment (1.3.8): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (1.2.4): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (2.3.8): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing phpunit/php-token-stream (1.4.12): Loading from cache
  - Installing phpunit/php-code-coverage (2.2.4): Loading from cache
  - Installing webmozart/assert (1.3.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.7.6): Loading from cache
  - Installing phpunit/phpunit (4.8.36): Loading from cache
  - Installing oomphinc/composer-installers-extender (v1.1.2): Loading from cache
  - Installing dflydev/dot-access-data (v1.1.0): Loading from cache
  - Installing grasmash/yaml-expander (1.4.0): Loading from cache
  - Installing symfony/filesystem (v3.4.11): Loading from cache
  - Installing grasmash/yaml-cli (1.0.3): Loading from cache
  - Installing symfony/config (v3.4.11): Loading from cache
  - Installing symfony/event-dispatcher (v3.4.11): Loading from cache
  - Installing webmozart/path-util (2.3.0): Loading from cache
  - Installing webflo/drupal-finder (1.1.0): Loading from cache
  - Installing symfony/var-dumper (v3.4.11): Loading from cache
  - Installing symfony/process (v3.4.11): Loading from cache
  - Installing symfony/finder (v3.4.11): Loading from cache
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing nikic/php-parser (v4.0.1): Loading from cache
  - Installing psy/psysh (v0.9.4): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing container-interop/container-interop (1.2.0): Loading from cache
  - Installing league/container (2.4.1): Loading from cache
  - Installing consolidation/output-formatters (3.2.1): Loading from cache
  - Installing consolidation/log (1.0.6): Loading from cache
  - Installing consolidation/annotated-command (2.8.4): Loading from cache
  - Installing grasmash/expander (1.0.0): Loading from cache
  - Installing consolidation/config (1.0.11): Loading from cache
  - Installing consolidation/robo (1.3.0): Loading from cache
  - Installing composer/semver (1.4.2): Loading from cache
  - Installing chi-teck/drupal-code-generator (1.24.0): Loading from cache
  - Installing drush/drush (9.3.0): Loading from cache
  - Installing drupal/coder (8.2.12): Cloning 984c54a7b1 from cache
  - Installing doctrine/inflector (v1.1.0): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (v1.7.1): Loading from cache
  - Installing doctrine/annotations (v1.6.0): Loading from cache
  - Installing doctrine/common (v2.8.1): Loading from cache
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.4.4): Loading from cache
  - Installing acquia/blt (9.0.5): Loading from cache
acquia/http-hmac-php suggests installing silex/silex (~1.3.0)
acquia/http-hmac-php suggests installing symfony/psr-http-message-bridge (~0.1.0)
acquia/http-hmac-php suggests installing symfony/security (~3.0.0)
acquia/http-hmac-php suggests installing zendframework/zend-diactoros (~1.3.5)
symfony/twig-bridge suggests installing symfony/asset (For using the AssetExtension)
symfony/twig-bridge suggests installing symfony/expression-language (For using the ExpressionExtension)
symfony/twig-bridge suggests installing symfony/form (For using the FormExtension)
symfony/twig-bridge suggests installing symfony/http-kernel (For using the HttpKernelExtension)
symfony/twig-bridge suggests installing symfony/routing (For using the RoutingExtension)
symfony/twig-bridge suggests installing symfony/security (For using the SecurityExtension)
symfony/twig-bridge suggests installing symfony/stopwatch (For using the StopwatchExtension)
symfony/twig-bridge suggests installing symfony/templating (For using the TwigEngine)
symfony/twig-bridge suggests installing symfony/translation (For using the TranslationExtension)
symfony/twig-bridge suggests installing symfony/web-link (For using the WebLinkExtension)
symfony/console suggests installing symfony/lock ()
symfony/console suggests installing psr/log-implementation (For using the console logger)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
symfony/var-dumper suggests installing ext-symfony_debug ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
consolidation/robo suggests installing henrikbjorn/lurker (For monitoring filesystem changes in taskWatch)
consolidation/robo suggests installing natxet/CssMin (For minifying CSS files in taskMinify)
consolidation/robo suggests installing patchwork/jsqueeze (For minifying JS files in taskMinify)
consolidation/robo suggests installing pear/archive_tar (Allows tar archives to be created and extracted in taskPack and taskExtract, respectively.)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
dealerdirect/phpcodesniffer-composer-installer suggests installing dealerdirect/qa-tools (All the PHP QA tools you'll need)
acquia/blt suggests installing hirak/prestissimo (^0.3)
acquia/blt suggests installing typhonius/acquia_cli (^0.0.7)
acquia/blt suggests installing davereid/drush-acquia-hook-invoke (dev-master)
Writing lock file
Generating autoload files
Copying /Users/username/Sites/tmp/my-project/vendor/acquia/blt/composer.required.json to /Users/username/Sites/tmp/my-project/blt/composer.required.json
Copying /Users/username/Sites/tmp/my-project/vendor/acquia/blt/composer.suggested.json to /Users/username/Sites/tmp/my-project/blt/composer.suggested.json
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer/
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer/
Creating BLT templated files...
 > /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt internal:create-project --ansi

Notice: Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70

Fatal error: Uncaught Error: Call to a member function set() on null in /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:70
Stack trace:
#0 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(58): Acquia\Blt\Robo\Config\DefaultConfig->setSite('default')
#1 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(84): Acquia\Blt\Robo\Config\ConfigInitializer->setSite('default')
#2 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt-robo-run.php(29): Acquia\Blt\Robo\Config\ConfigInitializer->initialize()
#3 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt-robo.php(14): require_once('/Users/username/Si...')
#4 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt(11): require_once('/Users/username/Si...')
#5 {main}
  thrown in /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70
PHP Notice:  Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70
PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:70
Stack trace:
#0 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(58): Acquia\Blt\Robo\Config\DefaultConfig->setSite('default')
#1 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(84): Acquia\Blt\Robo\Config\ConfigInitializer->setSite('default')
#2 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt-robo-run.php(29): Acquia\Blt\Robo\Config\ConfigInitializer->initialize()
#3 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt-robo.php(14): require_once('/Users/username/Si...')
#4 /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt(11): require_once('/Users/username/Si...')
#5 {main}
  thrown in /Users/username/Sites/tmp/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70
BLT installation failed! Please execute /Users/username/Sites/tmp/my-project/vendor/acquia/blt/bin/blt internal:create-project --ansi --verbose to debug the issue.
```

And I expected this to happen:
New project setup to complete successfully.

**Comment by guptas89** [comment]
I am also facing same issue. Any solution yet?

Here is system configuration:

Composer version 1.6.3 
Drush Commandline Tool 9.3.0
PHP 7.1.15-1+ubuntu16.04

**Comment by vaibhavjain-in** [comment]
I am having the same issue, no resolution yet.

**Comment by manishkumar1988** [comment]
I am having the same issue, 

Composer version 1.6.5
Drush Version : 9.3.0
OS - Ubuntu 16.04
PHP 7.2.5

**Comment by bartfeenstra** [comment]
This is a backwards compatibility break in consolidation/robo. As a workaround, either until the break has been fixed, or BLT has been updated to work with consolitation/robo 1.3.0+ as well, the solution is to add `"consolidation/robo:~1.2.4"` to the `require` section in your `composer.json`.

**Comment by vaibhavjain-in** [comment]
@bartfeenstra Thanks, that does solve the issue.
Steps for fix, that worked for me.

1. After you get the error, update composer.json, and it looks like this now.
```{
    "name": "acquia/blt-project",
    "description": "Project template for Drupal 8 sites built with BLT.",
    "type": "project",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "acquia/blt": "^9.0.3",
		"consolidation/robo": "~1.2.4"
    },
    "require-dev": {}
}```

2. Remove any other directories like blt, vendor. Only files present should be License, readme and composer.json.
3. Run `composer install`.

Everything should be good post this.

**Comment by guptas89** [comment]
Thanks.. @bartfeenstra @vaibhavjain-in 

This issue is resolved using updated composer.json file. But now I am getting following error. Any idea why this error:

BLT can automatically create a Bash alias to make it easier to run BLT tasks.
This alias will be created in /home/ubuntu/.bashrc.
[ExecStack] git init && git add -A && git commit -m 'Initial commit.'
[ExecStack]  Initialized empty Git repository in /var/www/html/blt-project/.git/ 
[ExecStack]  Exit code 128 
[error]  Could not initialize new git repository.
BLT installation failed! Please execute /var/www/html/blt-project/vendor/acquia/blt/bin/blt internal:create-project --ansi --verbose to debug the issue.

**Comment by mikemadison13** [comment]
@guptas89 if you are continuing to see the issue you commented on, please create a new issue.

**Comment by greylabel** [comment]
@mikemadison13 here is backport for `8.9.x` -- https://github.com/acquia/blt/pull/2834/files

**Comment by shelane** [comment]
Since running the command `composer create-project --no-interaction acquia/blt-project my-project` still pulls BLT 9.0.0 to start, what can users do running the create-project command to get the version that has the fix?
