### ISSUE TITLE
Cannot initialize new project with composer

### ISSUE THREAD

**Issue by rhuffstedtler** [acquia/blt#2835]
My system information:
* Operating system type: MacOS 
* Operating system version: 10.13.4
* BLT version: 9.0.5

Output of `blt doctor`:
```
-bash: blt: command not found
```
NOTE: it runs fine in previously created projects

When I run this command:
```
composer create-project --no-interaction acquia/blt-project my-project
```

I get the following output:
```
Installing acquia/blt-project (9.0.0)
  - Installing acquia/blt-project (9.0.0): Loading from cache
Created project in my-project
    1/1:        http://packagist.org/p/provider-latest$1f48cbf1a8e8ae6d49f9b2331ab0a851aea72c1232799b08e11825a7fdef0733.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 79 installs, 0 updates, 0 removals
  - Installing wikimedia/composer-merge-plugin (v1.4.1): Loading from cache
  - Installing composer/installers (v1.5.0): Loading from cache
  - Installing grasmash/drupal-security-warning (1.1.1): Loading from cache
  - Installing cweagans/composer-patches (1.6.4): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing sarciszewski/php-future (0.4.2): Loading from cache
  - Installing acquia/http-hmac-php (3.4.0): Loading from cache
  - Installing typhonius/acquia-php-sdk-v2 (1.0.2): Loading from cache
  - Installing tivie/php-os-detector (1.1.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.8.0): Loading from cache
  - Installing symfony/yaml (v3.4.11): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.8.0): Loading from cache
  - Installing twig/twig (v1.35.3): Loading from cache
  - Installing symfony/twig-bridge (v3.4.11): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v4.0.11): Loading from cache
  - Installing symfony/console (v3.4.11): Loading from cache
  - Installing squizlabs/php_codesniffer (2.9.1): Loading from cache
  - Installing sebastian/version (1.0.6): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (1.0.5): Loading from cache
  - Installing sebastian/exporter (1.2.2): Loading from cache
  - Installing sebastian/environment (1.3.8): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (1.2.4): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (2.3.8): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing phpunit/php-token-stream (1.4.12): Loading from cache
  - Installing phpunit/php-code-coverage (2.2.4): Loading from cache
  - Installing webmozart/assert (1.3.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.0): Loading from cache
  - Installing phpspec/prophecy (1.7.6): Loading from cache
  - Installing phpunit/phpunit (4.8.36): Loading from cache
  - Installing oomphinc/composer-installers-extender (v1.1.2): Loading from cache
  - Installing dflydev/dot-access-data (v1.1.0): Loading from cache
  - Installing grasmash/yaml-expander (1.4.0): Loading from cache
  - Installing symfony/filesystem (v3.4.11): Loading from cache
  - Installing grasmash/yaml-cli (1.0.3): Loading from cache
  - Installing symfony/config (v3.4.11): Loading from cache
  - Installing symfony/event-dispatcher (v3.4.11): Loading from cache
  - Installing webmozart/path-util (2.3.0): Loading from cache
  - Installing webflo/drupal-finder (1.1.0): Loading from cache
  - Installing symfony/var-dumper (v3.4.11): Loading from cache
  - Installing symfony/process (v3.4.11): Loading from cache
  - Installing symfony/finder (v3.4.11): Loading from cache
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing nikic/php-parser (v4.0.1): Loading from cache
  - Installing psy/psysh (v0.9.4): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing container-interop/container-interop (1.2.0): Loading from cache
  - Installing league/container (2.4.1): Loading from cache
  - Installing consolidation/output-formatters (3.2.1): Loading from cache
  - Installing consolidation/log (1.0.6): Loading from cache
  - Installing consolidation/annotated-command (2.8.4): Loading from cache
  - Installing grasmash/expander (1.0.0): Loading from cache
  - Installing consolidation/config (1.0.11): Loading from cache
  - Installing consolidation/robo (1.3.0): Loading from cache
  - Installing composer/semver (1.4.2): Loading from cache
  - Installing chi-teck/drupal-code-generator (1.24.0): Loading from cache
  - Installing drush/drush (9.3.0): Loading from cache
  - Installing drupal/coder (8.2.12): Cloning 984c54a7b1 from cache
  - Installing doctrine/inflector (v1.1.0): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (v1.7.1): Loading from cache
  - Installing doctrine/annotations (v1.6.0): Loading from cache
  - Installing doctrine/common (v2.8.1): Loading from cache
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.4.4): Loading from cache
  - Installing acquia/blt (9.0.5): Loading from cache
acquia/http-hmac-php suggests installing silex/silex (~1.3.0)
acquia/http-hmac-php suggests installing symfony/psr-http-message-bridge (~0.1.0)
acquia/http-hmac-php suggests installing symfony/security (~3.0.0)
acquia/http-hmac-php suggests installing zendframework/zend-diactoros (~1.3.5)
symfony/twig-bridge suggests installing symfony/asset (For using the AssetExtension)
symfony/twig-bridge suggests installing symfony/expression-language (For using the ExpressionExtension)
symfony/twig-bridge suggests installing symfony/form (For using the FormExtension)
symfony/twig-bridge suggests installing symfony/http-kernel (For using the HttpKernelExtension)
symfony/twig-bridge suggests installing symfony/routing (For using the RoutingExtension)
symfony/twig-bridge suggests installing symfony/security (For using the SecurityExtension)
symfony/twig-bridge suggests installing symfony/stopwatch (For using the StopwatchExtension)
symfony/twig-bridge suggests installing symfony/templating (For using the TwigEngine)
symfony/twig-bridge suggests installing symfony/translation (For using the TranslationExtension)
symfony/twig-bridge suggests installing symfony/web-link (For using the WebLinkExtension)
symfony/console suggests installing symfony/lock ()
symfony/console suggests installing psr/log-implementation (For using the console logger)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
symfony/var-dumper suggests installing ext-intl (To show region name in time zone dump)
symfony/var-dumper suggests installing ext-symfony_debug ()
psy/psysh suggests installing ext-pcntl (Enabling the PCNTL extension makes PsySH a lot happier :))
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
consolidation/robo suggests installing henrikbjorn/lurker (For monitoring filesystem changes in taskWatch)
consolidation/robo suggests installing natxet/CssMin (For minifying CSS files in taskMinify)
consolidation/robo suggests installing patchwork/jsqueeze (For minifying JS files in taskMinify)
consolidation/robo suggests installing pear/archive_tar (Allows tar archives to be created and extracted in taskPack and taskExtract, respectively.)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
dealerdirect/phpcodesniffer-composer-installer suggests installing dealerdirect/qa-tools (All the PHP QA tools you'll need)
acquia/blt suggests installing hirak/prestissimo (^0.3)
acquia/blt suggests installing typhonius/acquia_cli (^0.0.7)
acquia/blt suggests installing davereid/drush-acquia-hook-invoke (dev-master)
Writing lock file
Generating autoload files
Copying /Users/roberthuffstedtler/Sites/devdesktop/my-project/vendor/acquia/blt/composer.required.json to /Users/roberth
uffstedtler/Sites/devdesktop/my-project/blt/composer.required.json
Copying /Users/roberthuffstedtler/Sites/devdesktop/my-project/vendor/acquia/blt/composer.suggested.json to /Users/roberthuffstedtler/Sites/devdesktop/my-project/blt/composer.suggested.json
    1/1:        http://packagist.org/p/provider-latest$1f48cbf1a8e8ae6d49f9b2331ab0a851aea72c1232799b08e11825a7fdef0733.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer/
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer/
Creating BLT templated files...
 > /Users/roberthuffstedtler/Sites/devdesktop/my-project/vendor/acquia/blt/bin/blt internal:create-project --ansi
PHP Notice:  Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /Users/roberthuffstedtler/Sites/devdesktop/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70
PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /Users/roberthuffstedtler/Sites/devdesktop/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:70
Stack trace:
#0 /Users/roberthuffstedtler/Sites/devdesktop/my-project/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(58): Acquia\Blt\Robo\Config\DefaultConfig->setSite('default')
#1 /Users/roberthuffstedtler/Sites/devdesktop/my-project/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(84): Acquia\Blt\Robo\Config\ConfigInitializer->setSite('default')
#2 /Users/roberthuffstedtler/Sites/devdesktop/my-project/vendor/acquia/blt/bin/blt-robo-run.php(29): Acquia\Blt\Robo\Config\ConfigInitializer->initialize()
#3 /Users/roberthuffstedtler/Sites/devdesktop/my-project/vendor/acquia/blt/bin/blt-robo.php(14): require_once('/Users/roberthu...')
#4 /Users/roberthuffstedtler/Sites/devdesktop/my-project/vendor/acquia/blt/bin/blt(11): require_once('/Users/roberthu...')
#5 {main}
  thrown in /Users/roberthuffstedtler/Sites/devdesktop/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70
BLT installation failed! Please execute /Users/roberthuffstedtler/Sites/devdesktop/my-project/vendor/acquia/blt/bin/blt internal:create-project --ansi --verbose to debug the issue.
roberthuffstedtler@Roberts-MBP:
```

And I expected this to happen:
I expected a project to be completed. It was not.

**Comment by mikemadison13** [comment]
this is a known issue and has been fixed in 9.x-dev (see https://github.com/acquia/blt/issues/2832). we are working on cutting a new 9.1 release tag soon to address this. please use this command instead:

```
composer create-project --no-interaction acquia/blt-project:9.x-dev my-project
```
