### ISSUE TITLE
"blt setup" causing the problems with DefaultConfig::$config

### ISSUE THREAD

**Issue by pralhadglobant** [acquia/blt#2838]
My system information:
* Operating system type: [Ubuntu]
* Operating system version: [14 LTS]
* BLT version: [8.9.14]

Output of `blt doctor`:
```
vagrant@local:/var/www/PROJECTNAME$ blt doctor
[warning] The xDebug extension is loaded. This will significantly decrease performance.
PHP Notice:  Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71

Notice: Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71
PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:71
Stack trace:
#0 /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Hooks/InitHook.php(35): Acquia\Blt\Robo\Config\DefaultConfig->setSiteConfig('default')
#1 /var/www/PROJECTNAME/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(37): Acquia\Blt\Robo\Hooks\InitHook->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#2 /var/www/PROJECTNAME/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#3 /var/www/PROJECTNAME/vendor/consolidation/annotated-command/src/CommandProcessor.php(117): Consolidation\AnnotatedCommand\Hooks\Dispatchers\Initia in /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71

Fatal error: Uncaught Error: Call to a member function set() on null in /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:71
Stack trace:
#0 /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Hooks/InitHook.php(35): Acquia\Blt\Robo\Config\DefaultConfig->setSiteConfig('default')
#1 /var/www/PROJECTNAME/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(37): Acquia\Blt\Robo\Hooks\InitHook->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#2 /var/www/PROJECTNAME/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#3 /var/www/PROJECTNAME/vendor/consolidation/annotated-command/src/CommandProcessor.php(117): Consolidation\AnnotatedCommand\Hooks\Dispatchers\Initia in /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71
vagrant@local:/var/www/PROJECTNAME$
```

When I run this command:
```
blt setup
```

I get the following output:
```
vagrant@local:/var/www/PROJECTNAME$ blt doctor
[warning] The xDebug extension is loaded. This will significantly decrease performance.
PHP Notice:  Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71

Notice: Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71
PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:71
Stack trace:
#0 /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Hooks/InitHook.php(35): Acquia\Blt\Robo\Config\DefaultConfig->setSiteConfig('default')
#1 /var/www/PROJECTNAME/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(37): Acquia\Blt\Robo\Hooks\InitHook->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#2 /var/www/PROJECTNAME/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#3 /var/www/PROJECTNAME/vendor/consolidation/annotated-command/src/CommandProcessor.php(117): Consolidation\AnnotatedCommand\Hooks\Dispatchers\Initia in /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71

Fatal error: Uncaught Error: Call to a member function set() on null in /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:71
Stack trace:
#0 /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Hooks/InitHook.php(35): Acquia\Blt\Robo\Config\DefaultConfig->setSiteConfig('default')
#1 /var/www/PROJECTNAME/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(37): Acquia\Blt\Robo\Hooks\InitHook->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#2 /var/www/PROJECTNAME/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#3 /var/www/PROJECTNAME/vendor/consolidation/annotated-command/src/CommandProcessor.php(117): Consolidation\AnnotatedCommand\Hooks\Dispatchers\Initia in /var/www/PROJECTNAME/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71
vagrant@local:/var/www/PROJECTNAME$
```

And I expected this to happen:

I have observed since composer update has updated the versions of BLT and its dependent libs problem is occuring. ROBO and CONSOLIDATION lib's versions are changed too.

**Comment by mikemadison13** [comment]
See https://github.com/acquia/blt/pull/2837

**Comment by pralhadglobant** [comment]
Still, it is not working. Even though I have changed the version of ROB too

```
"consolidation/robo": "~1.2.4",
```

Still, I am facing the same issue.

**Comment by mikemadison13** [comment]
where did you make the change @pralhadglobant ? you should be able to manually update this in the composer.json file that is created, then remove your vendor folder, then run composer update. i was able to successfully install 8.9.14 with these steps.

**Comment by pralhadglobant** [comment]
Thanks for the reply. I made this manual change to composer.json. 

- config [all the yml configs are stored here]
- docroot  [drupal project docroot]
- vendor [vendor libs]
-- acquia
--- blt
- composer.lock  
- composer.json [this is the file that I have made the change too].
