### ISSUE TITLE
BLT doctor throwing php fatal error after composer update

### ISSUE THREAD

**Issue by sandipsmarty** [acquia/blt#2839]
My system information:
* Operating system type: Mac
* Operating system version: 10.13.4
* BLT version: 8.9.14

Output of `blt doctor`:
```
[warning] The xDebug extension is loaded. This will significantly decrease performance.
PHP Notice:  Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /var/www/belize/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71

Notice: Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /var/www/belize/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71
PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /var/www/belize/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:71
Stack trace:
#0 /var/www/belize/vendor/acquia/blt/src/Robo/Hooks/InitHook.php(35): Acquia\Blt\Robo\Config\DefaultConfig->setSiteConfig('default')
#1 /var/www/belize/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(37): Acquia\Blt\Robo\Hooks\InitHook->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#2 /var/www/belize/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#3 /var/www/belize/vendor/consolidation/annotated-command/src/CommandProcessor.php(117): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher-> in /var/www/belize/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71

Fatal error: Uncaught Error: Call to a member function set() on null in /var/www/belize/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:71
Stack trace:
#0 /var/www/belize/vendor/acquia/blt/src/Robo/Hooks/InitHook.php(35): Acquia\Blt\Robo\Config\DefaultConfig->setSiteConfig('default')
#1 /var/www/belize/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(37): Acquia\Blt\Robo\Hooks\InitHook->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#2 /var/www/belize/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#3 /var/www/belize/vendor/consolidation/annotated-command/src/CommandProcessor.php(117): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher-> in /var/www/belize/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71
```

I running `composer update` the Travis build is failing & throwing the following error

`Notice: Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /home/travis/build/Citytechinc/belize/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71
PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /home/travis/build/Citytechinc/belize/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:71
Stack trace:
#0 /home/travis/build/Citytechinc/belize/vendor/acquia/blt/src/Robo/Hooks/InitHook.php(35): Acquia\Blt\Robo\Config\DefaultConfig->setSiteConfig('default')
#1 /home/travis/build/Citytechinc/belize/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(37): Acquia\Blt\Robo\Hooks\InitHook->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#2 /home/travis/build/Citytechinc/belize/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#3 /home/travis/build/Citytechinc/belize/vendor/consolidation/annotated-comm in /home/travis/build/Citytechinc/belize/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71`

Seems the issue with BLT.

**Comment by nileshlohar** [comment]
Adding "consolidation/robo:~1.2.4" to the require section of composer.json solves this issue.
