### ISSUE TITLE
blt stops working when upgrading to 1.3.0

### ISSUE THREAD

**Issue by gheydon** [acquia/blt#2844]
My system information:
* Operating system type: OS X (Mac OS)
* Operating system version: 10.13.4
* BLT version: 9.0.5

When updating Robo to 1.3.0, I get the following errors.

Output of `blt doctor`:
```
PHP Notice:  Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70
PHP Stack trace:
PHP   1. {main}() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt:0
PHP   2. require_once() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt:11
PHP   3. require_once() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo.php:14
PHP   4. Acquia\Blt\Robo\Config\ConfigInitializer->initialize() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo-run.php:29
PHP   5. Acquia\Blt\Robo\Config\ConfigInitializer->setSite() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php:84
PHP   6. Acquia\Blt\Robo\Config\DefaultConfig->setSite() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php:58

Notice: Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70

Call Stack:
    0.0003     389960   1. {main}() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt:0
    0.0006     399472   2. require_once('/Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo.php') /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt:11
    0.0136    1496512   3. require_once('/Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo-run.php') /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo.php:14
    0.0228    2180616   4. Acquia\Blt\Robo\Config\ConfigInitializer->initialize() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo-run.php:29
    0.0228    2180616   5. Acquia\Blt\Robo\Config\ConfigInitializer->setSite() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php:84
    0.0228    2180616   6. Acquia\Blt\Robo\Config\DefaultConfig->setSite() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php:58

PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:70
Stack trace:
#0 /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(58): Acquia\Blt\Robo\Config\DefaultConfig->setSite('default')
#1 /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(84): Acquia\Blt\Robo\Config\ConfigInitializer->setSite('default')
#2 /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo-run.php(29): Acquia\Blt\Robo\Config\ConfigInitializer->initialize()
#3 /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo.php(14): require_once('/Users/gordon/S...')
#4 /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt(11): require_once('/Users/gordon/S...')
#5 {main}
  thrown in /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70

Fatal error: Uncaught Error: Call to a member function set() on null in /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70

Error: Call to a member function set() on null in /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70

Call Stack:
    0.0003     389960   1. {main}() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt:0
    0.0006     399472   2. require_once('/Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo.php') /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt:11
    0.0136    1496512   3. require_once('/Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo-run.php') /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo.php:14
    0.0228    2180616   4. Acquia\Blt\Robo\Config\ConfigInitializer->initialize() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo-run.php:29
    0.0228    2180616   5. Acquia\Blt\Robo\Config\ConfigInitializer->setSite() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php:84
    0.0228    2180616   6. Acquia\Blt\Robo\Config\DefaultConfig->setSite() /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php:58
```

**Comment by mikemadison13** [comment]
this is a known issue and has been fixed in the 9.x-dev branch of BLT. in the interim, you can apply a fix without updating BLT by adding the following to your composer.json and updating the package.

```
"consolidation/robo": "~1.2.4"
```

then run:

```
$ composer update consolidation/robo --with-all-dependencies
```
