### ISSUE TITLE
BLT 8.9.14 not working with Robo 1.3.0

### ISSUE THREAD

**Issue by christopher-hopper** [acquia/blt#2871]
My system information:
* Operating system type: :penguin: Linux
* Operating system version: Ubuntu
* BLT version: 8.9.14

Output of `blt doctor`:
```
+----------------------+---------------------------------------------------------------+
| Property             | Value                                                         |
+----------------------+---------------------------------------------------------------+
| %paths               |                                                               |
|  - %root             | /var/www/mw/docroot                                           |
|  - %site             | sites/default                                                 |
|  - %modules          | modules                                                       |
|  - %themes           | themes                                                        |
|  - %config-sync      | /var/www/mw/config/default                                    |
|  - %files            | sites/default/files                                           |
|  - %private          | /var/www/mw/files-private                                     |
|  - %temp             | /tmp                                                          |
| admin-theme          | seven                                                         |
| blt-version          | 8.9.14                                                        |
| bootstrap            | Successful                                                    |
| config-sync          | /var/www/mw/config/default                                    |
| db-driver            | mysql                                                         |
| db-hostname          | localhost                                                     |
| db-name              | drupal                                                        |
| db-password          | drupal                                                        |
| db-port              | 3306                                                          |
| db-status            | Connected                                                     |
| db-username          | drupal                                                        |
| dev-desktop-enabled  | false                                                         |
| drupal-settings-file | sites/default/settings.php                                    |
| drupal-version       | 8.4.8                                                         |
| drupal-vm-enabled    | true                                                          |
| drush-alias-files    | /var/www/mw/docroot/../drush/site-aliases/aliases.drushrc.php |
| drush-conf           | /var/www/mw/drush/drushrc.php                                 |
| drush-script         | /var/www/mw/vendor/drush/drush/drush.php                      |
| drush-temp           | /tmp                                                          |
| drush-version        | 8.1.17                                                        |
| files                | sites/default/files                                           |
| install-profile      | quadrupal                                                     |
| local-drushrc        | /var/www/mw/docroot/sites/default/local.drushrc.php           |
| local-settings       | /var/www/mw/docroot/sites/default/settings/local.settings.php |
| modules              | modules                                                       |
| php-bin              | /usr/bin/php                                                  |
| php-conf             | /etc/php/7.1/cli/php.ini                                      |
| php-mysql            | /var/run/mysqld/mysqld.sock                                   |
| php-os               | Linux                                                         |
| private              | /var/www/mw/files-private                                     |
| root                 | /var/www/mw/docroot                                           |
| shell                |                                                               |
| site                 | sites/default                                                 |
| temp                 | /tmp                                                          |
| theme                | melb_water                                                    |
| themes               | themes                                                        |
| uri                  | http://local.mw.com                                           |
| user                 |                                                               |
+----------------------+---------------------------------------------------------------+
+--------------------------+----------------------------------------------------------------------------------+
| Check                    | Outcome                                                                          |
+--------------------------+----------------------------------------------------------------------------------+
| checkDocrootExists       | Found docroot.                                                                   |
| checkCoreExists          | Drupal core exists                                                               |
| checkSettingsFile        | Found settings file.                                                             |
| checkSettingsFile        | BLT settings are not included in settings file.                                  |
| checkLocalSettingsFile   | Found your local settings file.                                                  |
| checkLocalDrushFile      | Found your local drush settings file.                                            |
| checkUri                 | $options['uri'] is set.                                                          |
| checkUriResponse         | Received a response from site http://local.mw.com.                               |
| checkFileSystem:%files   | Public files directory is writable.                                              |
| checkFileSystem:%private | Private files directory does not exist.                                          |
|                          |                                                                                  |
|                          | Create /var/www/mw/files-private.                                                |
|                          | Installing Drupal will create this directory for you.                            |
|                          | Run `blt setup:drupal:install` to install Drupal, or run `blt setup` to run the  |
|                          | entire setup process.                                                            |
|                          | Otherwise, run `mkdir -p /var/www/mw/files-private`.                             |
|                          |                                                                                  |
| checkFileSystem:%temp    | Temporary files directory is writable.                                           |
| checkDbConnection        | Connected to database.                                                           |
| checkDrupalBootstrapped  | Bootstrapped Drupal via drush.                                                   |
| checkDrupalInstalled     | Drupal is installed.                                                             |
| checkCaching:page        | Drupal cache is disabled.                                                        |
| checkCaching:css         | CSS preprocessing is disabled.                                                   |
| checkCaching:js          | JS preprocessing is disabled.                                                    |
| checkComposer:require    | acquia/blt is in composer.json's require object.                                 |
| checkBehat:exists        | tests/behat/local.yml is missing!                                                |
|                          |   Run `blt setup:behat` to generate it from example.local.yml.                   |
| checkProjectYml:keys     | project.yml has no deprecated keys.                                              |
| checkDrupalVm:alias      | drush.aliases.local exists your drush aliases file.                              |
| checkDrupalVm            | Drupal VM is configured correctly.                                               |
| checkSimpleSamlPhp       | /var/www/mw/docroot/../vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-re |
|                          | mote.php is missing. Run `blt simplesamlphp:build:config`.                       |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set                                   |
+--------------------------+----------------------------------------------------------------------------------+

```

When I run this command:
```
blt install-alias
```

I get the following output:
```
[warning] The xDebug extension is loaded. This will significantly decrease performance.
PHP Notice:  Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71
PHP Stack trace:
PHP   1. {main}() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/acquia/blt/bin/blt:0
PHP   2. require_once() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/acquia/blt/bin/blt:11
PHP   3. require_once() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/acquia/blt/bin/blt-robo.php:14
PHP   4. Acquia\Blt\Robo\Blt->run() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/acquia/blt/bin/blt-robo-run.php:42
PHP   5. Robo\Runner->run() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/acquia/blt/src/Robo/Blt.php:235
PHP   6. Acquia\Blt\Robo\Application->run() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/consolidation/robo/src/Runner.php:220
PHP   7. Acquia\Blt\Robo\Application->doRun() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/symfony/console/Application.php:125
PHP   8. Acquia\Blt\Robo\Application->doRunCommand() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/symfony/console/Application.php:206
PHP   9. Acquia\Blt\Robo\Application->doRunCommand() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/acquia/blt/src/Robo/Application.php:29
PHP  10. Consolidation\AnnotatedCommand\AnnotatedCommand->run() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/symfony/console/Application.php:859
PHP  11. Consolidation\AnnotatedCommand\AnnotatedCommand->initialize() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/symfony/console/Command/Command.php:229
PHP  12. Consolidation\AnnotatedCommand\CommandProcessor->initializeHook() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:391
PHP  13. Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php:117
PHP  14. Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:27
PHP  15. Acquia\Blt\Robo\Hooks\InitHook->initialize() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:37
PHP  16. Acquia\Blt\Robo\Config\DefaultConfig->setSiteConfig() /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/acquia/blt/src/Robo/Hooks/InitHook.php:35
PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:71
Stack trace:
#0 /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/acquia/blt/src/Robo/Hooks/InitHook.php(35): Acquia\Blt\Robo\Config\DefaultConfig->setSiteConfig('default')
#1 /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(37): Acquia\Blt\Robo\Hooks\InitHook->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#2 /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#3 /home/chopper/Projects/deloitte/mw/mw-drupal/ in /home/chopper/Projects/deloitte/mw/mw-drupal/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 71
```

## Workaround

*To workaround this problem, I did the following*

> What version of Robo is installed?

```
# composer show consolidation/robo
name     : consolidation/robo
descrip. : Modern task runner
keywords : 
versions : * 1.3.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/consolidation/Robo.git ac563abfadf7cb7314b4e152f2b5033a6c255f6f
dist     : [zip] https://api.github.com/repos/consolidation/Robo/zipball/ac563abfadf7cb7314b4e152f2b5033a6c255f6f ac563abfadf7cb7314b4e152f2b5033a6c255f6f
names    : consolidation/robo, codegyre/robo
```

> Why is Robo required and at what versions?

```
# composer why consolidation/robo
acquia/blt  8.9.14  requires  consolidation/robo (^1.1.0)  

```

> What if I downgrade Robo to an earlier version within the constraints?

```
# composer require "consolidation/robo:>=1.1.0 <1.3.0"
    1/1:	https://asset-packagist.org/p/provider-latest/d406a58c8d5cc464eb20952811db982288ffec3ae036fee0efec875ef41e76e9.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
    1/6:	http://packagist.org/p/provider-latest$a8deaad4281077c3392551a2fe1d4441e208773f5e8701e61edb9e2be7289f9b.json
    2/6:	http://packagist.org/p/provider-2017-10$5e5d9134e5703b44f02c6b891ea96659638088c0cf516020dffbd9122fac85d4.json
    3/6:	http://packagist.org/p/provider-2014$acd36e55aa326bcf2d14c074b338f3e65c81509ae4c3f46ab96ffa0d006cf2bc.json
    4/6:	http://packagist.org/p/provider-2018-04$79e3cd99aa5276dc4fae4db615393897595092a3286663fb6c8dea1882963b0d.json
    5/6:	http://packagist.org/p/provider-2018-01$e8e5bde5406711a0f25b594052e6373b17910bb54eb0ae4e9b35a4cda2d2cefa.json
    6/6:	http://packagist.org/p/provider-2016$37b259695beba32278e444b4f5f3d883b8de3bb0fb6ba8cc731e5afa6d5e3c17.json
    Finished: success: 6, skipped: 0, failure: 0, total: 6
./composer.json has been updated                                                                                       
    1/1:	http://packagist.org/p/provider-latest$b95f39581cbb91111672e7c47a95c42b987047490c2debd588cd1fb293e6d8fb.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)                                                                          
    1/1:	https://codeload.github.com/consolidation/Robo/legacy.zip/273455c0dc1ebb1e9515ae27ad298bec800f1c11
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Package operations: 0 installs, 1 update, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Updating consolidation/robo (1.3.0 => 1.2.4): Loading from cache
Writing lock file
Generating autoload files
```

> Does BLT work now?

```
# vendor/bin/blt install-alias
[warning] The xDebug extension is loaded. This will significantly decrease performance.
The BLT alias is already installed and up to date.

```

*FIXED!*

So it looks like `acquia/blt:8.9.14` doesn't work with `consolidation/robo:1.3.0`. Perhaps a new version constraint is needed, more like the one I've forced into my project?

**Comment by mikemadison13** [comment]
@christopher-hopper this should be fixed in the dev version of BLT 8.9. Essentially you need to pin the version of robo. see https://github.com/acquia/blt/pull/2837

**Comment by greylabel** [comment]
@mikemadison13 Can you cut a new release. This is a pretty major bug fix?

**Comment by mikemadison13** [comment]
we are trying to get the 9.1 release out the door @greylabel but we will get 8.9 out ASAP as well!

**Comment by brooke-heaton** [comment]
@christopher-hopper's fix worked for me:

`composer require "consolidation/robo:>=1.1.0 <1.3.0"`
