### ISSUE TITLE
PHP Fatal error:  Uncaught PHP_CodeSniffer_Exception: Referenced sniff "Drupal" does not exist

### ISSUE THREAD

**Issue by seanhamlin** [acquia/blt#2877]
My system information:
* Operating system type: TravisCI
* BLT version: 9.1-alpha1

When I run this command:
```
TravisCI build
```

I get the following output:
```
0.00s$ source ${BLT_DIR}/scripts/travis/setup_project
set +v
$ source ${BLT_DIR}/scripts/travis/run_tests
blt validate:all
> tests:composer:validate
Validating composer.json and composer.lock...
> tests:php:lint
Linting PHP files...
Iterating over fileset files.php.custom.modules...
Iterating over fileset files.php.tests...
> tests:phpcs:sniff:all
[ExecStack] /home/travis/build/Baxter-Healthcare/Corvette/vendor/bin/phpcs
[ExecStack] Running /home/travis/build/Baxter-Healthcare/Corvette/vendor/bin/phpcs in /home/travis/build/Baxter-Healthcare/Corvette
PHP Fatal error:  Uncaught PHP_CodeSniffer_Exception: Referenced sniff "Drupal" does not exist in /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1167
Stack trace:
#0 /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/CodeSniffer.php(780): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/home/travis/bu...', 0)
#1 /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/CodeSniffer.php(578): PHP_CodeSniffer->processRuleset('/home/travis/bu...')
#2 /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(956): PHP_CodeSniffer->initStandard(Array, Array, Array)
#3 /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(113): PHP_CodeSniffer_CLI->process()
#4 /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/scripts/phpcs(25): PHP_CodeSniffer_CLI->runphpcs()
#5 {main}
  thrown in /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 1167
Fatal error: Uncaught PHP_CodeSniffer_Exception: Referenced sniff "Drupal" does not exist in /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1167
Stack trace:
#0 /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/CodeSniffer.php(780): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/home/travis/bu...', 0)
#1 /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/CodeSniffer.php(578): PHP_CodeSniffer->processRuleset('/home/travis/bu...')
#2 /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(956): PHP_CodeSniffer->initStandard(Array, Array, Array)
#3 /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(113): PHP_CodeSniffer_CLI->process()
#4 /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/scripts/phpcs(25): PHP_CodeSniffer_CLI->runphpcs()
#5 {main}
  thrown in /home/travis/build/Baxter-Healthcare/Corvette/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 1167
[ExecStack]  Exit code 255  Time 0.041s
 Attempt to fix violations automatically via PHPCBF? (y/n) 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

```

And I expected this to happen:

The Drupal CS rules to be found. This worked in BLT 8.9.x.

**Comment by seanhamlin** [comment]
FWIW, this runs locally

```
$ blt tests:phpcs:sniff:all
[ExecStack] /Users/sean.hamlin/Sites/Corvette/vendor/bin/phpcs
[ExecStack] Running /Users/sean.hamlin/Sites/Corvette/vendor/bin/phpcs in /Users/sean.hamlin/Sites/Corvette
.W......W...............................WW.......W....W..W..  60 / 181 (33%)
..WW........W..W..........WW......W..........W.....W........ 120 / 181 (66%)
W...WW................W..WW..W.WWWW..........W..........WWWW 180 / 181 (99%)
.

```

**Comment by seanhamlin** [comment]
So I checked https://github.com/acquia/blt/blob/9.x/composer.json#L28 and indeed BLT does require `drupal/coder`. However in TravisCI, when `composer install` runs, I do not see `drupal/coder` being downloaded. Weird.

**Comment by seanhamlin** [comment]
So, as it turns out, clearing TravisCI's cache fixed this issue. This should be in the docs somewhere.

```
blt validate:all
> tests:composer:validate
Validating composer.json and composer.lock...
> tests:php:lint
Linting PHP files...
Iterating over fileset files.php.custom.modules...
Iterating over fileset files.php.tests...
> tests:phpcs:sniff:all
[ExecStack] /home/travis/build/Baxter-Healthcare/Corvette/vendor/bin/phpcs
[ExecStack] Running /home/travis/build/Baxter-Healthcare/Corvette/vendor/bin/phpcs in /home/travis/build/Baxter-Healthcare/Corvette
W..........W..............WW...............................W  60 / 181 (33%)
W.........W.WW...W........W........W....W.W.W........WW..WW. 120 / 181 (66%)
WW.W....W..........W......W.WWW.......W.W..W.............W.. 180 / 181 (99%)
.
```

**Comment by ba66e77** [comment]
Good catch, @seanhamlin. Would you be willing to write up your experience and submit a PR for the docs?

**Comment by ba66e77** [comment]
I've added a section on how to clear TravisCI cache to the [FAQ](http://blt.readthedocs.io/en/latest/FAQ/).

**Comment by debdatta-sarkar** [comment]
Hi @ba66e77 , @seanhamlin : Will you please help me with this - https://github.com/acquia/blt/issues/3261?
