### ISSUE TITLE
Random Behat Failures

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3224]
My system information:
* Operating system type: Mac OS / Drupal VM
* Operating system version: [replace]
* BLT version: 9.2.1

Output of `blt doctor`:
```
blt doctor
+---------------------------+-------------------------------------------------------+
| Property                  | Value                                                 |
+---------------------------+-------------------------------------------------------+
| %paths.%root              | /var/www/<projet>/docroot                               |
| %paths.%site              | sites/default                                         |
| %paths.%modules           | sites/all/modules                                     |
| %paths.%themes            | sites/all/themes                                      |
| %paths.%config-sync       | /var/www/<projet>/config/default                        |
| %paths.%files             | sites/default/files                                   |
| %paths.%temp              | /tmp                                                  |
| %paths.%private           | /var/www/<projet>/files-private                         |
| admin-theme               | seven                                                 |
| alias-searchpaths.0       | /var/www/<projet>/drush/sites                           |
| blt-version               | 9.2.1                                                 |
| bootstrap                 | Successful                                            |
| composer-version          | Composer version 1.6.5 2018-05-04 11:44:59            |
| config-sync               | /var/www/<projet>/config/default                        |
| db-driver                 | mysql                                                 |
| db-hostname               | localhost                                             |
| db-name                   | drupal                                                |
| db-password               | drupal                                                |
| db-port                   | 3306                                                  |
| db-status                 | Connected                                             |
| db-username               | drupal                                                |
| drupal-settings-file      | sites/default/settings.php                            |
| drupal-version            | 8.6.3                                                 |
| drush-alias-files.0       | /var/www/<project>/drush/sites/default.site.yml          |
| drush-alias-files.1       | /var/www/<project>/drush/sites/demo.site.yml             |
| drush-alias-files.2       | /var/www/<project>/drush/sites/<project>-ace.site.yml       |
| drush-alias-files.3       | /var/www/<projet>/drush/sites/<project>-acsf-dev.site.yml  |
| drush-alias-files.4       | /var/www/<project>/drush/sites/<project>-acsf-test.site.yml |
| drush-alias-files.5       | /var/www/<project>/drush/sites/<project>-acsf.site.yml      |
| drush-alias-files.6       | /var/www/<project>/drush/sites/<project>.site.yml           |
| drush-cache-directory     | /home/vagrant/.drush/cache                            |
| drush-conf.0              | /var/www/<project>/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/<project>/drush/drush.yml                       |
| drush-script              | /var/www/<project>/vendor/bin/drush                      |
| drush-temp                | /tmp                                                  |
| drush-version             | 9.5.2                                                 |
| files                     | sites/default/files                                   |
| install-profile           | <project>                                                |
| modules                   | sites/all/modules                                     |
| php-bin                   | /usr/bin/php7.1                                       |
| php-conf.0                | /etc/php/7.1/cli/php.ini                              |
| php-os                    | Linux                                                 |
| private                   | /var/www/<project>/files-private                         |
| root                      | /var/www/<project>/docroot                               |
| site                      | sites/default                                         |
| stacks.drupal-vm.inited   | true                                                  |
| stacks.dev-desktop.inited | false                                                 |
| temp                      | /tmp                                                  |
| theme                     | <project>                                       |
| themes                    | sites/all/themes                                      |
| uri                       | default                                               |
+---------------------------+-------------------------------------------------------+
```

When I run this command:
```
blt tests:behat
```

I get the following output:
```
DMore\ChromeDriver\StreamReadException in /mnt/tmp/local.prod/source/vendor/dmore/chrome-mink-driver/src/DevToolsConnection.php:93
      Stack trace:
      #0 /mnt/tmp/local.prod/source/vendor/dmore/chrome-mink-driver/src/DevToolsConnection.php(75): DMore\ChromeDriver\DevToolsConnection->waitFor(Object(Closure))
      #1 /mnt/tmp/local.prod/source/vendor/dmore/chrome-mink-driver/src/ChromePage.php(42): DMore\ChromeDriver\DevToolsConnection->send('Page.navigate', Array)
      #2 /mnt/tmp/local.prod/source/vendor/dmore/chrome-mink-driver/src/ChromeDriver.php(175): DMore\ChromeDriver\ChromePage->visit('http://127.0.0....')
      #3 /mnt/tmp/local.prod/source/vendor/behat/mink/src/Session.php(148): DMore\ChromeDriver\ChromeDriver->visit('http://127.0.0....')
      #4 /mnt/tmp/local.prod/source/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/DrupalContext.php(342): Behat\Mink\Session->visit('http://127.0.0....')
      #5 [internal function]: Drupal\DrupalExtension\Context\DrupalContext->createTerm('brand', 'BrandName')
      #6 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(103): call_user_func_array(Array, Array)
      #7 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(59): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #8 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(140): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #9 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(96): Behat\Testwork\Call\CallCenter->handleCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #10 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(125): Behat\Testwork\Call\CallCenter->makeCall(Object(Behat\Behat\Definition\Call\DefinitionCall))
      #11 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeStepTester.php(73): Behat\Behat\Tester\Runtime\RuntimeStepTester->testDefinition(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), Object(Behat\Behat\Definition\SearchResult), false)
      #12 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableStepTester.php(74): Behat\Behat\Tester\Runtime\RuntimeStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #13 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/TickingStepTester.php(59): Behat\Behat\Hook\Tester\HookableStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #14 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingStepTester.php(73): Behat\Behat\EventDispatcher\Tester\TickingStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #15 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/Tester/StepContainerTester.php(59): Behat\Behat\EventDispatcher\Tester\EventDispatchingStepTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\StepNode), false)
      #16 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeScenarioTester.php(76): Behat\Behat\Tester\StepContainerTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #17 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(74): Behat\Behat\Tester\Runtime\RuntimeScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #18 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(103): Behat\Behat\Hook\Tester\HookableScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #19 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php(69): Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->test(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #20 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(84): Behat\Behat\Tester\Runtime\IsolatingScenarioTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
      #21 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
      #22 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(71): Behat\Behat\Hook\Tester\HookableFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
      #23 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
      #24 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
      #25 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(72): Behat\Testwork\Hook\Tester\HookableSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
      #26 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
      #27 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(70): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
      #28 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
      #29 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test(Array, false)
      #30 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
      #31 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #32 /mnt/tmp/local.prod/source/vendor/symfony/console/Command/Command.php(255): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #33 /mnt/tmp/local.prod/source/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #34 /mnt/tmp/local.prod/source/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #35 /mnt/tmp/local.prod/source/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #36 /mnt/tmp/local.prod/source/vendor/symfony/console/Application.php(148): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      #37 /mnt/tmp/local.prod/source/vendor/behat/behat/bin/behat(34): Symfony\Component\Console\Application->run()
      #38 {main}
```

And I expected this to happen:

This seems to be a resurgence of https://github.com/acquia/blt/issues/2138

As far as I can tell, it happens randomly. The same code can be run (fail) re-run (pass) re-run (fail) with little or no predictability. I've tried updating both dmore/chrome-mink-driver and dmore/behat-chrome-extension and nothing updates.

dmore/behat-chrome-extension:  1.2.0
dmore/chrome-mink-driver: 2.6.4

**Comment by mikemadison13** [comment]
This may be related to https://gitlab.com/DMore/behat-chrome-extension/issues/11

**Comment by mikemadison13** [comment]
To work around this issue, I have created a custom step in the FeatureContext file:

```
/** @When I accept confirmation dialogs */
  public function confirm() {
    $this->getSession()->evaluateScript('window.confirm = function(){return true;}');
  }
```

And added a step to scenarios that have been failing that calls this:
```
Given I accept confirmation dialogs
```

And the issues seem to have gone away. This is a pretty significant hack but it does seem to work.

**Comment by dpagini** [comment]
I get this locally too... very randomly. Much more in line with what this guy is reporting...

https://stackoverflow.com/questions/54748481/how-to-fix-behat-dmore-chromedriver-streamreadexception-in-behat-script

**Comment by rjgwiz** [comment]
@mikemadison13 @dpagini I've found this to be a timeout issue due to resources. The more programs I have open, the more I encounter it.

I have two local patches that basically prevent this error 100% of the time. One for `drupal-extension` and one for `chrome-mink-driver`. The `drupal-extension` patch basically increases the timeout threshold in two `$this-getSession()->wait()` calls. The `chrome-mink-driver` deals with how `DevToolsConnections` handles timeouts.

If you want more info, let me know. I can dig up the patch. I will warn that it's a bit quick and dirty but both are small patches.

Upgrading `chrome-mink-driver` negates the need for the patches, if I remember correctly. 

I also remember needing to increase my AJAX timeout at some point. https://github.com/jhedstrom/drupalextension/issues/486 discussed a new `ajax_timeout` setting in `behat.yml` (or any behat config file). At the time (last fall maybe) the drupalextension upgrade was blocked because using `ajax_timeout` requires using `Drupal\MinkExtension` instead of `Behat\MinkExtension`, and BLT's `BehatCheck` errors if `Behat\MinkExtension` is missing

**Comment by jeevanbhushetty** [comment]
Any updates on this issue? I am still facing this issue randomly for on Travis.

**Comment by AndreBaumeier** [comment]
@rjgwiz can you post the patches somewhere?

**Comment by rjgwiz** [comment]
@AndreBaumeier I'll try to post it this weekend. I need to recreate on my home machine... Current company policy won't let me share code from work machines

**Comment by rjgwiz** [comment]
@AndreBaumeier attached are the patches. They are quick and dirty. They work for me, maybe someone else can clean them up.

I apply these against `dmore/chrome-mink-driver`:`2.7.0` and `drupal/drupal-extension`:`v3.4.1`

[behat-patches.tar.gz](https://github.com/acquia/blt/files/4144795/behat-patches.tar.gz)

**Comment by AndreBaumeier** [comment]
@rjgwiz thank you

**Comment by mpdude** [comment]
To make it more easily accessible, @rjgwiz 's patch against `ChromeDriver` as follows:

```diff
diff --git a/src/DevToolsConnection.php b/src/DevToolsConnection.php
index 794ff63..15b4d4f 100644
--- a/src/DevToolsConnection.php
+++ b/src/DevToolsConnection.php
@@ -61,14 +61,26 @@ abstract class DevToolsConnection
     protected function waitFor(callable $is_ready)
     {
         $data = [];
+        $success = false;
+        $mininimum_tries = 10;
+        $current_try = 0;
         while (true) {
-            try {
-                $response = $this->client->receive();
-            } catch (ConnectionException $exception) {
-                $message = $exception->getMessage();
-                $state = json_decode(substr($message, strpos($message, '{')), true);
-                throw new StreamReadException($state['eof'], $state['timed_out'], $state['blocked']);
+            do {
+                try {
+                    $response = $this->client->receive();
+                    $success = true;
+                } catch (ConnectionException $exception) {
+                    $message = $exception->getMessage();
+                    $state = json_decode(substr($message, strpos($message, '{')), true);
+                    if ($current_try>=$mininimum_tries) {
+                        throw new StreamReadException($state['eof'], $state['timed_out'], $state['blocked']);
+                    }
+                    $current_try++;
+                    sleep(3);
+                }
             }
+            while ($current_try<$mininimum_tries && !$success);
+
             if (is_null($response)) {
                 return null;
             }
````

**Comment by mpdude** [comment]
Seeing this as well, but the above patch does not help. We're getting stuck and finally get the exception in the same scenario every time, but only if we execute the whole feature. Running the scenario in isolation works.

What should I look at? Is there something like a log in Chrome That would help?

**Comment by mxr576** [comment]
https://github.com/Textalk/websocket-php/issues/64 could be related, but installing the latest version of  the library did not solve the issue either.
