### ISSUE TITLE
blt:init:settings fails in CI docker container

### ISSUE THREAD

**Issue by bkildow** [acquia/blt#3276]
My system information:
* Operating system type: Linux
* BLT version: 9.2

Output of `blt doctor`:
```
+---------------------------+--------------------------------------------+
| Property                  | Value                                      |
+---------------------------+--------------------------------------------+
| %paths.%root              | /var/www/docroot                           |
| %paths.%site              | sites/default                              |
| %paths.%modules           | sites/all/modules                          |
| %paths.%themes            | sites/all/themes                           |
| %paths.%config-sync       | /var/www/config/default                    |
| alias-searchpaths.0       | /var/www/drush/sites                       |
| blt-version               | 9.2.0                                      |
| composer-version          | Composer version 1.6.3 2018-01-31 16:28:17 |
| config-sync               | /var/www/config/default                    |
| drupal-settings-file      | sites/default/settings.php                 |
| drupal-version            | 8.6.2                                      |
| drush-alias-files.0       | /var/www/drush/sites/awn.site.yml          |
| drush-alias-files.1       | /var/www/drush/sites/self.site.yml         |
| drush-cache-directory     | /home/docker/.drush/cache                  |
| drush-conf.0              | /var/www/vendor/drush/drush/drush.yml      |
| drush-conf.1              | /var/www/drush/drush.yml                   |
| drush-script              | /var/www/vendor/bin/drush                  |
| drush-temp                | /tmp                                       |
| drush-version             | 9.5.2                                      |
| modules                   | sites/all/modules                          |
| php-bin                   | /usr/local/bin/php                         |
| php-conf.1                | false                                      |
| php-os                    | Linux                                      |
| root                      | /var/www/docroot                           |
| site                      | sites/default                              |
| stacks.drupal-vm.inited   | false                                      |
| stacks.dev-desktop.inited | false                                      |
| themes                    | sites/all/themes                           |
| uri                       | default                      
```

When I run this command:
```
blt blt:init:settings -vvv
```

I get the following output:
```
[debug] Drupal VM is not initialized.
[Filesystem\FilesystemStack] _copy ["/var/www/blt/example.local.blt.yml","/var/www/blt/local.blt.yml"]
[Filesystem\FilesystemStack] _chmod ["/var/www/docroot/sites/default",511]
Hash salt already exists.
[Filesystem\FilesystemStack]  Failed to chmod file "/var/www/docroot/sites/default". 
[Filesystem\FilesystemStack]  Failed to chmod file "/var/www/docroot/sites/default". 
[Filesystem\FilesystemStack]  Exit code 1 

Warning: file(/var/www/docroot/sites/default/settings/local.settings.php): failed to open stream: No such file or directory in /var/www/vendor/acquia/blt/src/Robo/Config/BltConfig.php on line 20

Fatal error: Uncaught TypeError: Argument 1 passed to Dflydev\DotAccessData\Data::__construct() must be of the type array or null, boolean given, called in /var/www/vendor/grasmash/yaml-expander/src/Expander.php on line 51 and defined in /var/www/vendor/dflydev/dot-access-data/src/Dflydev/DotAccessData/Data.php:28
Stack trace:
#0 /var/www/vendor/grasmash/yaml-expander/src/Expander.php(51): Dflydev\DotAccessData\Data->__construct(false)
#1 /var/www/vendor/acquia/blt/src/Robo/Config/BltConfig.php(20): Grasmash\YamlExpander\Expander::expandArrayProperties(false, Array)
#2 /var/www/vendor/acquia/blt/src/Robo/Commands/Setup/SettingsCommand.php(123): Acquia\Blt\Robo\Config\BltConfig->expandFileProperties('/var/www/docroo...')
#3 [internal function]: Acquia\Blt\Robo\Commands\Setup\SettingsCommand->generateSiteConfigFiles(Array)
#4 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)
#5 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Conso in /var/www/vendor/dflydev/dot-access-data/src/Dflydev/DotAccessData/Data.php on line 28
```

I'm seeing this when running in CI in a docker container. It works locally, and I'm having a hard time debugging this in CI. It looks like `local.settings.php` is not getting generated, and I'm not sure why /var/www/docroot/sites/default is trying to be chmoded to 511 (and failing). Anyone know how I can go about debugging this?

**Comment by bkildow** [comment]
This turned out to be a docker volume mounting permission issue. chowning to the correct user before running fixed my issue.
