### ISSUE TITLE
Cannot find `example.local.blt.yml`

### ISSUE THREAD

**Issue by DeepCreekLake** [acquia/blt#3283]
My system information:
* Operating system type: macOS High Sierra
* Operating system version: 10.13.6
* BLT version: 9.2.1

I am trying to add blt to an existing project. I used composer to install blt.

Output of `blt doctor`:
```
$ blt doctor
+---------------------------+----------------------------------------------------------+
| Property                  | Value                                                    |
+---------------------------+----------------------------------------------------------+
| blt-version               | 9.2.1                                                    |
| composer-version          | Composer version 1.7.3 2018-11-01 10:05:06               |
| root                      | /Users/frank/Sites/devdesktop/sandbox/docroot         |
| stacks.drupal-vm.inited   | false                                                    |
| stacks.dev-desktop.inited | DDSETTINGS>                                              |
|                           | // Please don't edit anything between <DDSETTINGS> tags. |
|                           | // This section is autogenerated by Acquia Dev Desktop.  |
|                           | if (isset($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR']) && |
|                           | file_exists($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . |
|                           | '/cld_prod_sandbox_dev_default.inc')) {                   |
|                           |   require $_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] .   |
|                           | '/cld_prod_sandbox_dev_default.inc';                      |
|                           | }                                                        |
|                           | // </DDSETTINGS>                                         |
|                           |                                                          |
|                           | $config_directories['vcs'] = $app_root . '/../config/' . |
|                           | basename($site_path);                                    |
|                           |                                                          |
| uri                       | default                                                  |
+---------------------------+----------------------------------------------------------+
+------------------------------------------+--------------------------------------------------------------+
| Check                                    | Problem                                                      |
+------------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkLocalConfig:exists       | tests/behat/local.yml is missing!                            |
|                                          |   Run `blt tests:behat:init:config` to generate it from      |
|                                          | example.local.yml.                                           |
| ComposerCheck:checkPrestissimo:plugins   | hirak/prestissimo plugin for composer is not installed.      |
|                                          |   Run composer global require                                |
|                                          | hirak/prestissimo to install it.                             |
|                                          |   This will improve composer install/update performance by   |
|                                          | parallelizing the download of dependency information.        |
| ConfigCheck:checkGitConfig               | Git repositories are not defined in blt.yml.                 |
|                                          |   Add values for git.remotes to blt.yml to enabled automated |
|                                          | deployment.                                                  |
| DbCheck:checkRequiredKeys                | drush status is missing the 'db-hostname' key.               |
| DevDesktopCheck:checkDevDesktop          | DevDesktop usage is enabled, but                             |
|                                          | $DEVDESKTOP_DRUPAL_SETTINGS_DIR is not set in your           |
|                                          | environmental variables.                                     |
|                                          |                                                              |
|                                          | Add `export                                                  |
|                                          | DEVDESKTOP_DRUPAL_SETTINGS_DIR="$HOME/.acquia/DevDesktop/Dru |
|                                          | palSettings"` to ~/.bash_profile or equivalent for your      |
|                                          | system.`                                                     |
| DrupalCheck:checkDrupalBootstrapped      | Could not bootstrap Drupal via drush without alias.          |
| DrupalCheck:checkDrupalInstalled         | Drupal is not installed.                                     |
|                                          |                                                              |
|                                          | Run `blt drupal:install` to install Drupal locally.          |
| FileSystemCheck:checkFileSystem:%files   | Public files directory is not set.                           |
| FileSystemCheck:checkFileSystem:%private | Private files directory is not set.                          |
| FileSystemCheck:checkFileSystem:%temp    | Temporary files directory is not set.                        |
| NodeCheck:checkNodeVersionFileExists     | Neither .nvmrc nor .node-version file found in repo root.    |
| PhpCheck:checkPhpDateTimezone            | PHP setting for date.timezone is not set.                    |
|                                          |   Define date.timezone in                                    |
| SettingsFilesCheck:blt-settings          | BLT settings are not included in settings file.              |
| SettingsFilesCheck:local-settings        | Could not find local settings file.                          |
|                                          | Your local settings file should exist at                     |
|                                          | .../docroot/sites/defau |
|                                          | lt/settings/local.settings.php.                              |
| WebUriCheck:checkUri                     | Site URI is not set                                          |
|                                          | Is options.uri set correctly in                              |
|                                          | .../docroot/sites/defau |
|                                          | lt/local.drush.yml?                                          |
+------------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues. 
```

When I run this command by following this [link](https://blt.readthedocs.io/en/latest/onboarding/):
```
blt blt:init:settings
```

I get the following output:
```
$ blt blt:init:settings -vvv
[debug] Drupal VM is not initialized.
[Filesystem\FilesystemStack] _copy ["/Users/frank/Sites/devdesktop/sandbox-dev/blt/example.local.blt.yml","/Users/frank/Sites/devdesktop/sandbox-dev/blt/local.blt.yml"]
[Filesystem\FilesystemStack]  Failed to copy "/Users/frank/Sites/devdesktop/sandbox-dev/blt/example.local.blt.yml" because file does not exist. 
[Filesystem\FilesystemStack]  Failed to copy "/Users/frank/Sites/devdesktop/sandbox-dev/blt/example.local.blt.yml" because file does not exist. 
[Filesystem\FilesystemStack]  Exit code 1 
[error]  Unable to create blt/local.blt.yml/. 
0.114s total time elapsed.

```

And I expected this to happen: The step above could generate docroot/sites/default/settings/local.settings.php and docroot/sites/default/local.drush.yml.

I do not know why `example.local.blt.yml` is not there. I am using Acquia DevDesktop on my local.

Please advise.

Thanks!

**Comment by mikemadison13** [comment]
@DeepCreekLake a few things to try:

Can you please open your vendor folder and go to vendor/acquia/blt/template/blt and see if you see the example.local.blt.yml file there?

Also, can you try to run blt setup instead of blt blt:init:settings? 

It's been a long while since I tried to use dev desktop with blt, so I'm not sure exactly what issue we're hitting here but we'll try to get to the bottom of it!

**Comment by DeepCreekLake** [comment]
Hello Mike,

Yes there is a `example.local.blt.yml` file under `vendor/acquia/blt/template/blt`. I copied it to `blt` and the issue in my previous comment could be gone.

However, a new issue showed up during `blt setup` was running:
```
$ blt setup -vvv
[debug] Drupal VM is not initialized.
Setting up local environment for site default.
> source:build
[debug] Verifying that Drupal is installed...
[Robo\Common\ProcessExecutor] Running '/Users/frank/Sites/devdesktop/sandbox-dev/vendor/bin/drush' @ sqlq "SHOW TABLES LIKE 'config'" --uri=default in /Users/frank/Sites/devdesktop/sandbox-dev/docroot

                                                                               
  Command @ was not found. Drush was unable to query the database. As a resul  
  t, many commands are unavailable. Re-run your command with --debug to see r  
  elevant log messages.                                                        
                                                                               

> tests:behat:init:config
> source:build:composer
[Exec] Running export COMPOSER_EXIT_ON_PATCH_FAILURE=1; composer install --ansi --no-interaction in /Users/frank/Sites/devdesktop/sandbox-dev
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Component/Utility/Timer.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Component/Utility/Unicode.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/Database/Database.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/DrupalKernel.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/DrupalKernelInterface.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/Site/Settings.php" which does not appear to be a file nor a folder
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
PHP CodeSniffer Config installed_paths delete
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Component/Utility/Timer.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Component/Utility/Unicode.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/Database/Database.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/DrupalKernel.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/DrupalKernelInterface.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/Site/Settings.php" which does not appear to be a file nor a folder
> DrupalComposer\DrupalScaffold\Plugin::scaffold
  - .csslintrc (https://cgit.drupalcode.org/drupal/plain/.csslintrc?h=8.6.2): Downloading (100%)         
  - .editorconfig (https://cgit.drupalcode.org/drupal/plain/.editorconfig?h=8.6.2): Downloading (100%)         
  - .eslintignore (https://cgit.drupalcode.org/drupal/plain/.eslintignore?h=8.6.2): Downloading (100%)         
  - .eslintrc.json (https://cgit.drupalcode.org/drupal/plain/.eslintrc.json?h=8.6.2):Downloading (100%)         )
  - .gitattributes (https://cgit.drupalcode.org/drupal/plain/.gitattributes?h=8.6.2):Downloading (100%)         )
  - .ht.router.php (https://cgit.drupalcode.org/drupal/plain/.ht.router.php?h=8.6.2):Downloading (100%)         )
  - .htaccess (https://cgit.drupalcode.org/drupal/plain/.htaccess?h=8.6.2): Downloading (100%)         
  - index.php (https://cgit.drupalcode.org/drupal/plain/index.php?h=8.6.2): Downloading (100%)         
  - robots.txt (https://cgit.drupalcode.org/drupal/plain/robots.txt?h=8.6.2): Downloading (100%)         
  - sites/default/default.services.yml (https://cgit.drupalcode.org/drupal/plain/sites/default/default.services.yml?h=8.6.2): Downloading (100%)         
  - sites/default/default.settings.php (https://cgit.drupalcode.org/drupal/plain/sites/default/default.settings.php?h=8.6.2): Downloading (100%)         
  - sites/development.services.yml (https://cgit.drupalcode.org/drupal/plain/sites/development.services.yml?h=8.6.2): Downloading (100%)         
  - sites/example.settings.local.php (https://cgit.drupalcode.org/drupal/plain/sites/example.settings.local.php?h=8.6.2): Downloading (100%)         
  - sites/example.sites.php (https://cgit.drupalcode.org/drupal/plain/sites/example.sites.php?h=8.6.2): Downloading (100%)         
  - update.php (https://cgit.drupalcode.org/drupal/plain/update.php?h=8.6.2): Downloading (100%)         
  - web.config (https://cgit.drupalcode.org/drupal/plain/web.config?h=8.6.2): Downloading (100%)         
[Exec] Done in 3.312s
> blt:init:git-hooks
Installing pre-commit git hook...
[Filesystem\FilesystemStack] mkdir ["/Users/frank/Sites/devdesktop/sandbox-dev/.git/hooks"]
[Filesystem\FilesystemStack] remove ["/Users/frank/Sites/devdesktop/sandbox-dev/.git/hooks/pre-commit"]
[Filesystem\FilesystemStack] symlink ["../../vendor/acquia/blt/scripts/git-hooks/pre-commit","/Users/frank/Sites/devdesktop/sandbox-dev/.git/hooks/pre-commit"]
Installing commit-msg git hook...
[Filesystem\FilesystemStack] mkdir ["/Users/frank/Sites/devdesktop/sandbox-dev/.git/hooks"]
[Filesystem\FilesystemStack] remove ["/Users/frank/Sites/devdesktop/sandbox-dev/.git/hooks/commit-msg"]
[Filesystem\FilesystemStack] symlink ["../../vendor/acquia/blt/scripts/git-hooks/commit-msg","/Users/frank/Sites/devdesktop/sandbox-dev/.git/hooks/commit-msg"]
> blt:init:settings
Hash salt already exists.
[debug] Switching site context to sandbox.dev.dd.
[Filesystem\FilesystemStack] _chmod ["/Users/frank/Sites/devdesktop/sandbox-dev/docroot/sites/sandbox.dev.dd",511]
[Filesystem\FilesystemStack] _chmod ["/Users/frank/Sites/devdesktop/sandbox-dev/docroot/sites/sandbox.dev.dd/settings.php",511]
[Filesystem\FilesystemStack]  Failed to chmod file "/Users/frank/Sites/devdesktop/sandbox-dev/docroot/sites/sandbox.dev.dd/settings.php". 
[Filesystem\FilesystemStack]  Failed to chmod file "/Users/frank/Sites/devdesktop/sandbox-dev/docroot/sites/sandbox.dev.dd/settings.php". 
[Filesystem\FilesystemStack]  Exit code 1 

Warning: file(/Users/frank/Sites/devdesktop/sandbox-dev/docroot/sites/sandbox.dev.dd/settings/local.settings.php): failed to open stream: No such file or directory in /Users/frank/Sites/devdesktop/sandbox-dev/vendor/acquia/blt/src/Robo/Config/BltConfig.php on line 20

Fatal error: Uncaught TypeError: Argument 1 passed to Dflydev\DotAccessData\Data::__construct() must be of the type array or null, boolean given, called in /Users/frank/Sites/devdesktop/sandbox-dev/vendor/grasmash/yaml-expander/src/Expander.php on line 51 and defined in /Users/frank/Sites/devdesktop/sandbox-dev/vendor/dflydev/dot-access-data/src/Dflydev/DotAccessData/Data.php:28
Stack trace:
#0 /Users/frank/Sites/devdesktop/sandbox-dev/vendor/grasmash/yaml-expander/src/Expander.php(51): Dflydev\DotAccessData\Data->__construct(false)
#1 /Users/frank/Sites/devdesktop/sandbox-dev/vendor/acquia/blt/src/Robo/Config/BltConfig.php(20): Grasmash\YamlExpander\Expander::expandArrayProperties(false, Array)
#2 /Users/frank/Sites/devdesktop/sandbox-dev/vendor/acquia/blt/src/Robo/Commands/Setup/SettingsCommand.php(123): Acquia\Blt\Robo\Config\BltConfig->expandFileProperties('/Users/frank/Si...')
#3 [internal function]: Acquia\Blt\Robo\Commands\Setup\SettingsCommand->generateSiteConfigFiles(Array)
#4 /Users/frank/Sites/devdesktop/sandbox-dev/ in /Users/frank/Sites/devdesktop/sandbox-dev/vendor/dflydev/dot-access-data/src/Dflydev/DotAccessData/Data.php on line 28
```

The `/Users/frank/Sites/devdesktop/sandbox-dev/docroot/sites/sandbox.dev.dd/settings.php` could not be chmod to 551. Then I manually chmod the file to 511 and ran `blt setup` again. But the `chmod 511` issue was still there.

Could you please advise?

Thanks,

Peiyuan

**Comment by mikemadison13** [comment]
@DeepCreekLake sorry for the delayed response. it might make sense to sudo chmod -R 775 your entire directory just to try and avoid permission issues in general. does that help?

**Comment by DeepCreekLake** [comment]
Hello Mike,

After changing the permission, I still got the same issue:
```
$ sudo chmod -R 775 docroot/
Password: 

$ blt setup -vvv
[debug] Drupal VM is not initialized.
Setting up local environment for site default.
> source:build
[debug] Verifying that Drupal is installed...
[Robo\Common\ProcessExecutor] Running '/Users/frank/Sites/devdesktop/sandbox-dev/vendor/bin/drush' @ sqlq "SHOW TABLES LIKE 'config'" --uri=default in /Users/frank/Sites/devdesktop/sandbox-dev/docroot

                                                                               
  Command @ was not found. Drush was unable to query the database. As a resul  
  t, many commands are unavailable. Re-run your command with --debug to see r  
  elevant log messages.                                                        
                                                                               

> tests:behat:init:config
> source:build:composer
[Exec] Running export COMPOSER_EXIT_ON_PATCH_FAILURE=1; composer install --ansi --no-interaction in /Users/frank/Sites/devdesktop/sandbox-dev
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Component/Utility/Timer.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Component/Utility/Unicode.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/Database/Database.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/DrupalKernel.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/DrupalKernelInterface.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/Site/Settings.php" which does not appear to be a file nor a folder
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
PHP CodeSniffer Config installed_paths delete
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Component/Utility/Timer.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Component/Utility/Unicode.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/Database/Database.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/DrupalKernel.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/DrupalKernelInterface.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/Users/frank/Sites/devdesktop/sandbox-dev/vendor/drupal/core/lib/Drupal/Core/Site/Settings.php" which does not appear to be a file nor a folder
> DrupalComposer\DrupalScaffold\Plugin::scaffold
  - .csslintrc (https://cgit.drupalcode.org/drupal/plain/.csslintrc?h=8.6.2): Downloading (100%)         
  - .editorconfig (https://cgit.drupalcode.org/drupal/plain/.editorconfig?h=8.6.2): Downloading (100%)         
  - .eslintignore (https://cgit.drupalcode.org/drupal/plain/.eslintignore?h=8.6.2): Downloading (100%)         
  - .eslintrc.json (https://cgit.drupalcode.org/drupal/plain/.eslintrc.json?h=8.6.2):Downloading (100%)         )
  - .gitattributes (https://cgit.drupalcode.org/drupal/plain/.gitattributes?h=8.6.2):Downloading (100%)         )
  - .ht.router.php (https://cgit.drupalcode.org/drupal/plain/.ht.router.php?h=8.6.2):Downloading (100%)         )
  - .htaccess (https://cgit.drupalcode.org/drupal/plain/.htaccess?h=8.6.2): Downloading (100%)         
  - index.php (https://cgit.drupalcode.org/drupal/plain/index.php?h=8.6.2): Downloading (100%)         
  - robots.txt (https://cgit.drupalcode.org/drupal/plain/robots.txt?h=8.6.2): Downloading (100%)         
  - sites/default/default.services.yml (https://cgit.drupalcode.org/drupal/plain/sites/default/default.services.yml?h=8.6.2): Downloading (100%)         
  - sites/default/default.settings.php (https://cgit.drupalcode.org/drupal/plain/sites/default/default.settings.php?h=8.6.2): Downloading (100%)         
  - sites/development.services.yml (https://cgit.drupalcode.org/drupal/plain/sites/development.services.yml?h=8.6.2): Downloading (100%)         
  - sites/example.settings.local.php (https://cgit.drupalcode.org/drupal/plain/sites/example.settings.local.php?h=8.6.2): Downloading (100%)         
  - sites/example.sites.php (https://cgit.drupalcode.org/drupal/plain/sites/example.sites.php?h=8.6.2): Downloading (100%)         
  - update.php (https://cgit.drupalcode.org/drupal/plain/update.php?h=8.6.2): Downloading (100%)         
  - web.config (https://cgit.drupalcode.org/drupal/plain/web.config?h=8.6.2): Downloading (100%)         
[Exec] Done in 3.409s
> blt:init:git-hooks
Installing pre-commit git hook...
[Filesystem\FilesystemStack] mkdir ["/Users/frank/Sites/devdesktop/sandbox-dev/.git/hooks"]
[Filesystem\FilesystemStack] remove ["/Users/frank/Sites/devdesktop/sandbox-dev/.git/hooks/pre-commit"]
[Filesystem\FilesystemStack] symlink ["../../vendor/acquia/blt/scripts/git-hooks/pre-commit","/Users/frank/Sites/devdesktop/sandbox-dev/.git/hooks/pre-commit"]
Installing commit-msg git hook...
[Filesystem\FilesystemStack] mkdir ["/Users/frank/Sites/devdesktop/sandbox-dev/.git/hooks"]
[Filesystem\FilesystemStack] remove ["/Users/frank/Sites/devdesktop/sandbox-dev/.git/hooks/commit-msg"]
[Filesystem\FilesystemStack] symlink ["../../vendor/acquia/blt/scripts/git-hooks/commit-msg","/Users/frank/Sites/devdesktop/sandbox-dev/.git/hooks/commit-msg"]
> blt:init:settings
[Filesystem\FilesystemStack] _copy ["/Users/frank/Sites/devdesktop/sandbox-dev/blt/example.local.blt.yml","/Users/frank/Sites/devdesktop/sandbox-dev/blt/local.blt.yml"]
Generating hash salt...
[File\Write] Writing to /Users/frank/Sites/devdesktop/sandbox-dev/salt.txt.
[debug] Switching site context to sandbox.dev.dd.
[Filesystem\FilesystemStack] _chmod ["/Users/frank/Sites/devdesktop/sandbox-dev/docroot/sites/sandbox.dev.dd",511]
[Filesystem\FilesystemStack] _chmod ["/Users/frank/Sites/devdesktop/sandbox-dev/docroot/sites/sandbox.dev.dd/settings.php",511]
[Filesystem\FilesystemStack]  Failed to chmod file "/Users/frank/Sites/devdesktop/sandbox-dev/docroot/sites/sandbox.dev.dd/settings.php". 
[Filesystem\FilesystemStack]  Failed to chmod file "/Users/frank/Sites/devdesktop/sandbox-dev/docroot/sites/sandbox.dev.dd/settings.php". 
[Filesystem\FilesystemStack]  Exit code 1 

Warning: file(/Users/frank/Sites/devdesktop/sandbox-dev/docroot/sites/sandbox.dev.dd/settings/local.settings.php): failed to open stream: No such file or directory in /Users/frank/Sites/devdesktop/sandbox-dev/vendor/acquia/blt/src/Robo/Config/BltConfig.php on line 20

Fatal error: Uncaught TypeError: Argument 1 passed to Dflydev\DotAccessData\Data::__construct() must be of the type array or null, boolean given, called in /Users/frank/Sites/devdesktop/sandbox-dev/vendor/grasmash/yaml-expander/src/Expander.php on line 51 and defined in /Users/frank/Sites/devdesktop/sandbox-dev/vendor/dflydev/dot-access-data/src/Dflydev/DotAccessData/Data.php:28
Stack trace:
#0 /Users/frank/Sites/devdesktop/sandbox-dev/vendor/grasmash/yaml-expander/src/Expander.php(51): Dflydev\DotAccessData\Data->__construct(false)
#1 /Users/frank/Sites/devdesktop/sandbox-dev/vendor/acquia/blt/src/Robo/Config/BltConfig.php(20): Grasmash\YamlExpander\Expander::expandArrayProperties(false, Array)
#2 /Users/frank/Sites/devdesktop/sandbox-dev/vendor/acquia/blt/src/Robo/Commands/Setup/SettingsCommand.php(123): Acquia\Blt\Robo\Config\BltConfig->expandFileProperties('/Users/frank/Si...')
#3 [internal function]: Acquia\Blt\Robo\Commands\Setup\SettingsCommand->generateSiteConfigFiles(Array)
#4 /Users/frank/Sites/devdesktop/sandbox-dev/ in /Users/frank/Sites/devdesktop/sandbox-dev/vendor/dflydev/dot-access-data/src/Dflydev/DotAccessData/Data.php on line 28
```

Could you please advise at your early convenience?  

Thanks and happy holidays!

Peiyuan

**Comment by danepowell** [comment]
You have defined your aliases incorrectly. Drush is trying to run a command with a null alias.

Check your BLT configuration files and make sure all `drush:aliases:*` keys have a value that corresponds to a valid Drush alias. As an example:

```
drush:
  aliases:
    local: foo.local
```

**Comment by danepowell** [comment]
Closing since there has been no response in over a week. Please open a new issue if this is still valid.
