### ISSUE TITLE
BLT commands throw errors after updating drush 9.6.0 dependencies

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#3350]
In testing the upcoming drush 9.6.0 stable release, I updated robo to 1.3.4 since Drush 9.6.0 requires robo ^1.3.0. This appears to break all BLT commands, which has been reported before in #3209, #2078, and #2632 but was never addressed since pinning BLT to robo ^1.2.4 offered a temporary workaround. We will need to fix this to leverage the bugfixes and new functionality in drush 9.6.0 and its dependencies such as dynamic aliases and fixes for `sql:` commands. 

When I run this command:
- Any blt command

I get the following output:
```
~/sites/blted8/docroot develop* 3m 24s
❯blt list

Fatal error: Uncaught Error: Call to a member function set() on null in /var/www/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:70
Stack trace:
#0 /var/www/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(58): Acquia\Blt\Robo\Config\DefaultConfig->setSite('default')
#1 /var/www/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(84): Acquia\Blt\Robo\Config\ConfigInitializer->setSite('default')
#2 /var/www/vendor/acquia/blt/bin/blt-robo-run.php(29): Acquia\Blt\Robo\Config\ConfigInitializer->initialize()
#3 /var/www/vendor/acquia/blt/bin/blt-robo.php(14): require_once('/var/www/vendor...')
#4 /var/www/vendor/acquia/blt/bin/blt(11): require_once('/var/www/vendor...')
#5 {main}
  thrown in /var/www/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70```

And I expected this to happen:
- blt commands to execute successfully

**Comment by alexxed** [comment]
Looks like this does the trick, running tests:
```diff
diff --git a/src/Robo/Config/DefaultConfig.php b/src/Robo/Config/DefaultConfig.php
index 8de0bd84..d0ef1583 100644
--- a/src/Robo/Config/DefaultConfig.php
+++ b/src/Robo/Config/DefaultConfig.php
@@ -67,7 +67,7 @@ public function populateHelperConfig() {
    * @param $site
    */
   public function setSite($site) {
-    $this->config->set('site', $site);
+    $this->set('site', $site);
     if (!$this->get('drush.uri') && $site != 'default') {
       $this->set('drush.uri', $site);
     }
```

**Comment by mikemadison13** [comment]
@alexxed if it does work, it would be awesome if we could get a 10.x PR open to update this, update robo, and update drush.

**Comment by anavarre** [comment]
https://github.com/drush-ops/drush/releases/tag/9.6.0 is out.
