### ISSUE TITLE
Undefined function Acquia\Blt\Robo\Inspector\posix_getpwuid() on Linux

### ISSUE THREAD

**Issue by ofrzeta** [acquia/blt#3671]
**Describe the bug**
Installation of a new BLT project fails. 

**To Reproduce**
Steps to reproduce the behavior, _ideally_ starting from a fresh install of BLT:
1. Run `composer create-project acquia/blt-project --no-interaction`

**Expected behavior**
Installation of project should succeed. 

**Detailed error output**
```
PHP Fatal error:  Uncaught Error: Call to undefined function Acquia\Blt\Robo\Inspector\posix_getpwuid() in /srv/www/htdocs/testblt/vendor/acquia/blt/src/Robo/Inspector/Inspector.php:492
Stack trace:
#0 /srv/www/htdocs/testblt/vendor/acquia/blt/src/Robo/Inspector/Inspector.php(468): Acquia\Blt\Robo\Inspector\Inspector->getCliConfigFile()
#1 /srv/www/htdocs/testblt/vendor/acquia/blt/src/Robo/Commands/Blt/AliasCommand.php(28): Acquia\Blt\Robo\Inspector\Inspector->isBltAliasInstalled()
#2 [internal function]: Acquia\Blt\Robo\Commands\Blt\AliasCommand->installBltAlias(Array)
#3 /srv/www/htdocs/testblt/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#4 /srv/www/htdocs/testblt/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /srv/www/htdocs/testblt/vendor/consolidation/annotated-command/src/CommandProcessor.php(178): Consolidatio in /srv/www/htdocs/testblt/vendor/acquia/blt/src/Robo/Inspector/Inspector.php on line 492
```

**System information**
* Operating system type: CentOS 
* Operating system version: 7.6
* BLT version: 10.0.1

**Additional context**

The error occurred during installation after all steps up to this point succeeded:
```
...
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer/
Creating BLT templated files...
 > /srv/www/htdocs/testblt/vendor/acquia/blt/bin/blt internal:create-project --ansi
Copying files from BLT's template into your project...
Merging BLT's blt.yml template with your project's blt/blt.yml...
> blt:init:settings
Generating hash salt...
[File\Write] Writing to /srv/www/htdocs/testblt/salt.txt.
> recipes:blt:init:command
Example commands and hooks were copied to your repository root.
> blt:init:shell-alias
PHP Fatal error:  Uncaught Error: Call to undefined function Acquia\Blt\Robo\Inspector\posix_getpwuid() 

```

**Comment by danepowell** [comment]
You need to install the PHP posix extension. I'll open a PR to make this an explicit dependency.

**Comment by ofrzeta** [comment]
Thanks for the hint. I thought that the POSIX functions were compiled in but it turns out they aren't on Red Hat offsprings. On CentOS 7 the appropriate package to install is "php-process". Personally, to get PHP 7.2 on CentOS 7, I am using the [IUS Repo](https://ius.io/GettingStarted/) and the "php72u-process" package.
