### ISSUE TITLE
PHP 7.2 warning in Behat tests involving SimpleSAML: Cannot change session name when headers already sent 

### ISSUE THREAD

**Issue by brockfanning** [acquia/blt#3729]
**I want to...**
Figure why my Behat tests are generating PHP warnings, and causing Behat to think that it failed (even though all tests pass).

**It's not working because...**
During Behat test runs, locally, any test that involves SimpleSAML is generating a PHP warning like this: `Cannot change session name when headers already sent` plus a very long backtrace.

**Detailed error output**
The full output is quite long, but here is the first item in the backtrace, which appears after each failed test:
```
stdClass Object
  │  (
  │      [wid] => 561
  │      [uid] => 0
  │      [type] => php
  │      [message] => %type: @message in %function (line %line of %file) @backtrace_string.
  │      [variables] => Array
  │          (
  │              [%type] => Warning
  │              [@message] => Drupal\Core\Render\Markup Object
  │                  (
  │                      [string:protected] => session_name(): Cannot change session name when headers already sent
  │                  )
  │
  │              [%function] => SimpleSAML\SessionHandlerPHP->__construct()
  │              [%file] => /var/www/dojfoia/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php
  │              [%line] => 72
  │              [@backtrace_string] => #0 /var/www/dojfoia/docroot/core/includes/bootstrap.inc(587): _drupal_error_handler_real(2, 'session_name():...', '/var/www/dojfoi...', 72, Array)
  │  #1 [internal function]: _drupal_error_handler(2, 'session_name():...', '/var/www/dojfoi...', 72, Array)
  │  #2 /var/www/dojfoia/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php(72): session_name('SimpleSAML')
  │  #3 /var/www/dojfoia/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandler.php(134): SimpleSAML\SessionHandlerPHP->__construct()
  │  #4 /var/www/dojfoia/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandler.php(41): SimpleSAML\SessionHandler::createSessionHandler()
  │  #5 /var/www/dojfoia/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Session.php(336): SimpleSAML\SessionHandler::getSessionHandler()
  │  #6 /var/www/dojfoia/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Session.php(268): SimpleSAML\Session::getSession()
  │  #7 /var/www/dojfoia/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Logger.php(268): SimpleSAML\Session::getSessionFromRequest()
  │  #8 [internal function]: SimpleSAML\Logger::flush()
  │  #9 {main}
  │          )
  │
  │      [severity] => 4
  │      [link] =>
  │      [location] => http://local-api.foia.doj.gov/user/logout
  │      [referer] => http://local-api.foia.doj.gov/user/login
  │      [hostname] => 127.0.0.1
  │      [timestamp] => 1561476691
  │  )
```

**BLT doctor output**
```
vagrant@local-api:/var/www/dojfoia$ blt doctor
+---------------------------+--------------------------------------------------------+
| Property                  | Value                                                  |
+---------------------------+--------------------------------------------------------+
| %paths.%root              | /var/www/dojfoia/docroot                               |
| %paths.%site              | sites/default                                          |
| %paths.%modules           | sites/all/modules                                      |
| %paths.%themes            | sites/all/themes                                       |
| %paths.%config-sync       | /var/www/dojfoia/config/default                        |
| %paths.%files             | sites/default/files                                    |
| %paths.%temp              | /tmp                                                   |
| %paths.%private           | /var/www/dojfoia/files-private                         |
| admin-theme               | seven                                                  |
| alias-searchpaths.0       | /var/www/dojfoia/drush/sites                           |
| blt-version               | 10.1.0                                                 |
| bootstrap                 | Successful                                             |
| composer-version          | Composer version 1.8.5 2019-04-09 17:46:47             |
| config-sync               | /var/www/dojfoia/config/default                        |
| db-driver                 | mysql                                                  |
| db-hostname               | localhost                                              |
| db-name                   | drupal                                                 |
| db-password               | drupal                                                 |
| db-port                   | 3306                                                   |
| db-status                 | Connected                                              |
| db-username               | drupal                                                 |
| drupal-settings-file      | sites/default/settings.php                             |
| drupal-version            | 8.7.3                                                  |
| drush-alias-files.0       | /var/www/dojfoia/drush/sites/example.acsf.site.yml     |
| drush-alias-files.1       | /var/www/dojfoia/drush/sites/example.local.site.yml    |
| drush-alias-files.2       | /var/www/dojfoia/drush/sites/foia.site.yml             |
| drush-cache-directory     | /home/vagrant/.drush/cache                             |
| drush-conf.0              | /var/www/dojfoia/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/dojfoia/drush/drush.yml                       |
| drush-conf.2              | /var/www/dojfoia/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/dojfoia/vendor/drush/drush/drush              |
| drush-temp                | /tmp                                                   |
| drush-version             | 9.7.0                                                  |
| files                     | sites/default/files                                    |
| install-profile           | lightning                                              |
| modules                   | sites/all/modules                                      |
| php-bin                   | /usr/bin/php7.2                                        |
| php-conf.0                | /etc/php/7.2/cli/php.ini                               |
| php-os                    | Linux                                                  |
| private                   | /var/www/dojfoia/files-private                         |
| root                      | /var/www/dojfoia/docroot                               |
| site                      | sites/default                                          |
| stacks.drupal-vm.inited   | true                                                   |
| stacks.dev-desktop.inited | false                                                  |
| temp                      | /tmp                                                   |
| theme                     | bartik                                                 |
| themes                    | sites/all/themes                                       |
| uri                       | http://local-api.foia.doj.gov                          |
+---------------------------+--------------------------------------------------------+
+----------------------------------------------+--------------------------------------------------------------+
| Check                                        | Problem                                                      |
+----------------------------------------------+--------------------------------------------------------------+
| ComposerCheck:composer.extra.installer-paths | The Composer configuration for extra.installer-paths differs |
|                                              | from BLT's default, recommended values.                      |
|                                              |   Change your configuration to match BLT's defaults in       |
|                                              |                                                              |
|                                              | vendor/acquia/blt/subtree-splits/blt-project/composer.json.  |
| NodeCheck:checkNodeVersionFileExists         | Neither .nvmrc nor .node-version file found in repo root.    |
+----------------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues.
```

**System information**
* Operating system type: Ubuntu
* Operating system version: 16.04
* BLT version: 10.1.0

**Comment by mikemadison13** [comment]
seems related to https://github.com/simplesamlphp/simplesamlphp/issues/1006 ?

**Comment by danepowell** [comment]
This sounds like a problem with your SimpleSAML configuration. I don't see any evidence that this is due to a problem with BLT.

I'm also not a SimpleSAML expert so I can really only provide general troubleshooting advice. e.g., you mention this is a problem with PHP 7.2, is that significant somehow? Have you tried different PHP versions? Have you checked if the same warnings appear in other environments? Have you inspected your SimpleSAML configuration to see what's different between your production and CI environments?
