### ISSUE TITLE
BLT 11 Travis / Behat error: Cannot change session id when headers already sent

### ISSUE THREAD

**Issue by justclint** [acquia/blt#4137]
**Describe the bug**
After updating to BLT 11 we've started experiencing some intermittent errors with our travis builds that fail during the behat test but oddly the behat scenarios/steps themselves are not failing. 

Attempting to restart the travis build will sometimes end up completing successfully which makes this that much more bizarre. In some cases Ive restarted the build 4 or 5 times until it finally passes. But when it fails its always the same error as below.

**To Reproduce**
Commit new feature branch to repo to trigger travis build.

**Expected behavior**
Travis tests and builds completely and successfully.

**Detailed error output**
```
 [success] Successfully uninstalled: acquia_connector, shield
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 1.094s
> blt:init:shell-alias
BLT can automatically create a Bash alias to make it easier to run BLT tasks.
This alias will be created in /home/travis/.bash_profile.
Installing blt alias...
[File\Write] Writing to /home/travis/.bash_profile.
Added alias for blt to /home/travis/.bash_profile.
You may now use the blt command from anywhere within a BLT-generated repository.
Restart your terminal session or run source /home/travis/.bash_profile to use the new command.
12:58 total time elapsed.
/home/travis/.travis/functions: line 607:  9984 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"
blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --no-interaction --verbose || { set +v && return 1; }
> tests:behat:run
> tests:server:start
[info] Killing all processing containing string 'runserver'...
[info] Killing all processes on port '8888'...
Launching PHP's internal web server via drush.
[info] Running server at http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[Filesystem\FilesystemStack] mkdir ["/home/travis/build/redacted/redacted/reports"]
[info] Killing running google-chrome processes...
[info] Killing all processes on port '9222'...
[info] Launching headless chrome...
[Robo\Common\ProcessExecutor] Running 'google-chrome' --headless --disable-web-security --remote-debugging-port=9222  http://localhost in /home/travis/build/redacted/redacted
[info] Waiting for response from http://localhost:9222...
[info] Waiting for response from http://localhost:9222...
[Testing\Behat] Running behat  --format pretty /home/travis/build/redacted/redacted/tests/behat --colors --no-interaction --stop-on-failure --strict --config /home/travis/build/redacted/redacted/tests/behat/local.yml --profile local --tags '~ajax&&~experimental&&~lightningextension' -v
Feature: Theme loads successfully
  In order to verify the theme loads
  As a user
  I should be able to see the copyright in the footer
  Scenario: Footer in theme is loaded         # features/ThemeLoads.feature:6
    Given I am on "/"                         # Drupal\DrupalExtension\Context\MinkContext::visit()
    Then the copyright year should be current # Drupal\FeatureContext::theCopyrightYearShouldBeCurrent()
      │ Copyright in footer: © redacted 2020 
      │ 
  │
  │  stdClass Object
  │  (
  │      [wid] => 257
  │      [uid] => 0
  │      [type] => php
  │      [message] => %type: @message in %function (line %line of %file) @backtrace_string.
  │      [variables] => Array
  │          (
  │              [%type] => Warning
  │              [@message] => Drupal\Core\Render\Markup Object
  │                  (
  │                      [string:protected] => session_id(): Cannot change session id when headers already sent
  │                  )
  │  
  │              [%function] => Symfony\Component\HttpFoundation\Session\Storage\Proxy\AbstractProxy->setId()
  │              [%file] => /home/travis/build/redacted/redacted/vendor/symfony/http-foundation/Session/Storage/Proxy/AbstractProxy.php
  │              [%line] => 94
  │              [@backtrace_string] => #0 /home/travis/build/redacted/redacted/docroot/core/includes/bootstrap.inc(600): _drupal_error_handler_real(2, 'session_id(): C...', '/home/travis/bu...', 94, Array)
  │  #1 [internal function]: _drupal_error_handler(2, 'session_id(): C...', '/home/travis/bu...', 94, Array)
  │  #2 /home/travis/build/redacted/redacted/vendor/symfony/http-foundation/Session/Storage/Proxy/AbstractProxy.php(94): session_id('4InBjB8T8cxfYb3...')
  │  #3 /home/travis/build/redacted/redacted/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(183): Symfony\Component\HttpFoundation\Session\Storage\Proxy\AbstractProxy->setId('4InBjB8T8cxfYb3...')
  │  #4 /home/travis/build/redacted/redacted/docroot/core/lib/Drupal/Core/Session/SessionManager.php(131): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->setId('4InBjB8T8cxfYb3...')
  │  #5 /home/travis/build/redacted/redacted/vendor/drupal/drupal-driver/src/Drupal/Driver/Cores/Drupal8.php(42): Drupal\Core\Session\SessionManager->start()
  │  #6 /home/travis/build/redacted/redacted/vendor/drupal/drupal-driver/src/Drupal/Driver/DrupalDriver.php(80): Drupal\Driver\Cores\Drupal8->bootstrap()
  │  #7 /home/travis/build/redacted/redacted/vendor/drupal/drupal-driver/src/Drupal/Driver/DrupalDriver.php(140): Drupal\Driver\DrupalDriver->bootstrap()
  │  #8 /home/travis/build/redacted/redacted/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/Environment/Reader/Reader.php(149): Drupal\Driver\DrupalDriver->getSubDriverPaths()
  │  #9 /home/travis/build/redacted/redacted/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/Environment/Reader/Reader.php(90): Drupal\DrupalExtension\Context\Environment\Reader\Reader->findSubContextClasses()
  │  #10 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Environment/EnvironmentManager.php(115): Drupal\DrupalExtension\Context\Environment\Reader\Reader->readEnvironmentCallees(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment))
  │  #11 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Hook/HookRepository.php(50): Behat\Testwork\Environment\EnvironmentManager->readEnvironmentCallees(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment))
  │  #12 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Hook/HookRepository.php(67): Behat\Testwork\Hook\HookRepository->getEnvironmentHooks(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment))
  │  #13 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Hook/HookDispatcher.php(57): Behat\Testwork\Hook\HookRepository->getScopeHooks(Object(Behat\Testwork\Hook\Scope\BeforeSuiteScope))
  │  #14 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(63): Behat\Testwork\Hook\HookDispatcher->dispatchScopeHooks(Object(Behat\Testwork\Hook\Scope\BeforeSuiteScope))
  │  #15 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(59): Behat\Testwork\Hook\Tester\HookableSuiteTester->setUp(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
  │  #16 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(69): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->setUp(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
  │  #17 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(70): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
  │  #18 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
  │  #19 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test(Array, false)
  │  #20 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
  │  #21 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  │  #22 /home/travis/build/redacted/redacted/vendor/symfony/console/Command/Command.php(255): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  │  #23 /home/travis/build/redacted/redacted/vendor/symfony/console/Application.php(987): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  │  #24 /home/travis/build/redacted/redacted/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  │  #25 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  │  #26 /home/travis/build/redacted/redacted/vendor/symfony/console/Application.php(148): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  │  #27 /home/travis/build/redacted/redacted/vendor/behat/behat/bin/behat(34): Symfony\Component\Console\Application->run()
  │  #28 {main}
  │          )
  │  
  │      [severity] => 4
  │      [link] => 
  │      [location] => http://127.0.0.1:8888/index.php
  │      [referer] => 
  │      [hostname] => 127.0.0.1
  │      [timestamp] => 1587668661
  │  )
  │  
  │
  ╳  Exception: PHP errors logged to watchdog in this scenario. in /home/travis/build/redacted/redacted/docroot/modules/contrib/lightning_core/tests/contexts/WatchdogContext.behat.inc:92
  ╳  Stack trace:
  ╳  #0 [internal function]: WatchdogContext->checkWatchdog(Object(Behat\Behat\Hook\Scope\AfterScenarioScope))
  ╳  #1 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(103): call_user_func_array(Array, Array)
  ╳  #2 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(59): Behat\Testwork\Call\Handler\RuntimeCallHandler->executeCall(Object(Behat\Testwork\Hook\Call\HookCall))
  ╳  #3 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(140): Behat\Testwork\Call\Handler\RuntimeCallHandler->handleCall(Object(Behat\Testwork\Hook\Call\HookCall))
  ╳  #4 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Call/CallCenter.php(96): Behat\Testwork\Call\CallCenter->handleCall(Object(Behat\Testwork\Hook\Call\HookCall))
  ╳  #5 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Hook/HookDispatcher.php(74): Behat\Testwork\Call\CallCenter->makeCall(Object(Behat\Testwork\Hook\Call\HookCall))
  ╳  #6 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Hook/HookDispatcher.php(58): Behat\Testwork\Hook\HookDispatcher->dispatchHook(Object(Behat\Behat\Hook\Scope\AfterScenarioScope), Object(Behat\Behat\Hook\Call\AfterScenario))
  ╳  #7 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableScenarioTester.php(89): Behat\Testwork\Hook\HookDispatcher->dispatchScopeHooks(Object(Behat\Behat\Hook\Scope\AfterScenarioScope))
  ╳  #8 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingScenarioTester.php(114): Behat\Behat\Hook\Tester\HookableScenarioTester->tearDown(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false, Object(Behat\Testwork\Tester\Result\TestResults))
  ╳  #9 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/IsolatingScenarioTester.php(70): Behat\Behat\EventDispatcher\Tester\EventDispatchingScenarioTester->tearDown(Object(Behat\Behat\Context\Environment\InitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false, Object(Behat\Testwork\Tester\Result\TestResults))
  ╳  #10 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Behat/Tester/Runtime/RuntimeFeatureTester.php(84): Behat\Behat\Tester\Runtime\IsolatingScenarioTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), Object(Behat\Gherkin\Node\ScenarioNode), false)
  ╳  #11 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Behat/Hook/Tester/HookableFeatureTester.php(72): Behat\Behat\Tester\Runtime\RuntimeFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
  ╳  #12 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Behat/EventDispatcher/Tester/EventDispatchingFeatureTester.php(71): Behat\Behat\Hook\Tester\HookableFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
  ╳  #13 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeSuiteTester.php(63): Behat\Behat\EventDispatcher\Tester\EventDispatchingFeatureTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Gherkin\Node\FeatureNode), false)
  ╳  #14 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Hook/Tester/HookableSuiteTester.php(73): Behat\Testwork\Tester\Runtime\RuntimeSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
  ╳  #15 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingSuiteTester.php(72): Behat\Testwork\Hook\Tester\HookableSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
  ╳  #16 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Tester/Runtime/RuntimeExercise.php(71): Behat\Testwork\EventDispatcher\Tester\EventDispatchingSuiteTester->test(Object(Behat\Behat\Context\Environment\UninitializedContextEnvironment), Object(Behat\Testwork\Specification\GroupedSpecificationIterator), false)
  ╳  #17 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php(70): Behat\Testwork\Tester\Runtime\RuntimeExercise->test(Array, false)
  ╳  #18 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php(80): Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->test(Array, false)
  ╳  #19 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(149): Behat\Testwork\Ordering\OrderedExercise->test(Array, false)
  ╳  #20 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php(108): Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications(Object(Symfony\Component\Console\Input\ArgvInput), Array)
  ╳  #21 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php(63): Behat\Testwork\Tester\Cli\ExerciseController->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  ╳  #22 /home/travis/build/redacted/redacted/vendor/symfony/console/Command/Command.php(255): Behat\Testwork\Cli\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  ╳  #23 /home/travis/build/redacted/redacted/vendor/symfony/console/Application.php(987): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  ╳  #24 /home/travis/build/redacted/redacted/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Behat\Testwork\Cli\Command), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  ╳  #25 /home/travis/build/redacted/redacted/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  ╳  #26 /home/travis/build/redacted/redacted/vendor/symfony/console/Application.php(148): Behat\Testwork\Cli\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
  ╳  #27 /home/travis/build/redacted/redacted/vendor/behat/behat/bin/behat(34): Symfony\Component\Console\Application->run()
  ╳  #28 {main}
  │
  └─ @AfterScenario ~@errors # WatchdogContext::checkWatchdog()
1 scenario (1 passed)
2 steps (2 passed)
0m0.55s (35.95Mb)
[Testing\Behat]  Exit code 1 
[info] Killing running google-chrome processes...
[info] Killing all processes on port '9222'...
> tests:server:kill
[info] Killing all processing containing string 'runserver'...
[info] Killing all processes on port '8888'...
[error]  Behat tests failed!
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
[error]  Command `tests:behat:run ` exited with code 1.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
7.117s total time elapsed.
The command "source ${BLT_DIR}/scripts/travis/run_tests" exited with 1.
```

**BLT doctor output**
```
vagrant@local:/var/www/redacted$ blt doctor
+---------------------------+--------------------------------------------------------+
| Property                  | Value                                                  |
+---------------------------+--------------------------------------------------------+
| %paths.%root              | /var/www/redacted/docroot                               |
| %paths.%site              | sites/default                                          |
| %paths.%modules           | sites/all/modules                                      |
| %paths.%themes            | sites/all/themes                                       |
| %paths.%config-sync       | /var/www/redacted/config/default                        |
| %paths.%files             | sites/default/files                                    |
| %paths.%temp              | /tmp                                                   |
| %paths.%private           | /var/www/redacted/files-private                         |
| admin-theme               | seven                                                  |
| alias-searchpaths.0       | /var/www/redacted/drush/sites                           |
| base-profile              |                                                        |
| blt-version               | 11.4.0                                                 |
| bootstrap                 | Successful                                             |
| composer-version          | Composer version 1.8.6 2019-06-11 15:03:05             |
| config-sync               | /var/www/redacted/config/default                        |
| db-driver                 | mysql                                                  |
| db-hostname               | localhost                                              |
| db-name                   | drupal                                                 |
| db-password               | drupal                                                 |
| db-port                   | 3306                                                   |
| db-status                 | Connected                                              |
| db-username               | drupal                                                 |
| drupal-settings-file      | sites/default/settings.php                             |
| drupal-version            | 8.8.4                                                  |
| drush-alias-files.0       | /var/www/redacted/drush/sites/example.acsf.site.yml     |
| drush-alias-files.1       | /var/www/redacted/drush/sites/example.local.site.yml    |
| drush-alias-files.2       | /var/www/redacted/drush/sites/legacy.site.yml           |
| drush-alias-files.3       | /var/www/redacted/drush/sites/redacted-dev.site.yml      |
| drush-alias-files.4       | /var/www/redacted/drush/sites/redacted-prod.site.yml     |
| drush-alias-files.5       | /var/www/redacted/drush/sites/redacted-qa.site.yml       |
| drush-alias-files.6       | /var/www/redacted/drush/sites/redacted-ra.site.yml       |
| drush-alias-files.7       | /var/www/redacted/drush/sites/redacted-test.site.yml     |
| drush-alias-files.8       | /var/www/redacted/drush/sites/redacted.site.yml          |
| drush-cache-directory     | /home/vagrant/.drush/cache                             |
| drush-conf.0              | /var/www/redacted/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/redacted/drush/drush.yml                       |
| drush-conf.2              | /var/www/redacted/docroot/drush                         |
| drush-conf.3              | /var/www/redacted/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/redacted/vendor/drush/drush/drush              |
| drush-temp                | /tmp                                                   |
| drush-version             | 9.7.2                                                  |
| files                     | sites/default/files                                    |
| install-profile           | lightning                                              |
| modules                   | sites/all/modules                                      |
| php-bin                   | /usr/bin/php7.2                                        |
| php-conf.0                | /etc/php/7.2/cli/php.ini                               |
| php-os                    | Linux                                                  |
| private                   | /var/www/redacted/files-private                         |
| root                      | /var/www/redacted/docroot                               |
| site                      | sites/default                                          |
| stacks.drupal-vm.inited   | true                                                   |
| stacks.dev-desktop.inited | false                                                  |
| temp                      | /tmp                                                   |
| theme                     | bootstrap_redacted                                         |
| themes                    | sites/all/themes                                       |
| uri                       | http://local.redacted.com                               |
+---------------------------+--------------------------------------------------------+
+----------------------------------------------+--------------------------------------------------------------+
| Check                                        | Problem                                                      |
+----------------------------------------------+--------------------------------------------------------------+
| ComposerCheck:composer.extra.installer-paths | The Composer configuration for extra.installer-paths differs |
|                                              | from BLT's default, recommended values.                      |
|                                              |   Change your configuration to match BLT's defaults in       |
|                                              |                                                              |
|                                              | vendor/acquia/blt/subtree-splits/blt-project/composer.json.  |
| NodeCheck:checkNodeVersionFileExists         | .nvmrc file exists                                           |
+----------------------------------------------+--------------------------------------------------------------+

```

**System information**
* Operating system type: macos
* Operating system version: catalina 10.15.4 (19E287)
* BLT version: 11.4.0

**Additional context**
Just wanted to point out what seems strange is our behat scenerio & steps pass as you can see in the travis build: 
```
1 scenario (1 passed)
2 steps (2 passed)
```
but for whatever reason it still fails.

**Comment by danepowell** [comment]
The error message is coming from this feature of the Lightning Behat context that monitors the watchdog for errors: https://git.drupalcode.org/project/lightning/-/blob/8.x-2.x/tests/features/bootstrap/lightning.behat.inc#L83

It looks like you are running a pretty old version of Lightning, that [code was removed in 8.x-3.x](https://git.drupalcode.org/project/lightning/-/commit/e8fc7e1aa9f69cee29a7a4b84c4ded98c43c1abd). If you upgrade, you might still get the session warning but it might not fail tests.

I don't know what's causing the session warnings, but I don't see any evidence that it's caused by BLT. Given the old version of Lightning, I suspect some other part of your testing stack is also out of date (especially Drupal Extension) and updating may fix it.

**Comment by justclint** [comment]
Great, thanks @danepowell! We'll get lightning updated.

**Comment by justclint** [comment]
Seems like we were on the latest lighting. Ive moved this issue over to lighting issues: https://www.drupal.org/project/lightning/issues/3132956

Thanks!
