### ISSUE TITLE
blt setup error MYSQL_ATTR_USE_BUFFERED_QUERY

### ISSUE THREAD

**Issue by justclint** [acquia/blt#4277]
We are onboarding someone and trying to get their local setup but they keep getting errors we dont usually see when running `blt setup`. 

**I want to...**
Stand up an existing project locally.

**It's not working because...**
when trying to run `blt setup` we keep getting `error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY'`

**Detailed error output**
```
vagrant@local:/var/www/**redacted**$ blt setup -vvv
Setting up local environment for site default.
Using drush alias @self
> source:build
[debug] Verifying that Drupal is installed...
[Robo\Common\ProcessExecutor] Running /var/www/**redacted**/vendor/bin/drush @self --uri= status bootstrap in /var/www/**redacted**/docroot
Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/**redacted**/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/**redacted**/docroot/core/lib/Drupal/Core/Database/Database.php(374): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /var/www/**redacted**/docroot/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 /var/www/**redacted**/vendor/drush/drush/src/Boot/DrupalBoot8.php(189): Drupal\Core\Database\Database::getConnection()
#3 /var/www/**redacted**/vendor/drush/drush/src/Boot/BootstrapManager.php(358): Drush\Boot\DrupalBoot8->bootstrapDrupalDatabaseValidate(Object(Drush\Boot\BootstrapManager))
#4 /var/www/**redacted**/vendor/drush/drush/src/Boot/BootstrapManager.php(491): Drush\Boot\BootstrapManager->bootstrapValidate(4)
#5 /var/www/**redacted**/vendor/drush/drush/src/Boot/BootstrapManager.php(427): Drush\Boot\BootstrapManager->bootstrapMax(6)
#6 /var/www/**redacted**/vendor/drush/drush/src/Boot/BootstrapManager.php(396): Drush\Boot\BootstrapManager->bootstrapToPhaseIndex(-2, Object(Consolidation\AnnotatedCommand\AnnotationData))
#7 /var/www/**redacted**/vendor/drush/drush/src/Boot/BootstrapHook.php(28): Drush\Boot\BootstrapManager->bootstrapToPhase('max', Object(Consolidation\AnnotatedCommand\AnnotationData))
#8 /var/www/**redacted**/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(34): Drush\Boot\BootstrapHook->initialize(Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#9 /var/www/**redacted**/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Object(Drush\Boot\BootstrapHook), Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#10 /var/www/**redacted**/vendor/consolidation/annotated-command/src/CommandProcessor.php(145): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize(Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#11 /var/www/**redacted**/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(289): Consolidation\AnnotatedCommand\CommandProcessor->initializeHook(Object(Drush\Symfony\DrushArgvInput), Array, Object(Consolidation\AnnotatedCommand\AnnotationData))
#12 /var/www/**redacted**/vendor/symfony/console/Command/Command.php(221): Consolidation\AnnotatedCommand\AnnotatedCommand->initialize(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/**redacted**/vendor/symfony/console/Application.php(1010): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/**redacted**/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/**redacted**/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/**redacted**/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/**redacted**/vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/**redacted**/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#19 /var/www/**redacted**/vendor/drush/drush/drush(4): require('/var/www/**redacted**...')
#20 {main}
Error: Undefined class constant &#039;MYSQL_ATTR_USE_BUFFERED_QUERY&#039; in Drupal\Core\Database\Driver\mysql\Connection::open() (line 404 of /var/www/**redacted**/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php).
 [warning] Drush command terminated abnormally.
> tests:behat:init:config
> source:build:composer
[Exec] Running export COMPOSER_EXIT_ON_PATCH_FAILURE=1 &&
 composer install --ansi --no-interaction in /var/www/**redacted**
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package drupal-composer/drupal-scaffold is abandoned, you should avoid using it. Use drupal/core-composer-scaffold instead.
Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
57 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
PHP CodeSniffer Config installed_paths set to ../../sirbrillig/phpcs-variable-analysis,../../drupal/coder/coder_sniffer
[Exec] Done in 2.359s
> blt:init:git-hooks
Installing pre-commit git hook...
[Filesystem\FilesystemStack] mkdir ["/var/www/**redacted**/.git/hooks"]
[Filesystem\FilesystemStack] remove ["/var/www/**redacted**/.git/hooks/pre-commit"]
[Filesystem\FilesystemStack] symlink ["../../vendor/acquia/blt/scripts/git-hooks/pre-commit","/var/www/**redacted**/.git/hooks/pre-commit"]
Installing pre-push git hook...
[Filesystem\FilesystemStack] mkdir ["/var/www/**redacted**/.git/hooks"]
[Filesystem\FilesystemStack] remove ["/var/www/**redacted**/.git/hooks/pre-push"]
[Filesystem\FilesystemStack] symlink ["../../vendor/acquia/blt/scripts/git-hooks/pre-push","/var/www/**redacted**/.git/hooks/pre-push"]
Installing commit-msg git hook...
[Filesystem\FilesystemStack] mkdir ["/var/www/**redacted**/.git/hooks"]
[Filesystem\FilesystemStack] remove ["/var/www/**redacted**/.git/hooks/commit-msg"]
[Filesystem\FilesystemStack] symlink ["../../vendor/acquia/blt/scripts/git-hooks/commit-msg","/var/www/**redacted**/.git/hooks/commit-msg"]
> blt:init:settings
Hash salt already exists.
[debug] Multisites found: default
[debug] Initial site: default
[Filesystem\FilesystemStack] _chmod ["/var/www/**redacted**/docroot/sites/default",511]
[Filesystem\FilesystemStack] _chmod ["/var/www/**redacted**/docroot/sites/default/settings.php",511]
[File\Write] Writing to /var/www/**redacted**/docroot/sites/default/settings.php.
[Filesystem\FilesystemStack] _chmod ["/var/www/**redacted**/docroot/sites/default/settings.php",420]
> source:build:frontend
> source:build:frontend-reqs
Executing frontend-reqs target hook...
[ExecStack] ./scripts/bootstrap_**redacted**/frontend-setup.sh
[ExecStack] Running ./scripts/bootstrap_**redacted**/frontend-setup.sh in /var/www/**redacted**
Removing bootstrap_**redacted** node_modules if exists...
Removing pattern-lab node_modules if exists...
Removing public directory contents...
Installing NPM in theme...
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
.....
Built Pattern Lab front end
⊙ patternlab → build: Yay, your Pattern Lab project was successfully built ☺
$ ../../../../scripts/bootstrap_**redacted**/frontend-build.sh
Adding assets from NPM packages
Copying bootstrap js files...
cp: cannot stat 'node_modules/bootstrap-sass/assets/javascripts/bootstrap.min.js': No such file or directory
cp: cannot stat 'node_modules/bootstrap-sass/assets/javascripts/bootstrap-sprockets.js': No such file or directory
cp: cannot stat 'node_modules/bootstrap-sass/assets/javascripts/bootstrap': No such file or directory
Copying bootstrap-datetimepicker.min.js...
cp: cannot stat 'node_modules/bootstrap-datetimepicker-npm/build/js/bootstrap-datetimepicker.min.js': No such file or directory
Copying bootstrap-select.min.js...
cp: cannot stat 'node_modules/bootstrap-select/dist/js/bootstrap-select.min.js': No such file or directory
cp: cannot stat 'node_modules/bootstrap-select/dist/js/bootstrap-select.min.js.map': No such file or directory
Copying moment js...
cp: cannot stat 'node_modules/moment/min/*': No such file or directory
Copying Launch Darkly Client ldclient.min.js...
cp: cannot stat 'node_modules/ldclient-js/dist/ldclient.min.js': No such file or directory
cp: cannot stat 'node_modules/ldclient-js/dist/ldclient.min.js.map': No such file or directory
Copying Pattern Lab style guide...
Copying Animate.css...
cp: cannot stat 'node_modules/animate.css/animate.min.css': No such file or directory
Copying Bootstrap fonts...
cp: cannot stat 'node_modules/bootstrap-sass/assets/fonts/bootstrap/*': No such file or directory
Copying IonIcons fonts...
cp: cannot stat 'node_modules/ionicons/fonts/*': No such file or directory
Copying flag-icon-css icons...
cp: cannot stat 'node_modules/flag-icon-css/flags': No such file or directory
Copying simple-line-icons...
cp: cannot stat 'node_modules/simple-line-icons/fonts/*': No such file or directory
Copying jpList...
cp: cannot stat 'node_modules/jplist-es6/dist/1.2.0/jplist.min.js': No such file or directory
cp: cannot stat 'node_modules/jplist-es6/dist/1.2.0/jplist.min.js.map': No such file or directory
cp: cannot stat 'node_modules/jplist-es6/dist/1.2.0/jplist.styles.css': No such file or directory
cp: cannot stat 'node_modules/jplist-es6/dist/1.2.0/jplist.styles.css.map': No such file or directory
Copying icons from **redacted** design-system...
cp: cannot stat 'node_modules/@**redacted**/design-system/dist/system/icons/*': No such file or directory
cp: cannot stat 'node_modules/@**redacted**/webfont-icons/dist/fonts/*': No such file or directory
Applying Pattern Lab style guide customizations...
../../../../scripts/bootstrap_**redacted**/frontend-build.sh: line 76: npm-sass: command not found
../../../../scripts/bootstrap_**redacted**/frontend-build.sh: line 77: npm-sass: command not found
../../../../scripts/bootstrap_**redacted**/frontend-build.sh: line 78: uglifycss: command not found
cat: public/css/styleguide.min.css: No such file or directory
Minifying css...
../../../../scripts/bootstrap_**redacted**/frontend-build.sh: line 85: npm-sass: command not found
../../../../scripts/bootstrap_**redacted**/frontend-build.sh: line 86: uglifycss: command not found
Minifying js...
../../../../scripts/bootstrap_**redacted**/frontend-build.sh: line 89: uglifyjs: command not found
The frontend build is complete.
Done in 13.07s.
[ExecStack] Done in 13.258s
Executing post-setup-build target hook...
[ExecStack] echo 'No post-setup build configured.'
[ExecStack] Running echo 'No post-setup build configured.' in /var/www/**redacted**/docroot
No post-setup build configured.
[ExecStack] Done in 0.003s
> drupal:deployment-identifier:init
Generating deployment identifier...
[File\Write] Writing to /var/www/**redacted**/deployment_identifier.
> drupal:install
[Robo\Common\ProcessExecutor] Running /var/www/**redacted**/vendor/bin/drush @self site:alias @self --format=json in /var/www/**redacted**/docroot
{
    "@self": {
        "root": "/var/www/**redacted**/docroot",
        "uri": "http://local.**redacted**.com"
    }
}
> internal:drupal:install
[Robo\Common\ProcessExecutor] Running /var/www/**redacted**/vendor/bin/drush @self site:alias @self --format=json in /var/www/**redacted**/docroot
{
    "@self": {
        "root": "/var/www/**redacted**/docroot",
        "uri": "http://local.**redacted**.com"
    }
}
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/**redacted**/vendor/bin/drush @self site-install lightning install_configure_form.enable_update_status_module=NULL --sites-subdir=default --site-name='**redacted**.com BLT Drupal 8' --site-mail=no-reply@acquia.com --account-name='w5Lpj2_+dB' --account-mail=no-reply@acquia.com --locale=en -vvv --ansi in /var/www/**redacted**/docroot
 [preflight] Config paths: /var/www/**redacted**/vendor/drush/drush/drush.yml,/var/www/**redacted**/drush/drush.yml,/var/www/**redacted**/docroot/drush,/var/www/**redacted**/docroot/sites/default/local.drush.yml
 [preflight] Alias paths: /var/www/**redacted**/docroot/drush/sites,/var/www/**redacted**/drush/sites
 [preflight] Commandfile search paths: /var/www/**redacted**/vendor/drush/drush/src,/var/www/**redacted**/drush
 [bootstrap] Starting bootstrap to root [0.13 sec, 8.92 MB]
 [bootstrap] Drush bootstrap phase 1 [0.13 sec, 8.92 MB]
 [bootstrap] Try to validate bootstrap phase 1 [0.13 sec, 8.92 MB]
 [bootstrap] Try to validate bootstrap phase 1 [0.13 sec, 8.92 MB]
 [bootstrap] Try to bootstrap at phase 1 [0.13 sec, 8.92 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot() [0.14 sec, 8.92 MB]
 [bootstrap] Change working directory to /var/www/**redacted**/docroot [0.14 sec, 8.92 MB]
 [bootstrap] Initialized Drupal 8.9.6 root directory at /var/www/**redacted**/docroot [0.14 sec, 9.05 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite() [0.15 sec, 9.43 MB]
 [bootstrap] Initialized Drupal site default at sites/default [0.15 sec, 9.6 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.15 sec, 9.6 MB]
 [debug] Add service modifier [0.2 sec, 10.25 MB]
 [info] Executing: command -v mysql [0.21 sec, 11.32 MB]
 [debug]  [0.21 sec, 11.36 MB]

 You are about to Program mysql not found. Proceed if you have already created or emptied the Drupal database. Do you want to continue? (yes/no) [yes]:
 > yes

 [info] Sites directory sites/default already exists - proceeding. [50.47 sec, 11.4 MB]
 [notice] Starting Drupal installation. This takes a while. [50.48 sec, 11.41 MB]
 [debug] Calling install_drupal(Composer\Autoload\ClassLoader, array) [50.49 sec, 11.71 MB]
Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/**redacted**/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/**redacted**/docroot/core/lib/Drupal/Core/Database/Database.php(374): Drupal\Core\Database\Driver\mysql\Connection::open(Array)
#1 /var/www/**redacted**/docroot/core/lib/Drupal/Core/Database/Database.php(169): Drupal\Core\Database\Database::openConnection('default', 'default')
#2 /var/www/**redacted**/docroot/core/lib/Drupal/Core/Config/BootstrapConfigStorageFactory.php(40): Drupal\Core\Database\Database::getConnection()
#3 /var/www/**redacted**/docroot/core/lib/Drupal/Core/Config/BootstrapConfigStorageFactory.php(31): Drupal\Core\Config\BootstrapConfigStorageFactory::getDatabaseStorage()
#4 /var/www/**redacted**/docroot/core/lib/Drupal/Core/DrupalKernel.php(1414): Drupal\Core\Config\BootstrapConfigStorageFactory::get(Object(Composer\Autoload\ClassLoader))
#5 /var/www/**redacted**/docroot/core/lib/Drupal/Core/Installer/InstallerKernel.php(48): Drupal\Core\DrupalKernel->getConfigStorage()
#6 /var/www/**redacted**/docroot/core/lib/Drupal/Core/DrupalKernel.php(623): Drupal\Core\Installer\InstallerKernel->getConfigStorage()
#7 /var/www/**redacted**/docroot/core/lib/Drupal/Core/DrupalKernel.php(1345): Drupal\Core\DrupalKernel->discoverServiceProviders()
#8 /var/www/**redacted**/docroot/core/lib/Drupal/Core/DrupalKernel.php(1254): Drupal\Core\DrupalKernel->initializeServiceProviders()
#9 /var/www/**redacted**/docroot/core/lib/Drupal/Core/DrupalKernel.php(916): Drupal\Core\DrupalKernel->compileContainer()
#10 /var/www/**redacted**/docroot/core/lib/Drupal/Core/Installer/InstallerKernel.php(20): Drupal\Core\DrupalKernel->initializeContainer()
#11 /var/www/**redacted**/docroot/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\Core\Installer\InstallerKernel->initializeContainer()
#12 /var/www/**redacted**/docroot/core/includes/install.core.inc(430): Drupal\Core\DrupalKernel->boot()
#13 /var/www/**redacted**/docroot/core/includes/install.core.inc(115): install_begin_request(Object(Composer\Autoload\ClassLoader), Array)
#14 /var/www/**redacted**/vendor/drush/drush/includes/drush.inc(229): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#15 /var/www/**redacted**/vendor/drush/drush/includes/drush.inc(214): drush_call_user_func_array('install_drupal', Array)
#16 /var/www/**redacted**/vendor/drush/drush/src/Commands/core/SiteInstallCommands.php(145): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#17 [internal function]: Drush\Commands\core\SiteInstallCommands->install('lightning', Array)
#18 /var/www/**redacted**/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#19 /var/www/**redacted**/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#20 /var/www/**redacted**/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#21 /var/www/**redacted**/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#22 /var/www/**redacted**/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/**redacted**/vendor/symfony/console/Application.php(1010): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/**redacted**/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/**redacted**/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/**redacted**/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/**redacted**/vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/**redacted**/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#29 /var/www/**redacted**/vendor/drush/drush/drush(4): require('/var/www/**redacted**...')
#30 {main}
Error: Undefined class constant &#039;MYSQL_ATTR_USE_BUFFERED_QUERY&#039; in Drupal\Core\Database\Driver\mysql\Connection::open() (line 404 of /var/www/**redacted**/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php).
 [warning] Drush command terminated abnormally. [52.9 sec, 14.78 MB]
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 53.016s
[error]  Failed to install Drupal!
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
[error]  Command `internal:drupal:install ` exited with code 1.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
[error]  Command `drupal:install ` exited with code 1.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
03:01 total time elapsed.
vagrant@local:/var/www/**redacted**$ 
```

**BLT doctor output**
```
vagrant@local:/var/www/**redacted**$ blt doctor
+---------------------------+----------------------------------------------+
| Property         | Value                    |
+---------------------------+----------------------------------------------+
| blt-version        | 11.4.0                    |
| composer-version     | Composer version 1.10.13 2020-09-09 11:46:34 |
| root           | /var/www/**redacted**/docroot           |
| stacks.drupal-vm.inited  | true                     |
| stacks.dev-desktop.inited | false                    |
| uri            | default                   |
+---------------------------+----------------------------------------------+
+----------------------------------------------+--------------------------------------------------------------+
| Check                    | Problem                           |
+----------------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri         | base_url in tests/behat/local.yml does not match the site  |
|                       | URI.                             |
|                       |  Behat base_url is set to                  |
|                       | http://local.**redacted**.com.                  |
|                       |  Drush site URI is set to default.             |
| ComposerCheck:composer.extra.installer-paths | The Composer configuration for extra.installer-paths differs |
|                       | from BLT's default, recommended values.           |
|                       |  Change your configuration to match BLT's defaults in    |
|                       |                               |
|                       | vendor/acquia/blt/subtree-splits/blt-project/composer.json. |
| DbCheck:checkRequiredKeys          | drush status is missing the 'db-hostname' key.        |
| DrupalCheck:checkDrupalBootstrapped     | Could not bootstrap Drupal via drush without alias.     |
| DrupalCheck:checkDrupalInstalled       | Drupal is not installed.                   |
|                       |                               |
|                       | Run `blt drupal:install` to install Drupal locally.     |
| FileSystemCheck:checkFileSystem:%files    | Public files directory is not set.              |
| FileSystemCheck:checkFileSystem:%private   | Private files directory is not set.             |
| FileSystemCheck:checkFileSystem:%temp    | Temporary files directory is not set.            |
| NodeCheck:checkNodeVersionFileExists     | .nvmrc file exists                      |
| WebUriCheck:checkUri             | Site URI is not set                     |
|                       | Is options.uri set correctly in               |
|                       | /var/www/**redacted**/docroot/sites/default/local.drush.yml?   |
+----------------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
vagrant@local:/var/www/**redacted**$
```

**System information**
* Operating system type: osx
* Operating system version: Catalina 10.15.7
* BLT version: 11.4

**Comment by danepowell** [comment]
This is not a BLT issue, you can replicate it by running the `drush site-install` command completely independent of BLT. It's most likely occurring because your site is configured to connect to MySQL, but you don't have the PHP MySQL extension installed and enabled.

**Comment by justclint** [comment]
Ok, I see what you mean. But we never ran into this before onboarding others. I thought DrupalVM would handle all the php and mysql config. Do they need to have php and mysql setup on their host?

**Comment by danepowell** [comment]
You need MySQL wherever you are running BLT / Drush commands. If it's inside the VM, I'd expect the VM to have it. You might want to get help directly from Drupal VM in that case. For instance, I see this existing issue: https://github.com/geerlingguy/drupal-vm/issues/226

It sounds like reprovisioning your VM might help (make sure there are no errors during provisioning).

**Comment by justclint** [comment]
thanks @danepowell !
