### ISSUE TITLE
Command `tests:server:start ` exited with code 1.

### ISSUE THREAD

**Issue by jedgar1mx** [acquia/blt#4604]
**Describe the bug**
I started to get errors recently when trying to run the test server command. Here is the error.

`[error]  TypeError: Drush\Drupal\Commands\config\ConfigImportCommands::__construct(): Argument #3 ($configCache) must be of type Drupal\Core\Cache\CacheBackendInterface, Drupal\Core\Config\FileStorage given, called in /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 262 in Drush\Drupal\Commands\config\ConfigImportCommands->__construct() (line 172 of /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php) #0 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(262): Drush\Drupal\Commands\config\ConfigImportCommands->__construct(Object(Drupal\Core\Config\ConfigManager), Object(Drupal\Core\Config\CachedStorage), Object(Drupal\Core\Config\FileStorage), Object(Drupal\Core\Cache\ChainedFastBackend), Object(Drupal\Core\Extension\ModuleHandler), Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher), Object(Drupal\Core\ProxyClass\Lock\DatabaseLockBackend), Object(Drupal\Core\Config\TypedConfigManager), Object(Drupal\Core\ProxyClass\Extension\ModuleInstaller), Object(Drupal\Core\Extension\ThemeHandler), Object(Drupal\Core\StringTranslation\TranslationManager), Object(Drupal\Core\Extension\ModuleExtensionList))`

**Detailed error output**
` [error]  TypeError: Drush\Drupal\Commands\config\ConfigImportCommands::__construct(): Argument #3 ($configCache) must be of type Drupal\Core\Cache\CacheBackendInterface, Drupal\Core\Config\FileStorage given, called in /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 262 in Drush\Drupal\Commands\config\ConfigImportCommands->__construct() (line 172 of /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php) #0 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(262): Drush\Drupal\Commands\config\ConfigImportCommands->__construct(Object(Drupal\Core\Config\ConfigManager), Object(Drupal\Core\Config\CachedStorage), Object(Drupal\Core\Config\FileStorage), Object(Drupal\Core\Cache\ChainedFastBackend), Object(Drupal\Core\Extension\ModuleHandler), Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher), Object(Drupal\Core\ProxyClass\Lock\DatabaseLockBackend), Object(Drupal\Core\Config\TypedConfigManager), Object(Drupal\Core\ProxyClass\Extension\ModuleInstaller), Object(Drupal\Core\Extension\ThemeHandler), Object(Drupal\Core\StringTranslation\TranslationManager), Object(Drupal\Core\Extension\ModuleExtensionList))
#1 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\Container->createService(Array, 'config.import.c...')
#2 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(437): Drupal\Component\DependencyInjection\Container->get('config.import.c...', 3)
#3 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(276): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#4 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\Container->createService(Array, 'drush.command.s...')
#5 /app/vendor/drush/drush/src/Boot/DrupalBoot8.php(288): Drupal\Component\DependencyInjection\Container->get('drush.command.s...')
#6 /app/vendor/drush/drush/src/Boot/DrupalBoot8.php(251): Drush\Boot\DrupalBoot8->addDrupalModuleDrushCommands(Object(Drush\Boot\BootstrapManager))
#7 /app/vendor/drush/drush/src/Boot/BootstrapManager.php(291): Drush\Boot\DrupalBoot8->bootstrapDrupalFull(Object(Drush\Boot\BootstrapManager), Object(Consolidation\AnnotatedCommand\AnnotationData))
#8 /app/vendor/drush/drush/src/Boot/BootstrapManager.php(432): Drush\Boot\BootstrapManager->doBootstrap(5, 5, Object(Consolidation\AnnotatedCommand\AnnotationData))
#9 /app/vendor/drush/drush/src/Boot/BootstrapManager.php(384): Drush\Boot\BootstrapManager->bootstrapToPhaseIndex(5, Object(Consolidation\AnnotatedCommand\AnnotationData))
#10 /app/vendor/drush/drush/src/Boot/BootstrapHook.php(32): Drush\Boot\BootstrapManager->bootstrapToPhase('full', Object(Consolidation\AnnotatedCommand\AnnotationData))
#11 /app/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(44): Drush\Boot\BootstrapHook->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#12 /app/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(36): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->doInitializeHook(Object(Drush\Boot\BootstrapHook), Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#13 /app/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(29): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Object(Drush\Boot\BootstrapHook), Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#14 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(145): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#15 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(335): Consolidation\AnnotatedCommand\CommandProcessor->initializeHook(Object(Symfony\Component\Console\Input\ArgvInput), Array, Object(Consolidation\AnnotatedCommand\AnnotationData))
#16 /app/vendor/symfony/console/Command/Command.php(221): Consolidation\AnnotatedCommand\AnnotatedCommand->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /app/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /app/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /app/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#23 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#24 {main}. [10.61 sec, 23.6 MB]
TypeError: Drush\Drupal\Commands\config\ConfigImportCommands::__construct(): Argument #3 ($configCache) must be of type Drupal\Core\Cache\CacheBackendInterface, Drupal\Core\Config\FileStorage given, called in /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 262 in /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php on line 172 #0 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(262): Drush\Drupal\Commands\config\ConfigImportCommands->__construct(Object(Drupal\Core\Config\ConfigManager), Object(Drupal\Core\Config\CachedStorage), Object(Drupal\Core\Config\FileStorage), Object(Drupal\Core\Cache\ChainedFastBackend), Object(Drupal\Core\Extension\ModuleHandler), Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher), Object(Drupal\Core\ProxyClass\Lock\DatabaseLockBackend), Object(Drupal\Core\Config\TypedConfigManager), Object(Drupal\Core\ProxyClass\Extension\ModuleInstaller), Object(Drupal\Core\Extension\ThemeHandler), Object(Drupal\Core\StringTranslation\TranslationManager), Object(Drupal\Core\Extension\ModuleExtensionList))
#1 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\Container->createService(Array, 'config.import.c...')
#2 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(437): Drupal\Component\DependencyInjection\Container->get('config.import.c...', 3)
#3 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(276): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#4 /app/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(176): Drupal\Component\DependencyInjection\Container->createService(Array, 'drush.command.s...')
#5 /app/vendor/drush/drush/src/Boot/DrupalBoot8.php(288): Drupal\Component\DependencyInjection\Container->get('drush.command.s...')
#6 /app/vendor/drush/drush/src/Boot/DrupalBoot8.php(251): Drush\Boot\DrupalBoot8->addDrupalModuleDrushCommands(Object(Drush\Boot\BootstrapManager))
#7 /app/vendor/drush/drush/src/Boot/BootstrapManager.php(291): Drush\Boot\DrupalBoot8->bootstrapDrupalFull(Object(Drush\Boot\BootstrapManager), Object(Consolidation\AnnotatedCommand\AnnotationData))
#8 /app/vendor/drush/drush/src/Boot/BootstrapManager.php(432): Drush\Boot\BootstrapManager->doBootstrap(5, 5, Object(Consolidation\AnnotatedCommand\AnnotationData))
#9 /app/vendor/drush/drush/src/Boot/BootstrapManager.php(384): Drush\Boot\BootstrapManager->bootstrapToPhaseIndex(5, Object(Consolidation\AnnotatedCommand\AnnotationData))
#10 /app/vendor/drush/drush/src/Boot/BootstrapHook.php(32): Drush\Boot\BootstrapManager->bootstrapToPhase('full', Object(Consolidation\AnnotatedCommand\AnnotationData))
#11 /app/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(44): Drush\Boot\BootstrapHook->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#12 /app/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(36): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->doInitializeHook(Object(Drush\Boot\BootstrapHook), Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#13 /app/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(29): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Object(Drush\Boot\BootstrapHook), Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#14 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(145): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#15 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(335): Consolidation\AnnotatedCommand\CommandProcessor->initializeHook(Object(Symfony\Component\Console\Input\ArgvInput), Array, Object(Consolidation\AnnotatedCommand\AnnotationData))
#16 /app/vendor/symfony/console/Command/Command.php(221): Consolidation\AnnotatedCommand\AnnotatedCommand->initialize(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /app/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /app/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /app/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /app/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /app/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /app/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#23 /app/vendor/drush/drush/drush(4): require('/app/vendor/dru...')
#24 {main}`

**BLT doctor output**
+----------------------+-----------------------------------------------+
| Property             | Value                                         |
+----------------------+-----------------------------------------------+
| %paths.%root         | /app/docroot                                  |
| %paths.%site         | sites/default                                 |
| %paths.%modules      | sites/all/modules                             |
| %paths.%themes       | sites/all/themes                              |
| %paths.%config-sync  | /app/config/default                           |
| %paths.%files        | sites/default/files                           |
| %paths.%temp         | /tmp                                          |
| %paths.%private      | /app/files-private                            |
| admin-theme          | admin_detroitmi                               |
| alias-searchpaths.0  | /app/drush/sites                              |
| blt-version          | 13.5.1.0                                      |
| bootstrap            | Successful                                    |
| composer-version     | Composer version 2.0.8 2020-12-03 17:20:38    |
| config-sync          | /app/config/default                           |
| db-driver            | mysql                                         |
| db-hostname          | database                                      |
| db-name              | acquia                                        |
| db-password          | acquia                                        |
| db-port              | 3306                                          |
| db-status            | Connected                                     |
| db-username          | acquia                                        |
| drupal-settings-file | sites/default/settings.php                    |
| drupal-version       | 9.4.6                                         |
| drush-alias-files.0  | /app/drush/sites/default.site.yml             |
| drush-alias-files.1  | /app/drush/sites/detroitatwork.site.yml       |
| drush-alias-files.2  | /app/drush/sites/detroitmi.localhost.site.yml |
| drush-alias-files.3  | /app/drush/sites/detroitmi.site.yml           |
| drush-alias-files.4  | /app/drush/sites/intranet.site.yml            |
| drush-alias-files.5  | /app/drush/sites/stormwater.site.yml          |
| drush-alias-files.6  | /app/drush/sites/the-neighborhoods.site.yml   |
| drush-alias-files.7  | /app/drush/sites/training.detroitmi.site.yml  |
| drush-conf.0         | /app/vendor/drush/drush/drush.yml             |
| drush-conf.1         | /app/drush/drush.yml                          |
| drush-script         | /app/vendor/drush/drush/drush                 |
| drush-temp           | /tmp                                          |
| drush-version        | 11.1.1                                        |
| files                | sites/default/files                           |
| install-profile      | varbase                                       |
| modules              | sites/all/modules                             |
| php-bin              | /usr/local/bin/php                            |
| php-os               | Linux                                         |
| private              | /app/files-private                            |
| root                 | /app/docroot                                  |
| site                 | sites/default                                 |
| temp                 | /tmp                                          |
| theme                | detroitmi                                     |
| themes               | sites/all/themes                              |
| uri                  | http://default                                |
+----------------------+-----------------------------------------------+

**System information**
* Operating system type: linux
* Operating system version: ubuntu 20
* BLT version: 13.5.1

**Comment by jedgar1mx** [comment]
It looks like our team accidentally blew up our dev env during some testing so when our CI was pulling the database dump for testing the test server would just error out. Sorry for the false alarm. :(
