### ISSUE TITLE
DX-5184: BLT 13.5.2 New Project Error

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#4618]
**Describe the bug**
Starting a new project throws:

```
Fatal error: Uncaught Error: Class "Webmozart\PathUtil\Path" not found in /Users/mike.madison/git/examples/blt-error/vendor/acquia/blt/src/Robo/Commands/Blt/UpdateCommand.php:123
Stack trace:
#0 /Users/mike.madison/git/examples/blt-error/vendor/acquia/blt/src/Robo/Commands/Blt/UpdateCommand.php(61): Acquia\Blt\Robo\Commands\Blt\UpdateCommand->initGitignore()
#1 [internal function]: Acquia\Blt\Robo\Commands\Blt\UpdateCommand->addToProject(Array)
#2 /Users/mike.madison/git/examples/blt-error/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#3 /Users/mike.madison/git/examples/blt-error/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /Users/mike.madison/git/examples/blt-error/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /Users/mike.madison/git/examples/blt-error/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(350): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /Users/mike.madison/git/examples/blt-error/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/mike.madison/git/examples/blt-error/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/mike.madison/git/examples/blt-error/vendor/acquia/blt/src/Robo/Application.php(31): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/mike.madison/git/examples/blt-error/vendor/symfony/console/Application.php(273): Acquia\Blt\Robo\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/mike.madison/git/examples/blt-error/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/mike.madison/git/examples/blt-error/vendor/consolidation/robo/src/Runner.php(282): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/mike.madison/git/examples/blt-error/vendor/acquia/blt/src/Robo/Blt.php(264): Robo\Runner->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Acquia\Blt\Robo\Application), Array)
#13 /Users/mike.madison/git/examples/blt-error/vendor/acquia/blt/bin/blt-robo-run.php(35): Acquia\Blt\Robo\Blt->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /Users/mike.madison/git/examples/blt-error/vendor/acquia/blt/bin/blt-robo.php(15): require_once('/Users/mike.mad...')
#15 /Users/mike.madison/git/examples/blt-error/vendor/acquia/blt/bin/blt(11): require_once('/Users/mike.mad...')
#16 {main}
  thrown in /Users/mike.madison/git/examples/blt-error/vendor/acquia/blt/src/Robo/Commands/Blt/UpdateCommand.php on line 123

```

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `composer create-project acquia/drupal-recommended-project`
2. add blt with `composer require acquia/blt`
3. See error

**Expected behavior**
Not this.

**Comment by mikemadison13** [comment]
My hunch is that this was caused by Drush resolving https://github.com/drush-ops/drush/issues/5279

**Comment by mikemadison13** [comment]
@danepowell this didn't fail during our testing because it looks like we are still adding webmozart in the orca builds for some reason, see https://github.com/acquia/blt/actions/runs/3341174700/jobs/5532108317#step:6:245. At first glance, i'm not sure why / how that is.

**Comment by mikemadison13** [comment]
we are blocked from "fixing" this by applying the symfony/filesystem approach that drush took on due to the incompatibility with drupal/core-dev and the newer version of consolidation/site-alias (and symfony/filesystem). so, it seems like the only choice is to include webmozart as a dependency of blt at this time. thoughts?
