### ISSUE TITLE
blt local:refresh fails after upgrade to 8.6.0-beta1

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#699]
My system information:
* Operating system type: OSX
* Operating system version: 10.11.6
* BLT version: 8.6.0-beta1

Output of `blt doctor`:
```
172-16-245-2:Meyers8 rg173$ blt doctor
Buildfile: /Users/rg173/Sites/Meyers8/vendor/acquia/blt/phing/build.xml

blt > doctor:

Changed current directory to /home/vagrant/.composer
+----------------------+----------------------------------------------------------------------------------+
| Property             | Value                                                                            |
+----------------------+----------------------------------------------------------------------------------+
| %paths               |                                                                                  |
|  - %root             | /var/www/meyers8/docroot                                                         |
|  - %site             | sites/default                                                                    |
|  - %modules          | modules                                                                          |
|  - %themes           | themes                                                                           |
|  - %config-sync      | /var/www/meyers8/config/default                                                  |
|  - %files            | sites/default/files                                                              |
|  - %private          | /var/www/meyers8/files-private                                                   |
|  - %temp             | /tmp                                                                             |
| admin-theme          | seven                                                                            |
| blt-version          | 8.6.0-beta1                                                                      |
| bootstrap            | Successful                                                                       |
| config-sync          | /var/www/meyers8/config/default                                                  |
| db-driver            | mysql                                                                            |
| db-hostname          | localhost                                                                        |
| db-name              | drupal                                                                           |
| db-password          | drupal                                                                           |
| db-port              | 3306                                                                             |
| db-username          | drupal                                                                           |
| drupal-settings-file | sites/default/settings.php                                                       |
| drupal-version       | 8.2.3                                                                            |
| drush-alias-files    | /var/www/meyers8/docroot/../drush/site-aliases/aliases.drushrc.php               |
|                      | /var/www/meyers8/docroot/../drush/site-aliases/example.acsf.aliases.drushrc.php  |
|                      | /var/www/meyers8/docroot/../drush/site-aliases/example.local.aliases.drushrc.php |
| drush-conf           | /var/www/meyers8/drush/drushrc.php                                               |
| drush-script         | /var/www/meyers8/vendor/drush/drush/drush.php                                    |
| drush-temp           | /tmp                                                                             |
| drush-version        | 9.0.0-alpha1                                                                     |
| files                | sites/default/files                                                              |
| install-profile      | standard                                                                         |
| local-drushrc        | /var/www/meyers8/docroot/sites/default/local.drushrc.php                         |
| local-settings       | /var/www/meyers8/docroot/sites/default/settings/local.settings.php               |
| modules              | modules                                                                          |
| php-bin              | /usr/bin/php                                                                     |
| php-conf             | /etc/php/5.6/cli/php.ini                                                         |
| php-os               | Linux                                                                            |
| private              | /var/www/meyers8/files-private                                                   |
| root                 | /var/www/meyers8/docroot                                                         |
| site                 | sites/default                                                                    |
| temp                 | /tmp                                                                             |
| theme                | meyers                                                                           |
| themes               | themes                                                                           |
| uri                  | http://meyers8.default.local                                                     |
| user                 |                                                                                  |
+----------------------+----------------------------------------------------------------------------------+
+--------------------------+---------------------------------------------------------------------------------+
| Check                    | Outcome                                                                         |
+--------------------------+---------------------------------------------------------------------------------+
| checkDocrootExists       | Found docroot.                                                                  |
| checkCoreExists          | Drupal core exists                                                              |
| checkSettingsFile        | BLT settings are included in settings file.                                     |
| checkLocalSettingsFile   | Found your local settings file.                                                 |
| checkLocalDrushFile      | Found your local drush settings file.                                           |
| checkUri                 | $options['uri'] is set.                                                         |
| checkUriResponse         | Received a response from site http://meyers8.default.local.                     |
| checkFileSystem:%files   | Public files directory is writable.                                             |
| checkFileSystem:%private | Private files directory is writable.                                            |
| checkFileSystem:%temp    | Temporary files directory is writable.                                          |
| checkDbConnection        | Connected to database.                                                          |
| checkDrupalBootstrapped  | Bootstrapped Drupal via drush.                                                  |
| checkDrupalInstalled     | Drupal is installed.                                                            |
| checkCaching:page        | Drupal cache is disabled.                                                       |
| checkCaching:css         | CSS preprocessing is disabled.                                                  |
| checkCaching:js          | JS preprocessing is disabled.                                                   |
| checkNvmExists           | NVM does not exist.                                                             |
|                          |                                                                                 |
|                          | It is recommended that you use NVM to manage multiple versions of NodeJS on one |
|                          | machine.                                                                        |
|                          | Instructions for installing NVM can be found at:                                |
|                          |   https://github.com/creationix/nvm#installation                                |
| checkComposer:require    | acquia/blt is in composer.json's require object.                                |
| checkComposer:plugins    | hirak/prestissimo plugin for composer is installed.                             |
| checkBehat:exists        | Behat local settings file exists.                                               |
| checkBehat:uri           | base_url in tests/behat/local.yml does not match the site URI.                  |
|                          |   Behat base_url is set to "http://meyers8.local".                              |
|                          |   Drush site URI is set to http://meyers8.default.local.                        |
| checkProjectYml:keys     | project.yml has no deprecated keys.                                             |
| checkAcsfConfig          | BLT settings are included in your pre-settings-php include.                     |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set                                  |
+--------------------------+---------------------------------------------------------------------------------+

BUILD FINISHED

Total time: 14.9772 seconds

```

When I run this command:
```
blt local:refresh
```

I get the following output:
```
172-16-245-2:Meyers8 rg173$ blt local:refresh
Buildfile: /Users/rg173/Sites/Meyers8/vendor/acquia/blt/phing/build.xml

blt > setup:git-hooks:

   [delete] Deleting: /Users/rg173/Sites/Meyers8/.git/hooks/pre-commit
   [delete] Deleting: /Users/rg173/Sites/Meyers8/.git/hooks/commit-msg
     [echo] Symlinking /Users/rg173/Sites/Meyers8/scripts/git-hooks/pre-commit to /Users/rg173/Sites/Meyers8/vendor/acquia/blt/scripts/git-hooks/pre-commit
pre-commit -> /Users/rg173/Sites/Meyers8/vendor/acquia/blt/scripts/git-hooks/pre-commit
commit-msg -> /Users/rg173/Sites/Meyers8/vendor/acquia/blt/scripts/git-hooks/commit-msg

BUILD FAILED
exception 'IOException' with message 'FileSystem::chmod() FAILED. Cannot chmod /Users/rg173/Sites/Meyers8/vendor/acquia/blt/scripts/git-hooks/commit-msg. Mode 755.' in /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/system/io/FileSystem.php:621
Stack trace:
#0 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/system/io/PhingFile.php(951): FileSystem->chmod('/Users/rg173/Si...', 493)
#1 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/tasks/system/ChmodTask.php(211): PhingFile->setMode(493)
#2 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/tasks/system/ChmodTask.php(180): ChmodTask->chmodFile(Object(PhingFile), 493)
#3 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/tasks/system/ChmodTask.php(118): ChmodTask->chmod()
#4 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/UnknownElement.php(100): ChmodTask->main()
#5 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#6 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#7 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#8 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#9 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Project.php(868): Project->executeTarget('local:refresh')
#10 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Phing.php(723): Project->executeTargets(Array)
#11 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Phing.php(200): Phing->runBuild()
#12 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Phing.php(347): Phing::start(Array, NULL)
#13 /Users/rg173/Sites/Meyers8/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)
#14 /Users/rg173/Sites/Meyers8/vendor/phing/phing/bin/phing(14): require_once('/Users/rg173/Si...')
#15 {main}
Total time: 0.6816 seconds

#0 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/system/io/PhingFile.php(951): FileSystem->chmod('/Users/rg173/Si...', 493)
#1 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/tasks/system/ChmodTask.php(211): PhingFile->setMode(493)
#2 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/tasks/system/ChmodTask.php(180): ChmodTask->chmodFile(Object(PhingFile), 493)
#3 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/tasks/system/ChmodTask.php(118): ChmodTask->chmod()
#4 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/UnknownElement.php(100): ChmodTask->main()
#5 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#6 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#7 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#8 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#9 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Project.php(868): Project->executeTarget('local:refresh')
#10 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Phing.php(723): Project->executeTargets(Array)
#11 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Phing.php(200): Phing->runBuild()
#12 /Users/rg173/Sites/Meyers8/vendor/phing/phing/classes/phing/Phing.php(347): Phing::start(Array, NULL)
#13 /Users/rg173/Sites/Meyers8/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)
#14 /Users/rg173/Sites/Meyers8/vendor/phing/phing/bin/phing(14): require_once('/Users/rg173/Si...')
#15 {main}FileSystem::chmod() FAILED. Cannot chmod /Users/rg173/Sites/Meyers8/vendor/acquia/blt/scripts/git-hooks/commit-msg. Mode 755.

```

And I expected this to happen: the command to successfully run setup tasks.

**Comment by grasmash** [comment]
Thanks for posting, and for testing the beta release. Looks like it's unable to set the file permissions on your git hooks. 

Can you verify that symlinks to the git-hooks exist in `/Users/rg173/Sites/Meyers8/.git/hooks` and that they are executable and/or owned by you?

**Comment by bobbygryzynger** [comment]
@grasmash - looks correct to me:
```sh
lrwxr-xr-x   1 rg173  staff   73 Nov 21 16:01 commit-msg -> /Users/rg173/Sites/Meyers8/vendor/acquia/blt/scripts/git-hooks/commit-msg
lrwxr-xr-x   1 rg173  staff   73 Nov 21 16:01 pre-commit -> /Users/rg173/Sites/Meyers8/vendor/acquia/blt/scripts/git-hooks/pre-commit

```

**Comment by danepowell** [comment]
Pretty sure this is a dupe of #719

**Comment by bobbygryzynger** [comment]
@danepowell - seems pretty likely that's the case. I'll close this for now and reopen if your fix doesn't address the problem for me.
