### ISSUE TITLE
BLT (> 8.6.6) only runnable from repo root

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#952]
My system information:
* Operating system type: Ubuntu
* Operating system version: 14.04
* BLT version: 8.6.8

When I run this command (from the repo root):
```
$ blt
```

I get the following output:
```
Buildfile: /var/www/site/vendor/acquia/blt/phing/build.xml
     [echo] repo.root /var/www/site

blt > list:


__________.____  ___________
\______   \    | \__    ___/
 |    |  _/    |   |    |
 |    |   \    |___|    |
 |______  /_______ \____|
        \/        \/

Default target:
-------------------------------------------------------------------------------
 list

Main targets:
-------------------------------------------------------------------------------
 acsf:init                     Initializes ACSF support for project.
 acsf:init:drush               Refreshes the acsf settings and hook files.
 ci:pipelines:init             Initializes default Acquia Pipelines configuration for this project.
```

When I run this command (from docroot, for example):
```
$ blt
```

I get the following output:
```
#0 /var/www/site/vendor/phing/phing/classes/phing/Phing.php(1272): Phing::__import('vendor/acquia/b...', NULL)
#1 /var/www/site/vendor/phing/phing/classes/phing/Phing.php(852): Phing::import('vendor.acquia.b...')
#2 /var/www/site/vendor/phing/phing/classes/phing/Phing.php(791): Phing->createLogger()
#3 /var/www/site/vendor/phing/phing/classes/phing/Phing.php(663): Phing->addBuildListeners(Object(Project))
#4 /var/www/site/vendor/phing/phing/classes/phing/Phing.php(200): Phing->runBuild()
#5 /var/www/site/vendor/phing/phing/classes/phing/Phing.php(347): Phing::start(Array, NULL)
#6 /var/www/site/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)
#7 /var/www/site/vendor/phing/phing/bin/phing(14): require_once('/var/www/site...')
#8 {main}Error importing vendor/acquia/blt/phing/phingcludes/BltLogger.php
```

I can trace this back to the addition in #922 to `/blt.sh` file.
TBH, I'm not 100% sure how to fix this, I can just tell that when I revert this line, the application works as expected.

**Comment by grasmash** [comment]
@dpagini This was fixed in https://github.com/acquia/blt/releases/tag/8.6.9.

**Comment by dpagini** [comment]
Ah, sorry about that, thank you! I hadn't upgraded b/c of the "Pre-Release" tag.
